### ISSUE TITLE
Error when publishing custom element type

### ISSUE THREAD

**Issue by asecondwill** [dnadesign/silverstripe-elemental#100]
I made an element, very simple one.  When i add it to the page I can publish/save the element, but then I have to return to the page view and publish the page to make it display - the page won't publish.  I get a "No response" errror.  It also won't publish from the batch actions menu.  

Any clues what I've done wrong here? Finding it hard to debug. 

````
<?php

class HeroAndTextElement extends BaseElement {

	private static $title = "Hero And Text";

	private static $description = "Hero with text overlay";

  private static $db = array(
       'Caption' => 'HTMLText'
   );
   private static $has_one = array(
         'Image' => 'Image'
     );
 private static $enable_title_in_template = true;

	public function getCMSFields() {
    $this->beforeUpdateCMSFields(function ($fields) {
           $uploadField = UploadField::create('Image', 'Image')
               ->setAllowedFileCategories('image')
               ->setAllowedMaxFileNumber(1)
               ->setFolderName('Uploads/heros');
           $fields->addFieldToTab('Root.Main', $uploadField);
           $caption = HTMLEditorField::create('Caption', 'Caption');
           $caption->setRightTitle('Optional');
           $fields->addFieldToTab('Root.Main', $caption);
       });
       return parent::getCMSFields();
	}
}

````

**Comment by pitchandtone** [comment]
Which branch are you on?

**Comment by KINKCreative** [comment]
I think this is related to an issue I found. Because the Page is set to $owns the ElementalArea by the provided extension, the Page will try to publish the ElementalArea. The ElementalArea by default has no canPublish method / canEdit methods and publishing such pages as a non-admin will throw the error that "the user can't publish the ChangeSet" (along those lines).

I fixed it with this:

```
<?php

use SilverStripe\ORM\DataExtension;
use SilverStripe\Security\Permission;

class ElementalAreaPublishExtension extends DataExtension {

  public function canPublish($member = NULL) {
    return Permission::checkMember($member, "CMS_ACCESS");
  }

}
```

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
