### ISSUE TITLE
BaseElement canX methods sometimes return null, which is incorrect

### ISSUE THREAD

**Issue by GuySartorelli** [dnadesign/silverstripe-elemental#1003]
`BaseElement` canX methods are returning `null` in some cases.

As per https://github.com/silverstripe/silverstripe-framework/issues/10184 it is established that the return type for `canX` methods on a `DataObject` should be boolean - `null` is not a valid return type from these methods.

## Acceptance criteria
- [x] All canX methods in `BaseElement` return a boolean value.

## PRs
- https://github.com/silverstripe/silverstripe-elemental/pull/1004

**Comment by sabina-talipova** [comment]
Issue was fixed.
