### ISSUE TITLE
Update documentation for CMS 5 version

### ISSUE THREAD

**Issue by GuySartorelli** [dnadesign/silverstripe-elemental#1007]
The docs in the `5` branch haven't been updated and still reference CMS 4 stuff all over the place, including links to CMS 4 docs.
There are also some `yml` hints missing for code blocks - may as well add those at the same time.

## Acceptance criteria
- [x] Links to docs link to the CMS 5 docs
- [x] There are no references to CMS 4 except where needed to refer to the past
- [x] Code blocks which are for a specific programming language have that language in the code block hint.

## PRs
- https://github.com/silverstripe/silverstripe-elemental/pull/1008

**Comment by maxime-rainville** [comment]
I moved this to peer review since all the ACs appear to have been met.

**Comment by GuySartorelli** [comment]
Okay. I can't remember what state the PR is in though so whoever reviews it should make sure they actively search for outdated docs.
