### ISSUE TITLE
Apply TopPage extensions by default in CMS 5

### ISSUE THREAD

**Issue by GuySartorelli** [dnadesign/silverstripe-elemental#1009]
[The docs about the `TopPage` extensions](https://github.com/silverstripe/silverstripe-elemental/blob/4/docs/en/advanced_setup.md#top-page-reference-performance-enhancement) say these will be applied by default in CMS 5. We should do that.

## Acceptance Criteria
- [x] ~~The extensions that say they're applied by default _are_ applied by default~~
- [ ] This doesn't cause any obvious regressions
- [ ] This is mentioned in the changelog
- [ ] Top Page Extension is folded back in the base element

## PRs
- https://github.com/silverstripe/silverstripe-elemental/pull/1010
- https://github.com/silverstripe/silverstripe-elemental/pull/1022
- https://github.com/silverstripe/developer-docs/pull/94
- https://github.com/silverstripe/developer-docs/pull/113

**Comment by emteknetnz** [comment]
@sabina-talipova You'll need to do an additional PR to the CMS 4 version to add `@deprecated` and `Deprecation::notice()` (probably wrapped in `Deprecation::withNoReplacement()) to any classes + methods being removed

**Comment by sabina-talipova** [comment]
@emteknetnz could you check this failed CI, please.
https://github.com/silverstripe/silverstripe-cms/actions/runs/3467505777/jobs/5809980321

**Comment by emteknetnz** [comment]
All linked PRs have been merged
