### ISSUE TITLE
Add module to transifex?

### ISSUE THREAD

**Issue by chillu** [dnadesign/silverstripe-elemental#103]
Technically not part of our [supported module standard](https://www.silverstripe.org/software/addons/supported-modules-definition/), but high value in my opinion: It reduces the barrier for translators significantly. It's not only the initial translation in a web UI rather than YAML, but also the fact that you can stay up to date with any language changes/additions through that service.

That brings up a wider point: Making this module part of the CWP recipe means releases by default would be handled through our`cow` release tooling for module releases. It helps us keep CWP releases manageable across 30+ modules. Which should take care of updating translations automatically: https://github.com/silverstripe/cow/blob/a748522057840aaee2d6bad241df6e3eb45d63f8/src/Steps/Release/UpdateTranslations.php#L20

We've got a Transifex organisation that we can add new maintainers to, so the tooling and workflow is already in place. And we'd be happy to "host" those translations under https://www.transifex.com/silverstripe/

You can of course create module releases outside of the CWP recipe cycle - in which case it would make sense to use `cow` as well. Either way, even if you don't want that complexity for releases driven by module maintainers at DNA, we could just keep translations to a quarterly update schedule.

@adrexia @pitchandtone @wilr What do you think?

**Comment by pitchandtone** [comment]
Sounds good.

**Comment by robbieaverill** [comment]
Done in #112
