### ISSUE TITLE
TopPageExtension adds an extra field to content block

### ISSUE THREAD

**Issue by maxime-rainville** [dnadesign/silverstripe-elemental#1041]
When the TopPageExtension is applied to content blocks, it inadvertently adds an editable field to every content block.

This field is not meant to be directly editable/viewable by content authors. 

This affects CMS4 and CMS5, but is especially bad in CMS5 because the extension is now on by default.

![image](https://user-images.githubusercontent.com/1168676/222027667-20259332-ebff-4cf4-b7ef-0d84d60b70e8.png)

## Acceptance criteria
- "Top page" field is not displayed on the front end in both CMS4 and CMS5

## Related issue
- https://github.com/silverstripe/silverstripe-elemental/issues/1009

## PRs
- https://github.com/silverstripe/silverstripe-elemental/pull/1042

**Comment by GuySartorelli** [comment]
PR merged. The "and CMS 5" part will be resolved when it gets merged up.
