### ISSUE TITLE
RFC: Remove ModelAdmin

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#106]
From a UX perspective, content authors may find it confusing to manage content elements from two places: a model admin and from a page context.

My other justification for this is that if clients want to add a ModelAdmin it's a pretty small file that can be added to user code. We could make this a docs example instead?

**Comment by pitchandtone** [comment]
Fair point.

**Comment by robbieaverill** [comment]
We discussed yesterday that we could replace some of the function of the model admin with one or more reports, e.g. "total number of elements/element types" and for the virtual blocks a report like "show virtual elements that aren't linked to pages" etc

**Comment by wilr** [comment]
Removed from elemental v2. Developers could choose to provide an admin (or we can build another module)
