### ISSUE TITLE
Unable to save tags when using inline blocks

### ISSUE THREAD

**Issue by swytch** [dnadesign/silverstripe-elemental#1062]
After creating a tag, clicking anywhere, including the save button will clear the value.  Happens only when block is inline.  Repo here https://github.com/swytch/bugs

**Comment by GuySartorelli** [comment]
"tags" aren't a thing that exist in this module. I'm assuming, based on the repository you've linked to, that you mean tags from the `silverstripe/tagfield` module.

In the future, please include _all_ relevant information in the description of the issue itself, including reproduction steps.

In this case, I have been able to reproduce this issue.

**Comment by sabina-talipova** [comment]
I hope this issue was solved by [this PR](https://github.com/silverstripe/silverstripe-tagfield/pull/256) as part of [this issue](https://github.com/silverstripe/silverstripe-tagfield/issues/252)
