### ISSUE TITLE
Review cms-testing-recipes

### ISSUE THREAD

**Issue by sabina-talipova** [dnadesign/silverstripe-elemental#1066]
## Description
This repository ['cms-testing-recipes'](https://github.com/silverstripeltd/cms-testing-recipes) contains a big number of branches that are no longer relevant. Sometimes it is very difficult to determine which should be uploaded to the server. It is necessary to revise existing branches and delete those that are not relevant at the moment. This revision should also be done at least after every release.
You should also review the process of preparing a version for deploy to the server. It may be worth developing some tool to facilitate this process and make it more understandable, since we do not use it as often.

## AC's
- [ ] All old and temporary created branches are reviewed and removed.
- [ ] The process of preparing a version for deploy is reviewed.

**Comment by GuySartorelli** [comment]
I think you've created this in the wrong repo - should probably be in product-issues

**Comment by sabina-talipova** [comment]
Created by accident in wrong repo. Close.
