### ISSUE TITLE
Optimise SiteTree search when elemental is installed

### ISSUE THREAD

**Issue by emteknetnz** [dnadesign/silverstripe-elemental#1067]
I raised this card after getting feedback from a couple of developers about poor performance in the CMS being a pain point, particularly on a large customer website - slack thread (internal) https://silverstripeltd.slack.com/archives/CLXKD9X51/p1614061096035300?thread_ts=1614061096.035300&cid=CLXKD9X51

The site tree search (magnifying glass at the top right of the "pages" seciton in the CMS) is a performance bottleneck, and gets significantly worse with elemental installed. Performance scales badly and get worse the more pages + elements there are

I had a quick look through the code path with elemental installed, specifically in [ElementSiteTreeFilterSearch](https://github.com/silverstripe/silverstripe-elemental/blob/5/src/Controllers/ElementSiteTreeFilterSearch.php) (which copy pastes a lot from [CMSSiteTreeFilter](https://github.com/silverstripe/silverstripe-cms/blob/5/code/Controllers/CMSSiteTreeFilter.php) and overrides it, rather than being an extension)
- There's a lot of PartialMatchFilter on multiple database fields, which translation to a bunch of SQL `WHERE Field LIKE '%search_term%'` on unindexed columns that contain text, as you'd expect, probably can't do much easily without adding in something like elastic specifically for CMS search, which is non-trivial
- More interestingly, there's [this](https://github.com/silverstripe/silverstripe-elemental/blob/5/src/Controllers/ElementSiteTreeFilterSearch.php#L44) seemingly unoptimized code:

```php
        // Get an array of SiteTree record IDs that match the search term in nested element data
        /** @var ArrayList $siteTrees */
        $siteTrees = $query->filterByCallback(function (SiteTree $siteTree) {
            // Filter by elemental PHP
            if (!$siteTree->hasExtension(ElementalPageExtension::class)) {
                return false;
            }

            // Check whether the search term exists in the nested page content
            $pageContent = $siteTree->getElementsForSearch();
            return stripos($pageContent ?? '', $this->params['Term'] ?? '') !== false;
        });

        if ($siteTrees->count()) {
            // Apply the list of IDs as an extra filter
            $this->extraTermFilters['ID:ExactMatch'] = $siteTrees->column('ID');
        }
```

Where `$siteTree->getElementsForSearch();` will do a bunch of N+1 stuff in [ElementalPageExtension](https://github.com/silverstripe/silverstripe-elemental/blob/5/src/Extensions/ElementalPageExtension.php)

Given the recent work on [eager loading](https://github.com/silverstripe/silverstripe-framework/pull/10783) which specifically deals with N + 1 I think this would be a good candidate for using the new eagerLoading() API, or at least doing something similar in a more manual approach where the aim is to do "one big query early" rather than "multiple little queries in a loop"

## Acceptance criteria
- Review site tree search and identify possible performance gain from using Eager loading, especially Elemental Content search
- Validate performance gain for a site with a substantial number of blocks and page (~2000 pages, ~5000 blocks, ~5 block types)
- Presuming they are performance gains, report them on the 5.1 changelog
- Update relevant modules to require framework 5.1

## Related
- https://github.com/silverstripe/.github/issues/68

## Follow up issues
- https://github.com/silverstripe/silverstripe-framework/issues/10865

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10840
- https://github.com/silverstripe/silverstripe-framework/pull/10841
- https://github.com/silverstripe/silverstripe-elemental/pull/1069
- https://github.com/silverstripe/developer-docs/pull/291

**Comment by emteknetnz** [comment]
This is actually seems very unoptimized ... though at the same time I'm not sure if there's scope to optimize.`BaseElement::getContentForSearchIndex()` will call `BaseElement::forTemplate()` which will call `ViewableData::renderWith()` ... so fully rendering every element. About as inefficient as you could get

This makes sense as it's a safe way to ensure that you're only "indexing for search" fields that are actually shown.  This is nice for developers because you don't need to separately config searchable fields on each element - however big downside here is we don't know ahead of times which fields to search for content in without a render.

e.g. the basic content block `ElementContent` has `private static $db = ['HTML' => 'HTMLText']` and no `$searchable_fields` config

If we're to optimize this we'd probably need to just assume every varchar/htmltext style field on every element is cms search indexable and then maybe provide an opt-out via config

**Comment by maxime-rainville** [comment]
If your block has relations that are used to generate the content, I take it those won't be pick up with that `render_elements_for_cms_search` turn off?

**Comment by emteknetnz** [comment]
That's correct, only content directly on the element will be picked up by search. The assumption I'm making is that bulk of content relevant to search will be on the element itself and not on a relation.  This will lead to a loss of search accuracy in some cases, though the idea is that increase in performance outweighs this downside.

**Comment by GuySartorelli** [comment]
PRs merged, no remaining ACs
