### ISSUE TITLE
Element Controllers not nestable

### ISSUE THREAD

**Issue by rasstislav** [dnadesign/silverstripe-elemental#1086]
Hello,

I have the same issue as mentioned here: dnadesign/silverstripe-elemental-list#29.

Is it solvable?

Thank for response :-)

**Comment by GuySartorelli** [comment]
Closing as this is related to a non-supported module.
If changes are required here for that module to work, and they are reasonable changes, they can be submitted as a pull request as a part of solving the issue for that module.
