### ISSUE TITLE
Fluent - Show PublishedInLocale State in Backend-ElementalArea 

### ISSUE THREAD

**Issue by MLindenhofer** [dnadesign/silverstripe-elemental#1098]
Hi,

We're using the fluent module in most of our projects, especially when it comes to use it in combination with elemental there is one  feature which would just be great to have -> a "Visible in Locale" column / flag something which shows if a current Block is visible in a Locale or not in the Backend-ElementalArea.

Maybe like this:
![Bildschirmfoto 2023-08-25 um 11 27 25](https://github.com/silverstripe/silverstripe-elemental/assets/68067510/a2ae29e9-56ea-42e7-8064-c3266d24e3b7)

There is a GridField Extension which comes together with the fluent-module itself. Maybe this is a inspiration.
[VisibleLocalesColum - Fluent Module](https://github.com/tractorcow-farm/silverstripe-fluent/blob/1d3e58b564cc38ee73ad67b299998c7902884d3a/src/Forms/VisibleLocalesColumn.php)

We would love to integrate it by ourselfs, but as this part is managed by react-only and to be honest, we don't have an idea on how to do do it. So we decide to write this feature-request.

Thanks in advance

**Comment by GuySartorelli** [comment]
Thanks for suggesting this - however as this is a feature we aren't likely to implement any time soon I will close this issue.

If you find someone who is willing to implement this for you, feel free to reopen a PR - though note that if it is specifically for the fluent module, it should be raised there. If it's for making the react component more flexible, that's fine to raise here.
