### ISSUE TITLE
BUG: handling of linked element in virtual element failed

### ISSUE THREAD

**Issue by rasstislav** [dnadesign/silverstripe-elemental#1099]
Hello,

I have [ElementForm](https://github.com/dnadesign/silverstripe-elemental-userforms/blob/3.3.3/src/Model/ElementForm.php)  as  [LinkedElement in ElementVirtual](https://github.com/dnadesign/silverstripe-elemental-virtual/blob/44635640e73b0f076618ac8135f738a8f3a4efe3/src/Model/ElementVirtual.php#L21) and after submitting the form I got an error:

`Fatal error: Element $id not found for this page in /var/www/html/vendor/dnadesign/silverstripe-elemental/src/Extensions/ElementalContentControllerExtension.php on line 62`.

## PRs
- https://github.com/silverstripe/silverstripe-elemental/pull/1100

**Comment by GuySartorelli** [comment]
Thanks for pointing this out.
Based on the additional context provided in your pull request, it sounds like this is something that should and can be resolved in the virtual module instead. I'll close this issue, but if you find that this is something that needs to be handled here instead please provide additional context explaining why.
