### ISSUE TITLE
Infinite rendering loop when rendering a FormBuilder as part of an ElementAction

### ISSUE THREAD

**Issue by emteknetnz** [dnadesign/silverstripe-elemental#1122]
When rendering a FormBuilder component as part of an ElementAction, ElementEditor will go into an infinite loop of re-rendering ElementEditor

This started happening as part of this change https://github.com/silverstripe/silverstripe-elemental/pull/1044

## PR
- https://github.com/silverstripe/silverstripe-elemental/pull/1123

**Comment by GuySartorelli** [comment]
Merged
