### ISSUE TITLE
Add versioned badge to elements

### ISSUE THREAD

**Issue by emteknetnz** [dnadesign/silverstripe-elemental#1124]
Linkfield v4 is getting a textual versioned badge along with a disc icon so that it's similar to the versioned badge in the sitetree as part of [this issue](https://github.com/silverstripe/silverstripe-linkfield/issues/7)

![image](https://github.com/silverstripe/silverstripe-elemental/assets/4809037/ee4b2c96-0a53-4892-8de6-fcddcd129c23)

Recommendation from internal design team is to also add this badge to elemental

Should also consider getting rid of the blue icon dirty state from elemental since it's inconsistent with the rest of the CMS

## Acceptance criteria
- Labels are added to Elemental blocks in-line with the mock up above
- Labels for Draft and modified are visible.
- No labels are shown when the block content reflects the latest published version.
- Validate with design team if the blue dot should have a matching label.

## Note
- There's a blue "dirty state" dot that shows when editing a block. We are not sure if that should have a matching label. Please validate with UX team.

## PR
- https://github.com/silverstripe/silverstripe-elemental/pull/1137
- https://github.com/silverstripe/silverstripe-elemental/pull/1138

**Comment by sabina-talipova** [comment]
It's waiting when merge ups  for `admin`, `asset-admin` and `cms` will be completed
