### ISSUE TITLE
HTMLEditorField::setRows method doesn't work in Elemental

### ISSUE THREAD

**Issue by sabina-talipova** [dnadesign/silverstripe-elemental#1132]
## Description
HTMLEditorField::setRows method doesn't work in Elemental since `height` attribute is not passed.

## Related issue
- https://github.com/silverstripe/silverstripe-admin/pull/1588
- https://github.com/silverstripe/silverstripe-admin/issues/1650

## Replication steps

Add the following to your content block and then try to inline edit it

```php
    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        $fields->removeByName('Content');
        $fields->addFieldToTab('Root.Main', HTMLEditorField::create('OtherContent1')->setRows(2));
        $fields->addFieldToTab('Root.Main', HTMLEditorField::create('OtherContent2')->setRows(4));
        $fields->addFieldToTab('Root.Main', HTMLEditorField::create('OtherContent3')->setRows(5));
        $fields->addFieldToTab('Root.Main', HTMLEditorField::create('OtherContent4')->setRows(10));
  
        return $fields;
    }
```
 ## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11114
- https://github.com/silverstripe/silverstripe-admin/pull/1660

**Comment by GuySartorelli** [comment]
PRs merged
