### ISSUE TITLE
Broken multi WYSIWYG behat test

### ISSUE THREAD

**Issue by emteknetnz** [dnadesign/silverstripe-elemental#1142]
tests/Behat/features/multiple-wysiwyg-configs.feature:17

https://github.com/silverstripe/silverstripe-elemental/actions/runs/7726060510/job/21083852150

## PRs
- https://github.com/silverstripe/silverstripe-elemental/pull/1143

**Comment by sabina-talipova** [comment]
This issue should be already fixed in `5.1` by this [PR](https://github.com/silverstripe/silverstripe-elemental/pull/1139)

**Comment by GuySartorelli** [comment]
Sweet. Doing a merge-up now to see if that resolves it for `5`

**Comment by sabina-talipova** [comment]
CI passed https://github.com/silverstripe/silverstripe-elemental/actions/runs/7736041586
