### ISSUE TITLE
Validation can prevent the creation of new block

### ISSUE THREAD

**Issue by maxime-rainville** [dnadesign/silverstripe-elemental#1149]
### Module version(s) affected

4 and 5

### Description

Unlike Dataobject managed in a ModelAdmin, Elemental blocks have to be saved before the user can interact with them.

This means that it is some times necessary to suppress validation on block creation.

This is an inconvenience for developers and is counter-intuitive.

### How to reproduce

This code snippet illustrate the weird logic one has to go through to apply validation rules to a block while still allowing it to be created.

```php
<?php

use DNADesign\Elemental\Models\BaseElement;
use SilverStripe\Forms\FieldList;
use SilverStripe\LinkField\Form\LinkField;
use SilverStripe\LinkField\Form\MultiLinkField;
use SilverStripe\LinkField\Models\Link;

/**
 * @property Link $MyTestLink
 */
class TitleBlock extends BaseElement
{

    private static $table_name = 'TitleRequriedBlock';

    private static $singular_name = 'Block with required title';

    private static $plural_name = 'test link blocks';

    private static $description = 'A block with a that requires a Title';

    public function getSummary()
    {
        return '';
    }

    protected function provideBlockSchema()
    {
        $blockSchema = parent::provideBlockSchema();
        $blockSchema['content'] = $this->getSummary();
        return $blockSchema;
    }

    public function getType()
    {
        return 'Title Required Block';
    }

    public function validate()
    {
        $validator = parent::validate();
        // You need to add silly logic to allow the block to be created in the first place
        if ($this->isInDB() && trim($this->Title ?? '') === '') {
            $validator->addFieldError('Title', 'Title is required (this message is coming from block level)');
        }
        return $validator;
    }

}
```

### Possible Solution

Update BaseElement to skip validation on creation.

### Additional Context

Related card:
- https://github.com/silverstripe/silverstripe-elemental/issues/1179
- https://github.com/silverstripe/silverstripe-elemental/issues/1145
- https://github.com/silverstripe/silverstripe-elemental/issues/329

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

### Acceptance criteria
- A content block with validation rules can be created by a user even if the default values do not meet the validation rules.
- Further attempts to save or publish the content block are prevented unless the data is updated to pass validation.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11202
- https://github.com/silverstripe/silverstripe-elemental/pull/1172
- https://github.com/silverstripe/developer-docs/pull/499

**Comment by GuySartorelli** [comment]
@maxime-rainville You've said what should happen, and you have steps to reproduce.... but I assume what you really mean is that those are steps to reproduce a bug? Can you please update the description to talk about what the bug actually is (i.e. what the current behaviour is)?

**Comment by maxime-rainville** [comment]
I added extra details.

**Comment by maxime-rainville** [comment]
I'm assuming this can be done without API change. But I'm happy to push it to CMS 6 if not.
