### ISSUE TITLE
RFC: Overload SiteTree::Content by default when the module is installed

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#116]
It might be nice, since this is going to be moving towards the default way to edit content in SilverStripe in future, that we can install the module and have it work out of the box (i.e. rather than changing `$Content` to `$ElementalArea` in your theme or page templates).

A change might look like this:

```diff
diff --git a/src/Extensions/ElementalPageExtension.php b/src/Extensions/ElementalPageExtension.php
index d650aff..58181b9 100644
--- a/src/Extensions/ElementalPageExtension.php
+++ b/src/Extensions/ElementalPageExtension.php
@@ -3,6 +3,7 @@
 namespace DNADesign\Elemental\Extensions;
 
 use DNADesign\Elemental\Models\ElementalArea;
+use SilverStripe\ORM\FieldType\DBHTMLText;
 
 class ElementalPageExtension extends ElementalAreasExtension
 {
@@ -19,4 +20,14 @@ class ElementalPageExtension extends ElementalAreasExtension
     private static $owns = [
         'ElementalArea'
     ];
+
+    /**
+     * Overloads the default SiteTree::Content for immediate use in themes and templates when installed
+     *
+     * @return DBHTMLText
+     */
+    public function getContent()
+    {
+        return $this->owner->ElementalArea();
+    }
 }

```

We could also add a config flag to prevent this behaviour if users didn't want it.

How do we feel about this?

**Comment by sminnee** [comment]
`getContent()` will also override the WYSIWYG editor. We'd want to override `Content()`, which only applies itself to templates.

If that doesn't work for some reason, I would suggest creating a new extension-point in hook rather than using getContent()

**Comment by robbieaverill** [comment]
>getContent() will also override the WYSIWYG editor. We'd want to override Content(), which only applies itself to templates.

Elemental replaces the Page's Content field by default anyway

**Comment by pitchandtone** [comment]
Yes but I don’t think it should anymore. It should create a $SearchContent field with rendered content, but not overwrite $Content as it will screw over sites that migrate to Elemental.

**Comment by sminnee** [comment]
In addition, it could have a migration script (e.g. requireDefaultRecords) that will detect `Content` present and replace it with a single WyswiygContentElement or something.

**Comment by robbieaverill** [comment]
Looks like this is a bad idea!
