### ISSUE TITLE
Incorrect toast message on publish inline-editable elemental block 

### ISSUE THREAD

**Issue by sabina-talipova** [dnadesign/silverstripe-elemental#1166]
## Description
If a block has a title and this title has been changed, but these changes have not yet been saved and the element is published, then the toast message contains the previous (unchanged) title.

<img width="1790" alt="Screenshot 2024-04-12 at 10 32 45 AM" src="https://github.com/silverstripe/silverstripe-elemental/assets/87288324/303efc94-8620-40ea-a73b-bd507e57909e">

**Comment by emteknetnz** [comment]
This has possibly been fixed in 5.3 with all the work done on elemental, so validate it's still an issue before fixing

**Comment by emteknetnz** [comment]
Tested in 5.3, no longer an issue
