### ISSUE TITLE
Update TopPage classnames

### ISSUE THREAD

**Issue by emteknetnz** [dnadesign/silverstripe-elemental#1240]
The TopPage feature uses a non-standard directory and class name structure. This should be changed to adopt the standard Silverstripe naming conventions

## Acceptance criteria
- [ ] The TopPage feature classes adopt the standard Silverstripe naming convention in CMS 6
- [ ] In CMS 5 old class names are deprecated and wrapping in withNoReplacement. The message should be "Will be replaced with <new-class-name>"
- [ ] Any documentation referring to TopPage is updated

## Kitchen sink CI
- https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/10692918428

## CMS 5 PRs
- https://github.com/silverstripe/silverstripe-elemental/pull/1251
- https://github.com/silverstripe/developer-docs/pull/578

## CMS 6 PRs - Ensure CMS 5 PR's are merged, merged-up and rebased first
- https://github.com/silverstripe/silverstripe-elemental/pull/1249
- https://github.com/silverstripe/silverstripe-linkfield/pull/327
- https://github.com/silverstripe/developer-docs/pull/575

**Comment by GuySartorelli** [comment]
CMS 5 PRs merged. Reassigning to Steve for CMS 6 PRs

**Comment by GuySartorelli** [comment]
PRs merged
