### ISSUE TITLE
Missing .upgrade.yml

### ISSUE THREAD

**Issue by silbinarywolf** [dnadesign/silverstripe-elemental#125]
When upgrading an existing project from 3.X to 4.X, this file is meant to help map old class names to new class names.

Looks like this doesn't exist currently for the core module and the additional modules here:
https://github.com/dnadesign/silverstripe-elemental-list
https://github.com/dnadesign/silverstripe-elemental-userforms

**Comment by robbieaverill** [comment]
Thanks. We can add one to each repo, will need to split it up between them

**Comment by robbieaverill** [comment]
Thanks @raissanorth!
