### ISSUE TITLE
Elemental area stop rendering after save/publish clicked

### ISSUE THREAD

**Issue by satrun77** [dnadesign/silverstripe-elemental#1293]
### Module version(s) affected

5.3.3

### Description
 
When a content author is too fast to click the save or publish button before the elemental areas are completely rendered, the buttons get stuck in the loading animation and the elemental area fields don't render. 

Related issue: https://github.com/silverstripe/silverstripe-admin/issues/1871
The PR https://github.com/silverstripe/silverstripe-elemental/pull/1294 seems to resolve the issue in `silverstripe-admin`

### How to reproduce

1. Install fresh CMS
2. Add Elemental module
4. Create a data object with version and more than one elemental area
```php
use DNADesign\Elemental\Extensions\ElementalPageExtension;
use DNADesign\Elemental\Models\ElementalArea;
use SilverStripe\ORM\DataObject;
use SilverStripe\Versioned\Versioned;

class SomeObject extends DataObject
{
    private static string $table_name = 'SomeObject';

    private static array $db = [
        'Title' => 'Text',
    ];

    private static array $has_one = [
        'BlockArea' => ElementalArea::class,
        'BlockArea2' => ElementalArea::class,
    ];

    private static array $extensions = [
        Versioned::class,
        ElementalPageExtension::class,
    ];
}
```
6. Create a model admin for the data object.
```php
use SilverStripe\Admin\ModelAdmin;

class SomeAdmin extends ModelAdmin
{
    private static string $url_segment = 'objects';

    private static string $menu_title = 'Objects';

    private static array $managed_models = [
        SomeObject::class,
    ];
}
```
8. Open browser console > Network tab
9. You will see multiple requests for `/admin/graphql` for each elemental area
<img width="353" alt="Screenshot 2024-12-11 at 1 50 16 PM" src="https://github.com/user-attachments/assets/917a9b76-16e6-4b24-bb5b-1be7c836f8f6">

10. Click publish just before all of the requests are completed, and you will see the pending ones changed to `cancelled`. The requests may load fast, which makes it hard to replicate. I edited the controller `SilverStripe\GraphQL\Controller`, and added `sleep(1);` to `index` method to slow down the request.
<img width="785" alt="Screenshot 2024-12-11 at 1 50 55 PM" src="https://github.com/user-attachments/assets/876419c3-0fe7-4a70-9b3d-645b72cd12d3">

11. The buttons keep on animating and you can't click it again. 
12. Elemental areas are not rendered in the CMS
13. The console display errors related to accessing `map` on null
<img width="540" alt="Screenshot 2024-12-13 at 10 45 33 AM" src="https://github.com/user-attachments/assets/9ff2e52f-92da-4af5-a11a-3e66d9dce993" />

### Possible Solution

https://github.com/silverstripe/silverstripe-elemental/pull/1294

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-elemental/pull/1294

**Comment by GuySartorelli** [comment]
IS this actually distinct from https://github.com/silverstripe/silverstripe-admin/issues/1871? Or are these two actually the same bug just described in different ways?

**Comment by satrun77** [comment]
> IS this actually distinct from [silverstripe/silverstripe-admin#1871](https://github.com/silverstripe/silverstripe-admin/issues/1871)? Or are these two actually the same bug just described in different ways?

Not sure 😅 

The PR for this issue is to ensure the code does not call the method `map` on `null`. This does seem to "resolve" the issue in the admin dependency! I feel this change might not be the correct fix for the issue [silverstripe/silverstripe-admin#1871](https://github.com/silverstripe/silverstripe-admin/issues/1871) but I could be wrong!

**Comment by GuySartorelli** [comment]
Okay. Sounds like this issue is specifically about the elemental areas not loading fully after the publish button is pushed (basically a "workaround" issue) whereas the other issue is about the fact that the buttons shouldn't be pushable _at all_ until the page form is fully ready to be submitted.

As I mentioned on the other issue I don't know if there's a sensible way to fix that with the current architecture - so this issue does seem worth fixing in its own right.

**Comment by GuySartorelli** [comment]
PR merged, will be automatically tagged by GitHub Actions
