### ISSUE TITLE
Review and polish UX, ensure CSS is using core variables etc

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#141]
cc @clarkepaul

## Blockers

- [x] #137 to introduce webpack builds

## Pull requests

- [ ] #144 
- [ ] https://github.com/symbiote/silverstripe-gridfieldextensions/pull/224
- [ ] https://github.com/silverstripe/silverstripe-elemental-blocks/pull/26
- [ ] https://github.com/dnadesign/silverstripe-elemental-userforms/pull/19

**Comment by clarkepaul** [comment]
I haven't had time for any review as yet, so hopefully we can do this on the spot.

**Comment by robbieaverill** [comment]
Added pull requests to the issue description
