### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by mfendeksilverstripe** [dnadesign/silverstripe-elemental#146]
There is a typo in the README.md file and quite nasty one. See the following line:

Replace the $Content variable with $ElementArea and rely on the markup of the individual elements

$ElementArea is incorrect it should be $ElementalArea

This typo causes the frontend not to display anything, I recommend fixing this issue ASAP to prevent confusion.

**Comment by robbieaverill** [comment]
Thanks @mfendeksilverstripe - this is fixed in #143
