### ISSUE TITLE
Save and publish button never change to "Saved" and "Published"

### ISSUE THREAD

**Issue by mfendeksilverstripe** [dnadesign/silverstripe-elemental#147]
This is how the buttons look like when block is saved and published.

![screen shot 2017-11-08 at 12 31 35 pm](https://user-images.githubusercontent.com/26395487/32523625-f8fccb2e-c480-11e7-9137-eefb7520104e.png)

This is how they should look like:

![screen shot 2017-11-08 at 12 31 57 pm](https://user-images.githubusercontent.com/26395487/32523640-10906f20-c481-11e7-916c-86f8ff26ec60.png)

**Comment by robbieaverill** [comment]
cc @clarkepaul @sachajudd

**Comment by robbieaverill** [comment]
I suspect that this is a core thing

**Comment by mfendeksilverstripe** [comment]
@robbieaverill Created a pull request that deals with this issue in the source module:

https://github.com/silverstripe/silverstripe-versioned/pull/66

**Comment by robbieaverill** [comment]
Closing in favour of https://github.com/silverstripe/silverstripe-versioned/pull/67
