### ISSUE TITLE
ElementalEditor GridField isn't usable on mobile view

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#153]
![image](https://user-images.githubusercontent.com/5170590/32706258-e2f6431a-c880-11e7-860e-754af558038c.png)

Perhaps it should revert to showing the element title and a click/touch action which would go to the edit screen.

cc @clarkepaul @sachajudd @be2n

**Comment by clarkepaul** [comment]
Isn't this the same issue which was fixed for content block reports? Pretty sure @flamerohr was looking at a similar issue where you could assign which column would be presented at smaller screen sizes but not sure which repo it was in. 

To be honest, I didn't do any mobile designs but it should scale down and text truncate fairly easy with that layout. I can prioritize some design for this if someone is going to pick up the dev.

**Comment by robbieaverill** [comment]
@flamerohr do you have any input here?

@clarkepaul I'd be happy to mock up something quickly with a mostly text based approach and send to you for review if that's easier

**Comment by flamerohr** [comment]
This pull request should've made it slightly better https://github.com/silverstripe/silverstripe-admin/pull/335

I'd be keen for more generic suggestions on how to address this :) the "hide all but a few" approach is quite aggressive

**Comment by robbieaverill** [comment]
That's a nice quick win for now!

How do you feel about this @clarkepaul? Ignore the icon alignment for now.

![image](https://user-images.githubusercontent.com/5170590/32760901-4f6d93ca-c955-11e7-8707-f19b12df728f.png)

Changes: add `display: table-cell` to `.col-EditorPreview` in small viewports and `display: none` to `.grid-field__col-compact.actions-menu` in small viewports, following Chris's example above.

We could leave the actions menu there if you'd rather

**Comment by clarkepaul** [comment]
Looking good. I would eventually want the more options dropdown available as well but it isn't essential yet as you should be able to click on the item and drill down into it.
You might want to check if the block title wraps or truncates as well.
Looking promising :)

**Comment by flamerohr** [comment]
Remember to use the modeladmin namespace for the `.grid-field__col-compact.actions-menu` selector for your display none :)
Otherwise it could affect other sections unexpectedly

**Comment by robbieaverill** [comment]
PR at https://github.com/dnadesign/silverstripe-elemental/pull/172
