### ISSUE TITLE
Where are templates for custom Elements supposed to go?

### ISSUE THREAD

**Issue by muppsy007** [dnadesign/silverstripe-elemental#162]
Hi. I'm trailing the Elemental module on SS4 and followed the example in the docs precisely. As follows:

```
<?php

use DNADesign\Elemental\Models\BaseElement;

class ElementalPromoGrid extends BaseElement
{

    private static $singular_name = "Promo Grid";
    private static $plural_name = "Promo Grids";
    private static $description = "A horizontal 3x1 grid consisting of promo images";

    public function getCMSFields() {
        $fields = parent::getCMSFields();

        return $fields;
    }

    public function getType() {
        return "Promo Grid";
    }

}
```

I also made a template called ElementalPromoGrid under my theme's template directory. The issue is that after a dev/build and refresh, SS reports that the template can't be found.

> [USER WARNING] NONE OF THE FOLLOWING TEMPLATES COULD BE FOUND: ARRAY ( [0] => ELEMENTALPROMOGRID [1] => ELEMENTALPROMOGRID ) IN THEMES "ARRAY ( [0] => MYTHEME [1] => $DEFAULT ) "

I'm sure this just my misunderstanding of how it should work in SS4. But docs appear to be a bit lacking of a simple example for creating your own elements.

**Comment by robbieaverill** [comment]
Hi @muppsy007, what is your `ElementalPromoGrid` template called exactly, and can you please provide the path to the file in your code?

**Comment by muppsy007** [comment]
Hi there. Tried several places although I know the second doesn't make much sense, it  just came from a comment noted in the docs regarding PHP namespaces.

> /themes/mytheme/templates/Layout/ElementalPromoGrid.ss

And

> /themes/mytheme/templates/Includes/ElementalPromoGrid.ss

And

> /themes/mytheme/templates/DNADesign/Elemental/Models/ElementalPromoGrid.ss

**Comment by muppsy007** [comment]
After a bit of stabbing int he dark, I found that the only place that custom templates are picked up are

> /themes/mytheme/templates/ElementalPromoGrid.ss. Right in the root of the template directory. Anywhere else, and the error above occurs.

**Comment by robbieaverill** [comment]
Yeah, that's correct

**Comment by muppsy007** [comment]
Really? Was my question unclear somehow? 

To clarify, I mean the file must be sitting directly in the /themes/mytheme/templates directory. No subdirectory of /templates is searched at all.

**Comment by robbieaverill** [comment]
Sorry - yes, your templates need to match the fully qualified class name, as in if your class is namespaces then you need folders for each part of the namespace inside templates, and if not then the template must be in the root templates folder. Lookup is strict now in SS4, it won't pick templates up from anywhere like in SS3. Hope that helps.

**Comment by robbieaverill** [comment]
Please feel free to reopen this issue if you're still having problems :)
