### ISSUE TITLE
Ensure that elements are searchable via the default CMS page search form

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#163]
When searching in the site tree using the standard CMS search form, we need to ensure that elements under a page can have their content searched and returned as per normal under the page that owns them.

This would behave the same way as if the page wasn't using elemental at all.

We can possibly re-use the frontend search content PHP function `getElementsForSearch` (not sure what it's called off hand) for this.

**Comment by michalkleiner** [comment]
This will likely resolve the current inability to offer a list of anchor links created within content elements when creating a link through the standard "Add link" in the WYSIWYG editor.

**Comment by robbieaverill** [comment]
@michalkleiner yeah you're potentially right - I've logged that at #186

**Comment by robbieaverill** [comment]
Pull request for _now_ which enables this functionality is at #188 but it's not going to be performant under larger data sets, so I've logged an enhancement issue to improve this in future at #189
