### ISSUE TITLE
Add Element JSS Requirements

### ISSUE THREAD

**Issue by digitall-it** [dnadesign/silverstripe-elemental#174]
Writing an element that has a JS requirement with this code
```
<?php

class MyElement extends BaseElement {
...
    public function getCMSFields()
    {
        Requirements::javascript('mysite/javascript/myelement.js');
        $fields = parent::getCMSFields();
        ...
    }
}
```

leads to unexpected behaviour: even if myelement.js is empty, Content Blocks grid becomes unclickable.

Force reloading the page via browser solves the problem.

Affects v1.9.0 with Silverstripe CMS 3.6.3.

Attached the composer json, the element php code  in working state and the javascript in working state.

[composer.json.zip](https://github.com/dnadesign/silverstripe-elemental/files/1626703/composer.json.zip)
[ElementCallToAction.php.zip](https://github.com/dnadesign/silverstripe-elemental/files/1626706/ElementCallToAction.php.zip)
[ElementCallToAction.js.zip](https://github.com/dnadesign/silverstripe-elemental/files/1626707/ElementCallToAction.js.zip)

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
