### ISSUE TITLE
Ensure the correct icon and hint text for deleting an element

### ISSUE THREAD

**Issue by NightJar** [dnadesign/silverstripe-elemental#175]
Since #173 changed the action from unlink to delete, we should check that the icon and tool-tip text reflect this accurately.

**Comment by robbieaverill** [comment]
It's worth noting that this is using the core GridFieldDeleteAction, so any helptips would come from that. We could modify them if needed to suit the element context, but I suspect we don't need to do anything for this.

**Comment by be2n** [comment]
I've added this to our backlog but more as a check to confirm Robbie's suspicion that we won't have to address this as core GridFieldDeleteAction will provide the what is required. If this proves false I'll re-address this issue.

**Comment by robbieaverill** [comment]
![image](https://user-images.githubusercontent.com/5170590/35597521-d5d4968c-0683-11e8-8431-78ea7bb54199.png)

LGTM!
