### ISSUE TITLE
User Forms

### ISSUE THREAD

**Issue by nglasl** [dnadesign/silverstripe-elemental#176]
I'm currently encountering an SS 4 compatibility issue between these two modules (which is specifically caused by including this module). The following causes a new UDF to not display any fields, since `Content` is not rendered into the template, and `Form` is set to null.

- https://github.com/silverstripe/silverstripe-userforms/blob/master/code/Control/UserDefinedFormController.php#L108
- https://github.com/silverstripe/silverstripe-userforms/blob/master/code/UserForm.php#L109

I managed to work around the issue by including both `ElementalArea` and `Content` in the template, but this is not the recommended approach from the documentation. This issue is to raise some discussion on what may be the best solution moving forwards. Perhaps the UDF module needs to add some support for this module, or perhaps we look at having a UDF element that allows a user to place it where they'd like on the page?

**Comment by robbieaverill** [comment]
@nglasl have you installed https://github.com/dnadesign/silverstripe-elemental-userforms?

**Comment by nglasl** [comment]
Aha, didn't actually know that was a thing :)

I've just installed it, but I'm still hitting the same issue. The new element works nicely, however a UDF page type still doesn't have any fields showing (unless you start using the form element on it).

**Comment by nglasl** [comment]
Is the idea that you hide the UDF page type from the CMS? How does this work for an SS 3 migration, such that UDF page types already exist?

**Comment by robbieaverill** [comment]
You could still have a UDF page without elements in it, or maybe even have a UDF page with elements but exclude the UserForms element from that page type ([userformception](https://github.com/dnadesign/silverstripe-elemental-userforms/issues/10)). I think it's up to how you want to implement it.

**Comment by nglasl** [comment]
Okay, from reading that issue (and just to make sure I'm understanding this correctly), the recommended solution is to apply the Elemental extension to a subclass of page, rather than to page directly? This feels like a moving target to me since you're likely to introduce new page types over time (and third party modules are going to extend from page rather than your subclass). So over time, you'll likely end up with some pages having elements and others not (which leads to confusion from a content author perspective). It feels to me as though a UDF page needs to prevent a form element from being used, and that either `$Content` or `$Form` is used to show the UDF page form. Keen to hear your thoughts on this.

**Comment by robbieaverill** [comment]
Noting that I need to come back to this properly. We need to find a standardised approach for SilverStripe Ltd as well.

**Comment by robbieaverill** [comment]
cc @be2n @clarkepaul

How would you expect CWP users to handle content blocks in CWP 2.0? Would it be that all pages have them by default and you opt out of it on a per-page basis (e.g. for a user forms page), or would it be that we have a specific page type for content blocks and all other pages don't have them?

**Comment by be2n** [comment]
An opt-in approach for 2.0 is preferable with content blocks provided as a page type that is selectable. Once there is further content block functionality - e.g. inline editing, reversion controls, a/b testing - and the community has had a chance to adopt, play with and extend content blocks, then I would forsee content blocks becoming the default page type which is then opted out of when necessary.

cc @robbieaverill

**Comment by lerni** [comment]
UX-wise it's hard to explain, why there is the old and new way of creating content and developers have to maintain Page & ElementalPage, which makes little sense since you can achieve the same with ElementalPage as with Page. For example users ask, why are BlogPosts not build with Blocks/Elements? In the CMS one click more is needed to navigate, but it's less confusing to create & edit, since all Pages with "Content" are maintained the same way. If Elemental is installed, I would prefer if it's easily possible to use it as the default way to create content.

**Comment by pitchandtone** [comment]
Why don’t you disable Page from being able to be created and use block page (or whatever you name it) as the default option?

Interesting point about blog etc though. You could probably create a new module that uses both modules as dependancies and makes this happen.

**Comment by robbieaverill** [comment]
cc @clarkepaul @sachajudd

**Comment by nglasl** [comment]
@pitchandtone, the problem I foresee is that a third party module will extend from `Page` and not `BlockPage` (the UDF module for example). So perhaps you want to add a new module to your project which introduces a new page type. Now you have a scenario where content pages across your site use elements, and this new page type which doesn't. Yes, elements can be enabled for this new page type, but this requires the developer to actually enforce this (rather than it just happening). Considering this may lead to a lack of consistency (some pages having elements and others not), I personally see it being confusing to a content author. That's all I was trying to say above :)

**Comment by lerni** [comment]
@pitchandtone - you convinced me - preventing normal pages from being created and having "ElementalPage" as default Page-Type helps. You still have to maintain multiple elemental-yml-config blocks for each class that extends Page but doable and probable more flexible rather than having Elemental on VirtualPage, RedirectorPage ect. An example config-snipet how to have "ElementalPage" as the default Page-Type and not allowing Page to be created in README would make guys like me come faster to the conclusion, that it's more flexible if you don't extend Page. But if Elemental would play nice with Page and from Page exteded classes it would allow to use the elemental-way as consistent editing method also for Errorpages ect. In the long run I still would like to use it that way.

**Comment by clarkepaul** [comment]
I had the feeling it wouldn't be right forcing users/devs to use the CWP supported block module as its still in its infant stages of development (might not fill users with confidence). Although having two different ways to set things up might be annoying, developers are best placed to make a decision on which option suits. If using elemental is going to work for your particular site then removing the old page type sounds like the better option.

**Comment by robbieaverill** [comment]
For this issue I'm going to add a BlocksPage to the [content blocks recipe](https://github.com/silverstripe/recipe-content-blocks/) I think, which will have the extension enabled by default

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/recipe-content-blocks/pull/3
