### ISSUE TITLE
Readonly view

### ISSUE THREAD

**Issue by chillu** [dnadesign/silverstripe-elemental#181]
# Overview

Readonly block views become important for viewing history of a page with all of its blocks. Currently that's not working. The SS4 page history only shows a "none" label, even with two (published) content blocks associated to that version.

![image](https://user-images.githubusercontent.com/111025/35604528-7fe862b6-06a7-11e8-8717-6fc63fcbd261.png)

# Acceptance Criteria

 * I can see all the information of the editable block overview, but as readonly fields
 * The position is displayed as an explicit readonly field
 * The view works with all core form fields in SilverStripe (excl. GridField, see https://github.com/silverstripe/silverstripe-framework/issues/3357)

# Notes

 * Designs: https://projects.invisionapp.com/share/5NEHOBLYZ#/screens/258945845_Blocks1_-_Page_History
 * Only needs to work in Entwine-based views (which can include React fields like UploadField or TreeDropdownField)
 * If there's significant work in getting form field readonly views going, split out into other cards
 * Excludes adding the link for "block history", see [listing versions of a block](https://github.com/silverstripe/silverstripe-versioned/issues/37)
* assuming 1 level deep

**Comment by robbieaverill** [comment]
It’s worth noting that block history does work, just not page history at this point

**Comment by robbieaverill** [comment]
I just tested the history for blocks on SS 4.1 and there have been some regressions. Will isolate and log an issue shortly.

**Comment by NightJar** [comment]
Just adding tests for the PR at https://github.com/dnadesign/silverstripe-elemental/pull/224

**Comment by robbieaverill** [comment]
Done in https://github.com/silverstripe/silverstripe-admin/pull/511 and #224
