### ISSUE TITLE
Error on child pages when on draft mode and try to publish them back

### ISSUE THREAD

**Issue by diegopego86** [dnadesign/silverstripe-elemental#198]
I've tested this on a clean version of SS4.0.3

To replicate do the following:

- Create a child page under Home. 
- Save and Publish the page
- Add a Content Element and Save and Publish the changes.
- Then Unpublish the Child page you just created.
- The click on the Home page.
- The go back to the Child Page that is in Draft mode and try to Save and Publish it again.

Here is an example of my sitetree:

<img width="193" alt="screen shot 2018-03-02 at 4 16 11 pm" src="https://user-images.githubusercontent.com/1388364/36884423-13abd542-1e35-11e8-8ca2-d9059a592603.png">

I'm not able to publish Test2.

I found that the issue is on DNADesign\Elemental\Extensions\ElementalAreasExtension in onBeforeWrite()  line 210, when is trying to rewrite the existing area, if I comment out that line, everything works fine.

`//$area->write();`

I believe that the line is not necessary as in the ElementalPageExtension there is a $owns set up that should write the ElementalArea on save. Can anyone confirm this?

This is the error I see, is it too long to post here:

<img width="1150" alt="screen shot 2018-03-02 at 4 15 06 pm" src="https://user-images.githubusercontent.com/1388364/36884399-eba2f620-1e34-11e8-9de8-b547393b111b.png">

**Comment by robbieaverill** [comment]
Thanks for reporting.

Interestingly, I'm not able to unpublish the child page at all.

**Comment by robbieaverill** [comment]
@diegopego86 would you mind re-testing with the latest master branch, since #199 was merged?

**Comment by diegopego86** [comment]
All working for me now!!! thanks @robbieaverill, really appreciated it.

**Comment by robbieaverill** [comment]
Great, thanks should be directed to @cjsewell!
