### ISSUE TITLE
content for search

### ISSUE THREAD

**Issue by digitall-it** [dnadesign/silverstripe-elemental#200]
Is it possible to control how the content is returned by blocks for search? I'm in the situation where the `$Content` field doesn't contain all or any useful information on save (specially when using nested elements, like rows having columns having content). A way to get a textual representation of the block that is just used for search purposes, that supports nesting and translation.

**Comment by andrewandante** [comment]
@digitall-it which search are you referring to? If you mean in-CMS search, then #189 may be of interest to you. If you mean via the FullTextSearch module or something else along those lines, can you please detail those as well? Thanks!

**Comment by digitall-it** [comment]
I mean the full text search (frontend search). Elemental creates a text representation of each block and concatenates the text in the `$Content` variable. However, there should be a method of the block to be called to have control on how such representation is created. Otherwise, Elemental can fill the Content of inaccurate information, making the page unsearchable. The primary example is when using nested blocks: as it doesn't know how to descend trough blocks, a "Three Column" block can have an Image block, a Text block and an Icon block. How does Elemental know what is the textual representation of such Icon block? Will it know that it has to "descend" to the "Three Column" block childs to actually get their content, which is indeed the actual page content?

Is using other search systems (like Zend Lucene or Apache Solr) different? Probably the situation would be even worse, because you may be want to save data in facets (for example the Icon blocks is a phone and has a phone text associated, you may want to save it in a Phone facet while indexing). I admit I didn't read well how does Elemental work with other search systems, so I would restrict the case to the base FullTextSearch module that comes free with SilverStripe.

I propose to clarify in the documentation how to customize the way a textual representation for search purposes of block gets created.

**Comment by digitall-it** [comment]
Maybe overriding ElementalSolrIndex would be the clue.

**Comment by robbieaverill** [comment]
@digitall-it the ElementalSolrIndex is provided mostly as a guideline and basic indexer so you can get the data on your frontend indexed and available for search using Solr.

If you need anything more complex you should write your own indexer. Cheers :)
