### ISSUE TITLE
Changing page type from Elemental to non-Elemental causes onBeforeWrite error

### ISSUE THREAD

**Issue by scttw** [dnadesign/silverstripe-elemental#203]
When you extend something other than Page with Elemental (eg PageWithPanels) and you try to change from PageWithPanels to another class without Elemental (eg RedirectorPage, or Page) the onBeforeWrite function in ElementPageExtension throws an error when it tries to access $this->owner->ElementArea()

Steps to reproduce:

Make a class that extends Elemental that is not Page
Make a page of that class in the sitetree
Save
Change the page type to a non-elemental class (Page) and save.

The onBeforeWrite function the errors at line 196 of ElementPageExtension.php 

The onBeforeWrite needs to handle changes to the page class and interrogate the new class whether it supports Elemental not just $this->supportsElemental()

**Comment by robbieaverill** [comment]
Hi @scttw, can you please provide the version of SS CMS and Elemental that you're using?

**Comment by scttw** [comment]
SS 3.6.5 and Elemental 1.9.0

**Comment by robbieaverill** [comment]
Thanks

**Comment by rotassator** [comment]
PR submitted for this: https://github.com/dnadesign/silverstripe-elemental/pull/204

**Comment by robbieaverill** [comment]
Fixed with #204
