### ISSUE TITLE
QUESTION - On Page save&publish, it publishes all elements...

### ISSUE THREAD

**Issue by korthjp17** [dnadesign/silverstripe-elemental#205]
Is this Expected behavior? We are having a case where we have some blocks on a page, but have them unpublished until we get all of the content. The problem was, if we save and publish the page, then all of the blocks get published.

Just wondering if this is the expected behavior? It seems like that sort of takes away from being able to do a draft block.

**Comment by robbieaverill** [comment]
Yes, that’s expected behaviour. You can disable this by removing the $owns configuration with config :-)

**Comment by robbieaverill** [comment]
You must unset the whole array and redefine it, since the array keys are not indexed with names you can reference
