### ISSUE TITLE
 2.x-dev doesn't exist? 

### ISSUE THREAD

**Issue by sparkcom** [dnadesign/silverstripe-elemental#209]
composer  require dnadesign/silverstripe-elemental 2.x-dev

./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package dnadesign/silverstripe-elemental 2.x-dev exists as dnadesign/silverstripe-elemental[1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.x-dev, 1.4.0, 1.4.x-dev, 1.5.0, 1.5.1, 1.5.x-dev, 1.6.0, 1.6.x-dev, 1.7.0, 1.8.0, 1.9.0, 1.x-dev, 2.0.0, 2.0.0-beta1, 2.0.x-dev, dev-fix/gridfieldextensions, dev-master, 2.1.x-dev, dev-pulls/splitscreen, dev-pulls/ss4-migrate] but these are rejected by your constraint.

**Comment by robbieaverill** [comment]
Fixed with 0bbe2357573805384a2708c7f7560e1635d87c09, thanks =)
