### ISSUE TITLE
SS 3.2.1 - seg fault on page save

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#21]
Hi @wilr 

Firstly, does this module support SS 3.2.x?

I've started with a fresh install of 3.2.1 and installed the following packages:

* silverstripe/comments
* silverstripe/blog
* **dnadesign/silverstripe-elemental**

After adding this to `mysite/_config/app.yml`:

```yaml
# Elemental - enable:
Page:
  extensions:
    - ElementPageExtension
```

... and running `dev/build`, I create a couple of elements and save/publish them, then when I try to save the page I get an internal server error message. Inspecting the Apache error log I see the following:

>[Mon Feb 22 01:56:50 2016] [error] [client 192.168.99.1] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /var/www/framework/core/Config.php on line 553, referer: http://ss.local:3000/admin/pages/edit/show/9

If I increase the memory limit in `mysite/_config.php` to 512M, I start seeing segmentation faults:

>[Mon Feb 22 01:57:28 2016] [notice] child pid 5125 exit signal Segmentation fault (11)

I've only had a quick look through your code, but is it possible that either (A) this module isn't compatible with updates in 3.2.x, or (B) that there's infinite recursion somewhere?

---

FYI, if I rename `mysite/_config/app.yml` to `app.yml.bak` to remove the editor from the page, flush again and reload, I can save/publish the page again successfully.

Thanks in advance.

Robbie

**Comment by wilr** [comment]
Hi Robbie,

Yes this module supports 3.2. We've got it running on several instances of 3.2 as we've upgraded SilverStripe. Use the 1.2.0 tag rather than master as master has some issues I'm currently ironing out.

Please continue your debugging and see if you can track it down.

**Comment by robbieaverill** [comment]
Thanks @wilr - will do. Will see if xdebug has anything to contribute :)

**Comment by robbieaverill** [comment]
Hi again,

FYI using the `1.2.0` tag and the following dependency versions is working correctly:

```
heyday/silverstripe-versioneddataobjects         1.4.0
silverstripe-australia/addressable               1.1.0
silverstripe-australia/gridfieldextensions       1.3.0
silverstripe-themes/simple                       3.1.0
silverstripe/blog                                2.4.0
silverstripe/cms                                 3.2.1
silverstripe/comments                            2.0.3
silverstripe/framework                           3.2.1
silverstripe/lumberjack                          1.1.3
silverstripe/widgets                             1.2.0
undefinedoffset/sortablegridfield                0.6.0
```

Must be something fishy in between the versions, unless it's a dependency issue.

**Comment by robbieaverill** [comment]
Hi again,

I'm finding that all of my elements have HTML tags stripped when I am rendering their published content to the page now.

They all contain HTML in the database from what I can see.

Would you like me raise a separate issue for this?

**Comment by robbieaverill** [comment]
Thanks @wiir - updated to the latest tip of master and can confirm the issue is resolved.
