### ISSUE TITLE
Layout of block breaks when the preview content is too long

### ISSUE THREAD

**Issue by clarkepaul** [dnadesign/silverstripe-elemental#222]
Layout of block breaks when the content is too long, so we need to ensure the text gets truncated when there isn't enough space. We should make sure it works right down to mobile sized screens as well.

![image](https://user-images.githubusercontent.com/555033/39455146-11946b52-4d33-11e8-90ee-ae93eec44a64.png)

**Comment by NightJar** [comment]
This also affects the upcoming historic view, and it would be good to address at the same time.

**Comment by robbieaverill** [comment]
PR at #257

**Comment by robbieaverill** [comment]
Fixed in 3.0.x elemental release line
