### ISSUE TITLE
Page history should link to block DetailForm history

### ISSUE THREAD

**Issue by NightJar** [dnadesign/silverstripe-elemental#223]
### Overview
The `View block` link should in fact be `Block history`, linking directly to the history of that block, as opposed to the current behaviour requiring a user to visit the current edit form for the block, then click the history tab in the top right.

This was made as a design decision in order to work around the current lack of permanent linking for history views. Once this feature is added, the behaviour described above should be amended.

Note that the `View block` link is present in the page history view.

### ACs
- `View block` link text is updated to be clear of the destination - suggest: `Block history`
- The link directs the user to the block DetailForm history viewer
- The page history remains as the master view of history
- Block history is only accessible via the page history link

**Comment by robbieaverill** [comment]
@brynwhyman it sounds like there's a dependency on this issue. Do you want to bring that into the sprint as well? I think it's this: https://github.com/silverstripe/silverstripe-versioned-admin/issues/1

**Comment by ScopeyNZ** [comment]
I'm not sure that's correct? The end goal here is that clicking "view block" will take you to the list of versions for the given block. So it should link to the `GridFieldDetailForm` and open the History tab.

**Comment by robbieaverill** [comment]
@brynwhyman can you clarify please

**Comment by brynwhyman** [comment]
Looking to follow @ScopeyNZ's assumption here, as the AC states:
> - The link directs the user to the block DetailForm history viewer

There were discussions about bringing in https://github.com/silverstripe/silverstripe-versioned-admin/issues/1 but it was understood to not be a blocker for this work.

**Comment by robbieaverill** [comment]
Thanks for updating the ACs. It looks (on CWP 2.3) like the issue now is that the "View block" button takes you back to the page's edit form, rather than viewing the block at all. I'll see what I can do.

**Comment by robbieaverill** [comment]
Actually, I'm a little confused by the ACs now:

> `View block` link text is updated to be clear of the destination - suggest: `Block history`
> The link directs the user to the block DetailForm history viewer

Block level history has been disabled. Should we be re-enabling it for this?

> The page history remains as the master view of history
> Block history is only accessible via the page history link

This conflicts with the previous two ACs in my mind. Should we be showing block history at the page level, or for individual blocks?

If we should be showing block history at the page level only, and blocks should continue to not have a History tab of their own, then what should the "View block" button do? Should it go to the GridFieldDetailForm for the block, even if it is inline editable? Should it go back to the page (as it does at the moment) but auto-expand the block in question?

If we should be showing block history on the page level, and clicking "Block history" (amended text) takes you to a GridFieldDetailForm for that block (even though it may be inline editable), and we re-enable the "History" tab for these blocks, wouldn't that invalidate the last AC: "Block history is only accessible via the page history link"?

cc @brynwhyman

**Comment by brynwhyman** [comment]
My answers below reflect the original intention of this issue (as it was groomed)

>Block level history has been disabled. Should we be re-enabling it for this?

Yes

> If we should be showing block history on the page level, and clicking "Block history" (amended text) takes you to a GridFieldDetailForm for that block (even though it may be inline editable), and we re-enable the "History" tab for these blocks, wouldn't that invalidate the last AC: "Block history is only accessible via the page history link"?

No, that statement is incorrect. I think confusion is due to a poorly worded AC. It should be: ~Block history is only accessible via the page history link~ Block history is only accessible via the 'View block'/'Block history' link in the page history view.

**Comment by robbieaverill** [comment]
I've made all the changes (locally) that are requested, but I can't auto select the History tab. It looks like this isn't possible yet ([example](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Security/Group.php#L231-L237)). One option is to add a little JavaScript snippet to the GridFieldDetailForm for elements which finds this anchor in the URL and triggers a click on the tab for it, but it's a hacky workaround. Thoughts @silverstripe/creative-commoners? @NightJar did you do something like this a while back?

**Comment by NightJar** [comment]
I don't recall @robbieaverill sorry - it does sound sort-of familiar though :thinking: 

> workaround.

!["Do it!" - Senator Palpatine; a Star Wars reference](https://user-images.githubusercontent.com/778003/61673155-78582480-ad42-11e9-8668-199732004d08.png)

**Comment by robbieaverill** [comment]
PR at https://github.com/dnadesign/silverstripe-elemental/pull/701
