### ISSUE TITLE
Element content not indexed on save

### ISSUE THREAD

**Issue by phptek** [dnadesign/silverstripe-elemental#226]
framework + cms 4.1.0 / fulltextsearch 3.2.0 / elemental 2.x-dev / cwp-search 1.0.0-rc3 / PHP 7.1

Using the following config in my `SolrIndex` subclass, the only way that content is saved in the `ElementContent::HTML` DB field, is by first manually running the `Solr_Reindex` task. The problem is that one should also expect searches to come back with results, right after creating / saving changes in individual elemental blocks (This happens for SiteTree subclasses without issue). But this isn't working for my current project, for Elemental blocks.

The expected search strings are also (obviously) not found in Solr itself via its dedicated UI. If I re-check after running Solr_Reindex, the content appears via Solr's UI and as expected, search results appear in the UI.

Adding debugging to various points in the fulltextsearch module's logic I can see that the following are the case:

* Not called: `SearchUpdater_ObjectHandler::triggerReindex()`
* Not called: `SearchUpdateProcessor::prepareIndexes()`
* Others (Can re-check if requested)

```
class CustomSolrSearchIndex extends CwpSearchIndex
{

    /**
     * @return void
     */
    public function init()
    {
        $this->addClass(File::class, ['include_children' => false]); // No images, just "Files"
        $this->addClass(Page::class);

        $this->addFulltextField('Title', 'Text', ['boost' => '1.5']);
        $this->addFulltextField('TopContent', 'HTMLText', ['stored' => 'true', 'boost' => '1.0']);
        $this->addFulltextField('PageIntro', 'Text', ['boost' => '1.0']);
        $this->addFulltextField('Content', 'HTMLText', ['stored' => 'true', 'boost' => '2.0']);
        $this->addFulltextField('MetaTitle', 'Text', ['boost' => '1.0']);
        $this->addFulltextField('MetaKeywords', 'Text', ['boost' => '1.0']);
        $this->addFulltextField('MetaDescription', 'Text', ['boost' => '1.0']);
        $this->addFulltextField('ExtraMeta', 'HTMLText', ['boost' => '1.0']);

        // Use the getElementsForSearch() from ElementalPageExtension::getElementsForSearch()
        $this->addFulltextField('ElementsForSearch', 'HTMLText');

        $this->addFilterField('ShowInSearch');              // Should apply to all de-normalised SS models
        //$this->addFilterField('CanViewType');               // Ditto
        $this->addFilterField('ViewerGroups.ID', 'Int');    // Ditto
        // These ref field-names in solrconfig.xml. See $this->getFieldDefinitions() below
        $this->addCopyField(SiteTree::class . '_Title', 'spellcheckData');
        $this->addCopyField(SiteTree::class . '_Content', 'spellcheckData');
        $this->addCopyField(File::class . '_Title', 'spellcheckData');

        // Don't index the draft content, just live
        $this->excludeVariantState(['SearchVariantVersioned' => 'Stage']);
        $this->addAnalyzer('Title', 'filter', ['class' => 'solr.SynonymFilterFactory']);
        $this->addAnalyzer('Content', 'filter', ['class' => 'solr.SynonymFilterFactory']);
```

**Comment by robbieaverill** [comment]
Right, because you're indexing the SiteTree object rather than the BaseElement so automatic reindexing won't happen... Do you have an idea of how you might fix this?

**Comment by phptek** [comment]
I don't follow. "indexing the SiteTree object rather than the BaseElement". This shouldn't be mutually exclusive, both are required to be indexed. So what am I missing do you think?

**Comment by phptek** [comment]
nvm, turns out that `ElementalPageExtension::getElementsForSearch()` doesn't do what I thought it did. Needed to _explicity_ reference fields, exactly as per `SiteTree` et al.
