### ISSUE TITLE
ElementChildrenList is missing from v2?

### ISSUE THREAD

**Issue by elliot-sawyer** [dnadesign/silverstripe-elemental#232]
Has ElementChildrenList been intentionally removed for version 2? [It seems to have disappeared from 1.9.1 onwards.](https://github.com/dnadesign/silverstripe-elemental/blob/1.9.1/code/models/ElementChildrenList.php), or is there a workaround for its functionality?

**Comment by robbieaverill** [comment]
Yeah, moved to the elemental-list module

**Comment by elliot-sawyer** [comment]
That module doesn't seem to do the same thing?  ElementChildrenList specifies a parent page and lists out the children. Elemental-List appears to be an orderable list of blocks.

**Comment by robbieaverill** [comment]
You're after this: https://github.com/dnadesign/silverstripe-elemental-list/blob/master/src/Model/ElementList.php

**Comment by elliot-sawyer** [comment]
Thanks, I'll check that out!

**Comment by elliot-sawyer** [comment]
I've checked out the module and tried to build with it, but this isn't the same functionality. While it does allow you to embed blocks within blocks that might contain other blocks until blockception occurs, it won't replicate the original functionality. If there's a blocktype that allows me to incapsulate a single page, I can use that to build a list of those blocks, but that's not the automatic solution it used to be.  The most recently supported version for SS3 (`1.9.1`) allows you to inject a block that automatically lists out all of the child pages that exist under a particular SiteTree object. This was quite useful for doing things like tiles on landing pages, but I can't see how someone would use this new module to do that. 

I'm happy to split the work out into a separate module and support it myself if it truly is abandoned, but it seems like it got lost in the move to SS4 so I thought I'd raise it as a bug.

**Comment by robbieaverill** [comment]
I see what you’re after. We removed any opinionated blocks for the SS4 version leaving only the framework for them. If you want that block I suggest making a new module or adding it to user code :-)

**Comment by elliot-sawyer** [comment]
This one might work with some modifications, I'll start there first:  https://github.com/dynamic/silverstripe-elemental-section-navigation

**Comment by robbieaverill** [comment]
Sounds good! Feel free to update the readme in this module with new blocks repositories!

**Comment by korthjp17** [comment]
I just opened a PR to update the readme with more block modules ping #234
