### ISSUE TITLE
ElementsInUseReport will not load with larger data sets

### ISSUE THREAD

**Issue by frankmullenger** [dnadesign/silverstripe-elemental#238]
The `ElementsInUseReport` appears to loop through every BaseElement to generate this report: https://github.com/dnadesign/silverstripe-elemental/blob/2/src/Reports/ElementsInUseReport.php#L27

On a project with a large number of elements in use the report exceeds max execution time for PHP and prevents ReportAdmin from loading. 

## Pull requests

- [x] Elemental: https://github.com/dnadesign/silverstripe-elemental/pull/260
- [ ] Reports: https://github.com/silverstripe/silverstripe-reports/pull/107

**Comment by robbieaverill** [comment]
Thanks @frankmullenger - how many elements do you have in the project as a reference point?

**Comment by frankmullenger** [comment]
@robbieaverill we have ~7k records in the Element table currently, will probably end up with 10 times that amount eventually.

**Comment by robbieaverill** [comment]
Thanks, we'll benchmark 50-100,000 records when we work on this

**Comment by robbieaverill** [comment]
PRs up in description. @frankmullenger would you mind testing the elemental PR on your large project to ensure it fixes it?

**Comment by ScopeyNZ** [comment]
Fixed in #260 - Nice work Robbie!

I'll close this now and let the reports PR get merged when it's ready.
