### ISSUE TITLE
Block names not being picked up

### ISSUE THREAD

**Issue by edwardleoni** [dnadesign/silverstripe-elemental#249]
Here's the problem I'm having:
<img width="312" alt="screen shot 2018-06-27 at 8 53 05 am" src="https://user-images.githubusercontent.com/5174477/41938614-9cea59e2-79e7-11e8-9080-0e875f60c73c.png">

**Package.json**
```
"require": {
        "php": ">=5.6.0",
        "silverstripe/recipe-plugin": "^1",
        "silverstripe/recipe-cms": "1.1.1@stable",
        "silverstripe-themes/simple": "~3.2.0",
        "dnadesign/silverstripe-elemental": "2.x-dev",
        "symbiote/silverstripe-gridfieldextensions": "^3",
        "silverstripe/s3": "^0.3.0"
    },
```

And that's an example of one of the blocks:
```
<?php

use DNADesign\Elemental\Models\BaseElement;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\GridField\GridField;
use SilverStripe\Forms\GridField\GridFieldConfig_RecordEditor;

class ImageBlock extends BaseElement
{
    private static $table_name = "image_blocks";

    public $singular_name = "Image Block";

    public $plural_name = 'Image Blocks';

    public $description = 'Creates a block of images';

    private static $has_many = [
        'cb_image' => ImagePartial::class,
    ];
```

For the $singular_name

I have tried pretty much everything lol

public $singular_name = "Image Block";
private $singular_name = "Image Block";
private static $singular_name = "Image Block";

But nothing changes, can you advise? :)

**Comment by robbieaverill** [comment]
Hi @edwardleoni 

Please overload `getType()` to return `Image` in your element.

The reason we've used this instead of the singular and plural name configs is:

* That in the dropdown we want to show "Image", "File", "Banner", "Form" etc, and;
* That using singular name will show "File Block", "Image Block", "Form Element", "Content Element" etc
