### ISSUE TITLE
Make block type a tooltip

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#267]
## User Story

As a designer, I want the block type label to be removed from the block preview in the CMS and replaced with a tooltip on the block icon, so that the block can focus on previewing content to the CMS user.

## Acceptance Criteria

- [ ] Block type unique icons have with a tooltip to show the type of block.
- [ ] Block type label is removed from the block preview.
- [ ] As per wireframe: https://projects.invisionapp.com/share/ZRL4T2HQAGB#/screens/301920920 
- [ ] The icon and tooltip is keyboard accessible.

**Comment by robbieaverill** [comment]
@ScopeyNZ @raissanorth was this done as part of #275?

**Comment by ScopeyNZ** [comment]
Yes.
