### ISSUE TITLE
Display versioned state of elements in react-based page

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#276]
Ensure that the versioned state of blocks are returned to the blocks page.

This has been sub-tasked out from #272 due to the dependancies of two bugs: ~https://github.com/silverstripe/silverstripe-graphql/issues/153#issuecomment-408735721 and~ https://github.com/silverstripe/silverstripe-versioned/issues/147#issuecomment-408736435

**Comment by robbieaverill** [comment]
I've triaged this in a way that assumes the blockers have been resolved

**Comment by robbieaverill** [comment]
Yeah totally, what you've done is what we didn't do last time and why we created this ticket. The indicators were new features as far as I remember.

Done in #374 - thanks @raissanorth
