### ISSUE TITLE
Implement React based drag and drop for reordering elements in the editor

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#285]
In elemental <= 3.x the GridField sortable component is used to allow reordering elements.

In the React equivalent editor (not using GridField components) we'll need to add a React component to allow this.

### Acceptance Criteria
- [x] Styling as per one of design directions (pending decision): https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5b8c6cbfc5ffe300176d8e22
- [x] Blocks can be dragged up or down the hierarchy of the blocks on a page, both collapsed or expanded blocks can be dragged. 
- [x] On hover content blocks have a ‘drag handle’ icon that is visible for mouse operated UI’s which can be used to click and drag, as well as showing an icon on hover, there is a shadow below the block as per designs.
- [x] Dragging can be activated anywhere on the block where there isn’t another action and the block is pressed for x time (use smart defaults from drag-drop library). If dragging is in process (On “click-and-hold” or “touch-and-hold”) of a block, the drag handle and shadow beneath the block appears. 
- [x] I receive an indication from the interface as to where I can drop the block. Highlighted by an indicator line
- [ ] Re-ordered blocks will become “modified” if previously published, the block will require publishing for the effects of re-ordering to be visible on the live site.

### Options:

* https://github.com/react-dnd/react-dnd: already used in silverstripe/asset-admin
* https://github.com/atlassian/react-beautiful-dnd

The handling of the reordering could be done with a GraphQL mutation on ElementalArea, providing the list of element IDs in the desired new sort order after a drop is completed. This could be a GraphQL type like `ElementIDList`, but might be a little unstructured in terms of what GraphQL expects.

Another option might be to put the mutation directly into the element that is dragged and dropped, providing a mutation signature like this:

```graphql
mutation updateElementSortOrder($id:ID!, $before:ID, $after:ID) {
  setElementSortOrder(Input: {
    ID: $id
    MoveAfter: $after
    MoveBefore: $before
  }) {
    ID
  }
}
```

In this case the element would need to set its sort order to +1 or -1 of the MoveAfter/MoveBefore element, then set new sort orders for all elements in the list to respect the updates.

Just possible ideas at this stage.

**Comment by brynwhyman** [comment]
@newleeland can you please confirm this is the correct wireframe? There's a similar DnD wireframe not included here

**Comment by brynwhyman** [comment]
Refer to asset-admin DnD styling for this

**Comment by clarkepaul** [comment]
Updated designs with the two different approaches for consideration in top comment. Link to enlarge the preview is below the design.

**Comment by ScopeyNZ** [comment]
I've almost finished this. I need some feedback for UX though (cc @clarkepaul @newleeland). 

I've implemented the designs on the right hand side, including a little blue bar for the intended drop location. The problem is that we can't have the dot appear outside of the container (like the designs). Would you like to update the design for that?

I can't allow dragging and dropping of elements that have the form visible. It's a bunch of extra work and there's no easy way to maintain form state when moving the block (ie. all your content will be reset after dragging). How should this look? My plan is if the block is expanded and the in-line form is visible then the drag handle will never appear. You would still be able to drag around blocks that haven't been expanded though. Maybe we should chat about this, it's a little complicated.

**Comment by clarkepaul** [comment]
Great I've had @newleeland look into updating the designs a few days ago, so I'll see where thats at. Yeah I think we need to chat about the dragging as thats a bit of a sticky topic.

**Comment by ScopeyNZ** [comment]
Ok I have raised a PR on admin that fixes dragging around forms:

silverstripe/silverstripe-admin#654

There are still a few issues with the feature which lives here: https://github.com/creative-commoners/silverstripe-elemental/tree/pulls/4/dnd-brb-implementing-dnd :

- Dragging a form with TinyMCE in it still doesn't work. The block moves correctly and the form still works but the `isDragging` prop seems to not be reset. Something weird is going on with TinyMCE and ReactDND.
- Dragging outside of the elemental area is not very UX friendly:
  - Dragging outside of the area cancels the drag - this is okay but the area isn't really big enough (especially at the top)
  - Dragging outside of the area still indicates that it can be dropped with a little blue bar indicator. This should really not show
- Nice to have: The blue bar really shouldn't show if the element will be dropped in its existing location.

**Comment by brynwhyman** [comment]
Ensure Aria label is hidden for DnD as it won't be possible for accessibility users

**Comment by chillu** [comment]
@clarkepaul Did you realise there would be a server call before a block can be added? Even on a vanilla website demo there's around a second delay, without any loading indication. I would suggest that you create a "shadow block" in the correct position, add a loading indicator there, and then replace it with the actual block once it's loaded. The status quo is particularly confusing because there's no other indication on what block is "new" (fading highlight etc), so if you have a few similar looking blocks you have to really pay attention to notice the changes.

**Comment by brynwhyman** [comment]
@chillu
>I would suggest that you create a "shadow block" in the correct position
I've raised #454 to track this.

**Comment by ScopeyNZ** [comment]
> @clarkepaul Did you realise there would be a server call before a block can be added? Even on a vanilla website demo there's around a second delay, without any loading indication. I would suggest that you create a "shadow block" in the correct position, add a loading indicator there, and then replace it with the actual block once it's loaded. The status quo is particularly confusing because there's no other indication on what block is "new" (fading highlight etc), so if you have a few similar looking blocks you have to really pay attention to notice the changes.

Is this for adding? Sorting optimistically updates meaning the feedback is instant.

**Comment by chillu** [comment]
> Is this for adding? Sorting optimistically updates meaning the feedback is instant.

In the demo just before it didn't appear instantaneous to me, there was a >500ms lag that I don't think would be attributed to the video conference connection. If it's adding the block before the server requrest finishes, then there's no need for a loading indicator.

**Comment by ScopeyNZ** [comment]
Ok - Adding in-line has that delay. I'm not sure that drag and drop was actually demo-ed - I missed the first 10 minutes of the demo. The drag and drop PR has no delay while re-ordering. Anyway - I have some ideas for this "add" delay which I noted in the other issue that @brynwhyman has raised.
