### ISSUE TITLE
Add block to page via pop-up 

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#293]
### User Story

As a CMS user, I want a way to select a block from a selection of blocks which have been made available to me and add it within a page, so that I can build a page with different block types easily. 

### Acceptance Criteria

- [ ] There is a button to add new blocks to the current page, styling as per wireframe: https://projects.invisionapp.com/share/ZRL4T2HQAGB#/screens/301920917
- [ ] When the ‘Add block’ button is clicked a pop-up presents all blocks available in a format that’s easy to view (NOTE this could be done multiple ways). Wireframe for reference: https://projects.invisionapp.com/share/BQMQXJGT73W#/screens/307488193_Adding_Blocks-_Buttons
- [ ] Clicking a new block type adds the block to the top of the list. Styling animation pushes current page blocks below new block

**Comment by newleeland** [comment]
~https://projects.invisionapp.com/share/ZRL4T2HQAGB#/screens/301920919~ is no longer upto date design:
- Button style is now green (https://projects.invisionapp.com/share/ZRL4T2HQAGB#/screens/301920917)

**Comment by brynwhyman** [comment]
^ Updated the ACs with the new wireframe

**Comment by ScopeyNZ** [comment]
Hey @newleeland .

I notice the designs you linked: 

> Button style is now green (projects.invisionapp.com/share/ZRL4T2HQAGB#/screens/301920917)

They have a "clear" control on the search widget. The DSM seems to have an "x" control instead:

![image](https://user-images.githubusercontent.com/3260989/44378389-2bc60100-a555-11e8-90fc-8f7d236a93c9.png)

Which one is the most up to date?

**Comment by ScopeyNZ** [comment]
I have split the task into some separate issues:

Add an "Add Block" popover: #338 
Show this popover when pressing the buttons: #339
Make this popover do something: #340
Implement the search functionality: #341

Please continue discussion in the relevant issue.
