### ISSUE TITLE
Add block to page (inline)

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#294]
### User Story

As a CMS user, I want to be able to add new content blocks within a page level between current content blocks, so that I can do this quickly and in context with the other page blocks.

### Acceptance Criteria

- [x] Hover-over between current page blocks presents styling as per wireframe: https://projects.invisionapp.com/share/ZRL4T2HQAGB#/screens/301918525
- [x] Clicking a “+” button in between blocks presents a pop-up with all blocks available in a format that’s easy to view
- [x] Clicking a new block type adds the block to the present gap between blocks. Styling animation pushes current page blocks below new block as per wireframe: https://projects.invisionapp.com/share/ZRL4T2HQAGB#/screens/301918523 
- [x] As per designs, when hovering between blocks there is a indicator that a block can be added between/above/below existing blocks (delayed interaction so the line isn’t triggered as you move the cursor across the screen).  https://invis.io/BYMQXG07QZH#/307488192_Adding_Blocks-_In-Page

### Notes
- Pop-up work is also covered in: https://github.com/dnadesign/silverstripe-elemental/issues/293

**Comment by NightJar** [comment]
Done https://github.com/dnadesign/silverstripe-elemental/pull/443
in tandem with #340
