### ISSUE TITLE
Add "more actions" item to save block individually

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#296]
Subtask from https://github.com/dnadesign/silverstripe-elemental/issues/290

A/Cs

- [x] "Save" option is in more actions menu
- [x] ~~Use the existing `FormBuilderLoader` REST API to save~~ turns out this isn't a relevant A/C
- [x] Apollo cache updates to update the state of the Element (ideally) or fallback to allowing the "read all blocks" query to re-run and reload all blocks
- [x] Blocks can still be saved after they've been edited and then collapsed.
- [x] Edit form remains open when the save action is triggered

## Requirements

- [x] [Inline editing](https://github.com/dnadesign/silverstripe-elemental/issues/327)
- [x] [Namespaced field names](https://github.com/dnadesign/silverstripe-elemental/issues/381)
- [x] [Move actions menu items into their own components](https://github.com/dnadesign/silverstripe-elemental/issues/384)

## Design references
https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5b8f33ec15093c001068254a

**Comment by robbieaverill** [comment]
Ok I've made a start on this. Here's what I've implemented so far:

* Form schema data for the frontend to construct a backend XHR request
* A bit of JS to serialise the element's form fields
* A backend controller method to save the data and return a response

Todo:

* CSRF protection
* Make the client do something after the save has been performed (update apollo store?)
* Probably move all of the "more actions" items into their own components, as well as the menu itself. There's too much logic now for them to still belong to the Header component
* Don't render the save button on the frontend if the user doesn't have canEdit permission (@NightJar, did you do something similar for rendering the form itself?) (Do we still show it but make it disabled? halp @clarkepaul)
* Don't render the save button until the inline edit form has been loaded (again, do we still show it but have it disabled?) Firing a save request before the form is available won't do anything since there won't be any form to get data from and the controller will ignore it.
* Automated testing etc.
* If anyone tests this you'll quickly notice that each of the Title fields is inheriting some of the page's Title field javascript e.g. you get an "Update URL" button added to the end of the title field when you change it - we'll need to add some kind of namespacing to the fields (also noted in #367 for saving all element data in the page)

WIP branch: https://github.com/creative-commoners/silverstripe-elemental/tree/pulls/4.0/li-save-ne based on @NightJar's WIP inline edit form PR)

This also introduces a dependency on asset-admin since we need to use the Backend.js library. This should really live in admin, but..

Would be cool to get some feedback on the approach @NightJar @ScopeyNZ @raissanorth

**Comment by clarkepaul** [comment]
@robbieaverill if you don't have edit permissions you shouldn't see the forms in an editable state, and therefor don't need to see the save button (as far as I'm aware), is there any need for a cross state where fields are in an editable state but can't save?

**Comment by ScopeyNZ** [comment]
Looks good from my quick glance over the code.

> Turns out this isn't a valid A/C - there's nothing in FormBuilderLoader for saving, it's all custom code.

Okay - I must've lost track when looking through asset-admin for example implementation.

**Comment by robbieaverill** [comment]
> @clarkepaul is there any need for a cross state where fields are in an editable state but can't save?

No I don't think so

**Comment by robbieaverill** [comment]
I'm guessing the saving the inline form should return the user back to the summary preview when the save was successful cc @clarkepaul

**Comment by clarkepaul** [comment]
> I'm guessing the saving the inline form should return the user back to the summary preview when the save was successful

No, the block should remain open. Its often that people will edit content and save several times before moving on.

**Comment by robbieaverill** [comment]
Cool, thank you!

**Comment by brynwhyman** [comment]
We create another issue for optimistic enhancement
