### ISSUE TITLE
Implement delete button

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#305]
The existing elemental editor (PHP GridField) has a delete button for quickly removing blocks.

The new React version needs this too. This will need to be written as a GraphQL mutation applied via an HOC.

## Acceptance criteria

- [x] Delete button shows on elements
- [x] Clicking the delete button removes the row
- [x] The element does not appear in the list on reload

## Pull requests

- [x] https://github.com/dnadesign/silverstripe-elemental/pull/314

**Comment by robbieaverill** [comment]
PR at https://github.com/dnadesign/silverstripe-elemental/pull/314
