### ISSUE TITLE
Alter spacing on elemental editor

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#306]
Currently the designs indicate some more compact padding for blocks (see below). The styling needs to be updated to more accurately follow the designs

Current: 
![image](https://user-images.githubusercontent.com/3260989/44006556-71f380de-9eda-11e8-992e-8c7bbd3dab55.png)

Designs: 
![image](https://user-images.githubusercontent.com/3260989/44006560-8e00efb4-9eda-11e8-9725-536a1ef08677.png)

Style guide:
![image](https://user-images.githubusercontent.com/3260989/44006587-0771a0aa-9edb-11e8-990b-c0a81ae03103.png)

**Comment by ScopeyNZ** [comment]
+1 I've update the issue to just include images.

**Comment by newleeland** [comment]
# Updated style guide
https://invis.io/EBNLPGJY76G

# Complete blocks style guide
Blocks: https://invis.io/T7NLP7WP3K4
Layout blocks: https://invis.io/BNNLP87VQJU

**Comment by ScopeyNZ** [comment]
Closed in #315
