### ISSUE TITLE
Implement loading indicator while blocks load

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#309]
With the new react editor the blocks now load asynchronously. While they load we need a loading indicator.

## Pull requests

 - [x] https://github.com/dnadesign/silverstripe-elemental/pull/316

**Comment by robbieaverill** [comment]
FYI the admin module has a Loading component that can be rendered while the `loading` prop is true (GraphQL HOCs update this prop as necessary on the components that they are bound to).

Should be an easy fix.

**Comment by brynwhyman** [comment]
@clarkepaul can you please check there is a loading indicator in the style guide or pattern library to use for this?

**Comment by clarkepaul** [comment]
Yup will sort @brynwhyman

**Comment by robbieaverill** [comment]
Loading indicator (React component in admin) from pattern library:

![image](https://user-images.githubusercontent.com/5170590/43809773-3feb5830-9b08-11e8-8893-84c9177a53e9.png)

**Comment by clarkepaul** [comment]
We use that for entire page loads but I'm not sure if its as practical for sections of UI, will confirm with Jared.

**Comment by robbieaverill** [comment]
@clarkepaul (cc @newleeland) we're already using this component for loading in sections of the UI, sometimes with multiple sections in one browser window at once. It's cool if that needs to change, perhaps we could create a new loading indicator for UI panels and mark this one as only to be used for full windows

**Comment by newleeland** [comment]
It would be good to modernize the loading indicator but I think as long as we don't have 3+ loading indicators appearing per the loading of a view it should be fine.

**Comment by robbieaverill** [comment]
In order to prevent a complex UI from having its subcomponents use the Loading component when loading async data, the component would need to share state between its child components somehow to tell them whether they're allowed to render their loading components or not.

I think this should be raised in core, and asset admin would be a good place to start (open the detail view for a file and refresh the page to see two loading indicators at the same time).

**Comment by robbieaverill** [comment]
I had a chat the other day with @newleeland about loading indicators. There are five or six varieties in the CMS at the moment, so we decided to use the Loading React component which ships in the admin module (shown in screenshot above) for now and raise a core issue (TBC) to assess and consolidate loading indicators across the CMS.

**Comment by robbieaverill** [comment]
PR at https://github.com/dnadesign/silverstripe-elemental/pull/316
