### ISSUE TITLE
Infinite Loop in ElementalArea getOwnerPage

### ISSUE THREAD

**Issue by Lolly101** [dnadesign/silverstripe-elemental#318]
![screen shot 2018-08-14 at 11 48 43 am](https://user-images.githubusercontent.com/42361058/44064229-1f0865ae-9fb8-11e8-9b60-825fe9622f2c.png)

When I save a page I get an infinite loop when owner ClassName is Null. Removed write from getOwnerPager to fix.

**Comment by Lolly101** [comment]
https://github.com/dnadesign/silverstripe-elemental/pull/319

**Comment by robbieaverill** [comment]
Thanks for the contribution =)

**Comment by robbieaverill** [comment]
Hi @Lolly101, we are having trouble with this change in the master branch CI builds so I've reverted the change and made a new one at #348 - can you let me know if this still fixes your problem? Unfortunately I'm unable to replicate your issue to try it out myself
