### ISSUE TITLE
Update SchemaComponents of TitleAndDisplayed to work with FormBuilderLoader

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#320]
Currently elemental uses a custom CompositeField "`TextCheckboxGroupField`" to render the input for "TitleAndDisplayed". FormBuilderLoader uses the default React form fields to render this resulting in the inputs being shown separate from one another:

![image](https://user-images.githubusercontent.com/3260989/44065350-3e01e77c-9fbe-11e8-90ad-87bf50c81bf4.png)

This should be done by setting a custom react "schema component" for the composite field. This component can decide how to handle the child inputs.

Remember blocks might be using this composite field, so changes should apply regardless of whether it's "TitleAndDisplayed" or not.

A/Cs
- [ ] Component is used to render the two fields combined - similar to the existing GridField component
- [ ] The two fields show the existing value of the two fields
- [ ] The current automatic process of submitting a `FormBuilderLoader` form will extract the right information from the component.

**Comment by robbieaverill** [comment]
I'm pretty sure this is done now with elemental v4.0, feel free to reopen if not
