### ISSUE TITLE
Add block within layout block

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#330]
### User Story
As a CMS user, I want to be able to add new content blocks within a layout block, so that rich presentations and layouts of content blocks can be easily created.

### Acceptance Criteria
- [ ] A developer can specify if and where blocks can be placed within the template of a layout block (presented with a dashed drop area with a “add block” link to users). 
- [ ] When a block has been added to a layout block the drop area-boarder disappears
- [ ] The user is unable to add a layout block within a layout block and therefore Layout blocks are not available in the block selector when triggering it from a Layout block.
*Blocks can be added by either*:
- [ ] Clicking the area presents a popup to add new content blocks: https://projects.invisionapp.com/share/DZNJVEEYAB8#/screens
- [ ] Blocks can be dragged or added above or below existing blocks already placed within the content block: https://projects.invisionapp.com/share/5XNJW5WBMPS#/screens
- [ ] Blocks can be added via a separator: https://projects.invisionapp.com/share/U2NJVDX7H8M#/screens

**Comment by robbieaverill** [comment]
Moved to https://github.com/silverstripe/silverstripe-elemental-layoutblock/issues/8
