### ISSUE TITLE
Adding a layout block via button

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#331]
### User Story
As a CMS user, I want to be able to add a layout block at a page level, so that I can create richer content block styling.

### Acceptance Criteria
- [ ] Styling as per wireframe: https://projects.invisionapp.com/share/DBNJVRNNMXK#/screens
- [ ] Layout blocks are available in the action to add blocks to a page through a button
- [ ] Clicking a layout block type adds the block to the top of the list. Styling animation pushes current page blocks below new block

**Comment by robbieaverill** [comment]
Moved to https://github.com/silverstripe/silverstripe-elemental-layoutblock/issues/7
