### ISSUE TITLE
Adding a layout block (inline)

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#332]
### User Story
As a CMS user, I want to be able to add a layout block at a page level, so that I can insert the layout block in context of existing page blocks.

### Acceptance Criteria
- [ ] Layout blocks are available in the action to add blocks to a page, through in-line separator: https://projects.invisionapp.com/share/YDNJVRJ928F#/screens
- [ ] Clicking a layout block type adds the block to current space. Styling animation pushes current page blocks below new block

**Comment by robbieaverill** [comment]
Moved to https://github.com/silverstripe/silverstripe-elemental-layoutblock/issues/6
