### ISSUE TITLE
Layout block template

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#333]
### User Story
As a developer, I can provide a template which is attached to a layout block. 

### Acceptance Criteria
- [ ] Template structures define where content blocks can be placed by the CMS user.
- [ ] A layout block template can be developer defined so that they work with their HTML/CSS framework.
- [ ] Layout block is displayed as per the wireframe: https://invis.io/6GNJVXX8JHZ
- [ ] Layout blocks only appear on the website if there is a block contained within it which is published, otherwise the block is not visible.

**Comment by robbieaverill** [comment]
Moved to https://github.com/silverstripe/silverstripe-elemental-layoutblock/issues/5
