### ISSUE TITLE
More options for layout bock

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#335]
### User Story
As a CMS user, I want to be able to access layout block options at a page level, so that layout blocks can be maintained quickly and separately from each other.

### Acceptance Criteria
- [ ] Layout blocks have a clickable ‘more options’ icon, as per the wireframe: https://invis.io/KGNJVNJD7PT
- [ ] Clicking the icon presents a popup with the following options and endpoints:
 - Content
 - Layout builder
 - Delete

**Comment by robbieaverill** [comment]
Moved to https://github.com/silverstripe/silverstripe-elemental-layoutblock/issues/3
