### ISSUE TITLE
Notification when publishing pages with empty layout blocks

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#336]
### User story
As a CMS user, I want to be warned if I publish a page containing an empty layout block, so that they are aware that the page will not contain dead space. 

### Acceptance Criteria
- [ ] An empty layout block will be brought to the user’s attention after attempting to save or publish a page, signifying that empty layout blocks will not be shown unless there is published content within them.

**Comment by robbieaverill** [comment]
Moved to https://github.com/silverstripe/silverstripe-elemental-layoutblock/issues/2
