### ISSUE TITLE
Notification when layout block is made empty

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#337]
### User story
As a CMS user, I want to be warned if I make a previously used layout block empty, so that they are aware that the page will not contain dead space. 

### Acceptance criteria
- [ ] The user will receive a notification when the last remaining published block within a Layout block is archived, removed or unpublished, signifying that the layout block will no longer be visible as there is no published content within it.

**Comment by robbieaverill** [comment]
Moved to https://github.com/silverstripe/silverstripe-elemental-layoutblock/issues/1
