### ISSUE TITLE
Create an "Add Block" popover widget

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#338]
The designs have a popover widget that is used to select a block type when adding new blocks to an elemental area. This widget is shown when clicking the add button and also when using the control that appears between blocks ([see designs](https://user-images.githubusercontent.com/3260989/44378295-d558c280-a554-11e8-8bb4-dcb17d4dc3e2.png)).

[Designs](https://user-images.githubusercontent.com/3260989/44378609-3af97e80-a556-11e8-8c1c-bd56453f6b25.png)

### User Story

As a user, I want a way to select a block from a selection of blocks which have been made available to me and add it within a page, so that I can build a page with different block types easily.

### A/Cs

- [ ] React popover component created that can be opened at an arbitrary point on the page
- [x] Popover lists the blocks that are available to be added to a page
- [x] The correct icon is used for blocks that are available
- [ ] Block options can be tabbed through (ie. keyboard accessible)
- [ ] ~Only 8 blocks are shown, and a "Show all blocks" link is provided to show all blocks immediately~

### Related issues

(Closed) Previous issue: #293 
Show this popover when pressing the buttons: #339
Make this popover do something: #340
Implement the search functionality: #341
Show an "Add Blocks" link/control when no blocks are in an area: #351

**Comment by clarkepaul** [comment]
Can we remove the AC "Only 8 blocks are shown, and a "Show all blocks" link is provided to show all blocks immediately"? As a first cut, it would be best to just show all blocks in alphabetic order. We will advise on a max-height for the popover and blocks can just scroll within that space. There will be a downside to this (double scroll with page beneath) but makes it an easy start to getting something usable with having to do a "show all" expand area.

Sorry I can't edit the original issue.

**Comment by ScopeyNZ** [comment]
So remove the A/C and replace it with "Blocks are shown in alphabetical order and a scroll bar is used when there are many blocks"? Also, I note that the designs say "most used" but we don't have a method to determine the "most used" blocks right now - and it's not really factored into the estimation for this task - Should we separate that out? I note you're talking about blocks in alphabetical order so should we change the title ("most used")?

**Comment by raissanorth** [comment]
@newleeland confirmed that we won't show a "Most used" heading for now, but it is something that may be added in the future. For now we won't show a heading.

**Comment by raissanorth** [comment]
Could you also include in the designs 
![image](https://user-images.githubusercontent.com/14869519/44966912-0f34ba80-af92-11e8-8701-eabd8cf609fa.png)

**Comment by ScopeyNZ** [comment]
I'm pretty keen to get the work that Raissa has already done into master as this issue is blocking 4 other issues that we want to start on this week/next week. @clarkepaul are you okay with transferring the outstanding style touch-ups to a follow up issue?

**Comment by clarkepaul** [comment]
Sure yup, sounds good.
