### ISSUE TITLE
Utilise the "Add Block" popover on the add button & other controls

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#339]
Given #338 adds a popover with a list of widgets that can be added - the existing "Add" button will need to be replace to use this.

Additionally the popover needs to show when adding a block "in-line" as per [the designs](https://user-images.githubusercontent.com/3260989/44378295-d558c280-a554-11e8-8bb4-dcb17d4dc3e2.png).

### A/Cs
- [x] The "add block" popover shows when you click on the "Add" button at the top of an elemental area
- [x] After clicking this "Add" button, the popover should be the next item in the tabindex.
- [x] A small blue line with a (+) icon shows when hovering near/between blocks
- [x] Clicking on the aformentioned line will open the "add block" popover

**Comment by raissanorth** [comment]
With the latest commit of https://github.com/dnadesign/silverstripe-elemental/pull/421/commits all ACs are fulfilled. Related task, if outstanding, are captured in new tickets.
