### ISSUE TITLE
Improvement: Add "disallowed_elements" equivalent of "allowed_elements"

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#34]
Hey Will,

I'm trying to exclude some of the default elements, but it's a "must whitelist everything" or nothing scenario.

It'd be great to have a `disallowed_elements` configuration option to blacklist some of them.

(PR coming shortly).

Cheers,
Robbie

**Comment by wilr** [comment]
PR's welcome :)

**Comment by robbieaverill** [comment]
All yours @wilr

**Comment by robbieaverill** [comment]
Thanks!
