### ISSUE TITLE
Add a search functionality to the "Add Block" popover

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#341]
#338 adds an "Add Block" popover. The designs show a search area that will filter down the list of blocks as you type:

![image](https://user-images.githubusercontent.com/3260989/44379321-7d708a80-a559-11e8-8d5d-3e76e5eb2cd5.png)

Note that the designs have been updated since this ticket was created.

### A/Cs

- [ ] ~A search box shows above the list of blocks as per the designs above~
- [x] A search box shows above the list of blocks as per the updated designs, see https://projects.invisionapp.com/share/N5MVKR392DS#/screens/318343221_Add_Block
- [x] Typing in the search area immediately filters the list of blocks
- [ ] ~The "Show All Blocks" option is automatically enabled while a search query is present~
- [x] By default all available block types are shown - if no search term was entered -
- [x] Pressing enter should not submit a parent form
- [ ] ~A small (x) icon appears when there is a search term - clicking it will clear the search~
- [x] A clear link appears when there is a search term - clicking it will clear the search
- [x] After clearing the search, the previous state of "Show All Blocks" is remembered and restored.

**Comment by raissanorth** [comment]
Closed via https://github.com/dnadesign/silverstripe-elemental/pull/406
