### ISSUE TITLE
Show a message when no blocks exist

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#351]
**Version: 4.x-dev**

![image](https://user-images.githubusercontent.com/5170590/44637815-8523a980-aa07-11e8-817b-03f763d0e0aa.png)

When no blocks exist yet we should show a message to hint to a user they need to add blocks to their page. 

Refer to designs:

![image](https://user-images.githubusercontent.com/3260989/45136548-b0bd4580-b1f8-11e8-9c48-81667882ee67.png)

https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5b90499d4d45900010a7be60

**Comment by NightJar** [comment]
I feel like the default should be the inline "Add block" directive as per the designs:

![image](https://user-images.githubusercontent.com/778003/44640815-fec39380-aa17-11e8-9c1d-1f2b1359e9e1.png)

**Comment by ScopeyNZ** [comment]
Nice. Another place for that `Add Block` popover to show 🤔 

This might be blocked by #338?

**Comment by NightJar** [comment]
I've just discussed this with @clarkepaul - the "Add block" directive I posted above is actually a minor misunderstanding on my part - it's designed for the _layout block_ - not a standard Elemental Area.
To that end something similar would be cool - in essence a simple:

>There are currently no blocks. _Add block_

**Comment by clarkepaul** [comment]
Updated with design link to top comment.

**Comment by NightJar** [comment]
Sorry @clarkepaul - that interface is painful. Could you please also attach a simple screenshot of the widget in question?

**Comment by ScopeyNZ** [comment]
@NightJar I have updated the OP with an image 🙂

**Comment by clarkepaul** [comment]
There is also links at the bottom of the design which goes to a full size image, we will try to ensure the extra links are there for quick access.

**Comment by raissanorth** [comment]
Since the updated designs only contain a message and don't include a link to add new elements, this ticket is resolved.
