### ISSUE TITLE
Make action buttons on ElementEditor keyboard accessible for Safari

### ISSUE THREAD

**Issue by raissanorth** [dnadesign/silverstripe-elemental#354]
The dropdown menu and the - yet to be merged #353 - expand button of the new ElementEditor React app are not yet key board accessible on Safari 11.

When tabbing through the items, only the Elements in the list get focused, but neither the action menu components nor the button.

**Comment by raissanorth** [comment]
Closing this since I haven't had Safari set up properly. Tab access is not enabled by default - this ticked box makes all the difference:

![image](https://user-images.githubusercontent.com/14869519/45005733-339f9e00-b049-11e8-857a-3ef836463478.png)

**Comment by robbieaverill** [comment]
Good to know!
