### ISSUE TITLE
`ElementSiteTreeFilterSearch` adds a second "All Pages" to SiteTree's page status search filter

### ISSUE THREAD

**Issue by maxime-rainville** [dnadesign/silverstripe-elemental#366]
## Affected Version

I'm seeing this with the CWP kitchen 4.x and SS 4.2. Both of them running elemental 3.0.

## Description

The `Page Status` filter in the SiteTree search form has 2 "All Pages" entries. The underlying value for each entry are:
* SilverStripe\CMS\Controllers\CMSSiteTreeFilter_Search
* DNADesign\Elemental\Controllers\ElementSiteTreeFilterSearch

I would expect those 2 search filters to have distinct labels assigned to them ... assuming they do different things.

## Steps to Reproduce

1. Access the CMS.
1. Access the Page Search.
1. Interact with the "Page Status" filter.

![image](https://user-images.githubusercontent.com/1168676/44822024-af19dd80-ac4c-11e8-8e5b-d5ae8cb6457b.png)

**Comment by robbieaverill** [comment]
Reproduced with CWP 2.2.x-dev and SS 4.3.x-dev: 

![image.png](https://images.zenhubusercontent.com/58409bdab9dc3c622022d20e/55220faf-d410-4594-b07b-fe6cce8cc2b7)

**Comment by robbieaverill** [comment]
CMSMain constructs the field list with the filter class dropdown, and provides "All pages" as an empty default string - the elemental filter adds this again. I've added an extension which removes the default string and empty default value. PR at #564

**Comment by ScopeyNZ** [comment]
Closed in #564

**Comment by robbieaverill** [comment]
This has popped up again in CWP 2.3.x-dev

**Comment by robbieaverill** [comment]
I forgot to enable the extension I wrote in #564 🤦‍♂

**Comment by ScopeyNZ** [comment]
Closed
