### ISSUE TITLE
Flesh out developer docs for in-line editing

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#379]
Currently the master branch is unstable and will eventually be released in a major version. As we develop breaking changes we should document what we broke. Additionally new API and configuration have been added. We should:

- add an upgrading guide (and note what is breaking). Started: https://github.com/dnadesign/silverstripe-elemental/blob/master/docs/en/upgrading_to_4.md
- document new configuration
- update docs for block authors (including creating react components where necessary)
- be better at including this within future PRs

**Comment by NightJar** [comment]
Specifically we need to note that Inline editing is the default, and there is an opt-out approach _per block/element type_ as a config setting.

**Comment by ScopeyNZ** [comment]
Yes. Note that #378 would introduce the ability to opt out of in-line editing globally, but I'd expect that PR to include documentation updates 😉
