### ISSUE TITLE
Element editor's actions menu items should live in their own components

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#384]
We're adding more and more action menu items at the moment, so the `Header` component is filling up quickly with things that aren't directly related to a "header", but to an actions menu within it.

I think we should move each of the actions into their own components

**Comment by robbieaverill** [comment]
Perhaps they should be HOCs, since they have some content to render but also a `handleXyz` event to provide as well

**Comment by ScopeyNZ** [comment]
It'd be nice to clean up the folder structure too.

**Comment by robbieaverill** [comment]
PR at https://github.com/dnadesign/silverstripe-elemental/pull/385

I've put the actions into their own folder. I think if we want to rearrange the folder structure more, someone could make a PR to do it and we should do it sooner rather than later if so

**Comment by robbieaverill** [comment]
The bulk of this is done in #385, we can refactor or improve as we go (before 4.0 stable)
