### ISSUE TITLE
Change "readBlocksForPage" to "readBlocksForArea"

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#387]
Currently we have a GraphQL query which is `getBlocksForPage`. This is a bit awkward because blocks can be separated into multiple areas, and pages don't necessarily have elemental areas. A better solution would be to expose the actual relationship that exists - the elemental area.

We should convert our query to `getBlocksForArea`:

```gql
query ReadBlocksForArea($id:ID!) {
  readOneArea(ID: $id, Versioning: {
    Mode: DRAFT
  }){
    ID
    Elements {
      pageInfo {
        totalCount
      }
      edges {
        node {
          ID
          Title
          BlockSchema
          InlineEditable
          IsLiveVersion
          IsPublished
          Version
        }
      }
    }
  }
}
```

This also removes the awkward `ElementalAreaIfExists`.

After this, the components will need to be updated to deal with area IDs instead of page IDs.

**Comment by robbieaverill** [comment]
Note that now we also need to update the sort mutation's optimistic update

**Comment by ScopeyNZ** [comment]
This would be required for "Layout" blocks.

**Comment by robbieaverill** [comment]
Done in #522
