### ISSUE TITLE
Update styling on in-line forms

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#388]
Couple of design notes for the new in-line edit forms:

- Fields should be using the "stacked" mode. Labels should appear above inputs. This can be done by adding the `stacked` class to the `form-group` container:

Old:
![image](https://user-images.githubusercontent.com/3260989/45460745-8a952980-b753-11e8-960c-4c83e60bb853.png)

New:
![image](https://user-images.githubusercontent.com/3260989/45460732-794c1d00-b753-11e8-8853-f9b516af9365.png)

- Responsive min-width should be updated. Specifically for TinyMCE that's looking a little cramped:

![image](https://user-images.githubusercontent.com/3260989/45460809-dc3db400-b753-11e8-96aa-b609d1f73265.png)

- In-line edit form has horizontal scroll:

![image](https://user-images.githubusercontent.com/3260989/45460909-4191a500-b754-11e8-8869-c1e01588b1e0.png)

- When in edit mode with a reduced window width the TinyMCE right border is lost:
![image.png](https://images.zenhubusercontent.com/5b17319354b51e4165e1fd0b/c0054068-60c1-4996-8885-864d3401ea7b)

Add it here if there was anything I missed (cc @clarkepaul - let me know if you want to run through this together in more detail).

**Comment by clarkepaul** [comment]
Apart from making the editor area bigger we'll need to create a separate issue to organise the TinyMCE options.

**Comment by brynwhyman** [comment]
At least the above two points appears to be inherited from core styling. See here for details https://github.com/silverstripe/silverstripe-admin/issues/655

**Comment by brynwhyman** [comment]
I'm changing this to impact/medium.

**Comment by raissanorth** [comment]
It appears that the first point has already been actioned upon.

See wide screen size:

![image](https://user-images.githubusercontent.com/14869519/47541701-b6045a00-d936-11e8-858f-9b237fe844af.png)


See narrow screen size:

![image](https://user-images.githubusercontent.com/14869519/47541687-a2f18a00-d936-11e8-9377-340a21a9ea6d.png)

**Comment by raissanorth** [comment]
There are some weird semi-states as well... 🤔 

![image](https://user-images.githubusercontent.com/14869519/47541902-8dc92b00-d937-11e8-88fd-c30d8d68f04d.png)

**Comment by clarkepaul** [comment]
If this hasn't been fixed, can we make sure there is an issue to capture it (or let me know to capture it), it should nicely for smaller sizes.
![image](https://user-images.githubusercontent.com/555033/47675974-35887680-dc20-11e8-8408-184da620478d.png)

**Comment by NightJar** [comment]
Closed in #478

**Comment by brynwhyman** [comment]
>If this hasn't been fixed, can we make sure there is an issue to capture it (or let me know to capture it), it should nicely for smaller sizes.

@clarkepaul #478 resolves this too.

**Comment by brynwhyman** [comment]
>If this hasn't been fixed, can we make sure there is an issue to capture it (or let me know to capture it), it should nicely for smaller sizes.

@clarkepaul this wasn't fixed by this PR. I've raised #483 to track it.

**Comment by NightJar** [comment]
It was a run-on effect of the scrollbar and styling issues addressed in #478 and #487 respectively
