### ISSUE TITLE
BUG 3.0.0: ElementalAreasExtension should not write in updateCMSFields

### ISSUE THREAD

**Issue by chrispenny** [dnadesign/silverstripe-elemental#395]
In `ElementalAreasExtension::updateCMSFields()`:
```
if (!$area->isInDb()) {
    $area->write();

    $this->owner->{$key} = $area->ID;
    $this->owner->write();
}
```

### Why is this an issue?

In it's current state, `ElementalArea` does not follow the standard archive process when it's owner is archived. I understand that this is because we can't define the relationship in `ElementalAreasExtension`, as the purpose of that extension is for it to be flexible.

I think that with the above consideration, it is a pretty fair expectation that the dev using the module will add their own relationship map, and add the appropriate cascading/handling so that the `ElementalArea` is archived with it's `owner`.

EG:
```
/**
 * @var array
 */
private static $cascade_deletes = [
    'ElementalArea',
];
```

The problem is that you cannot implement your own archive functionality, because every time you hit that `updateCMSFields()` method, your `Area` and your `owner` will both be written back into draft.

# Update

We've noticed that the History view is triggering this write as well.

## Example

I create a Page with a bunch of Blocks:
![screen shot 2018-10-10 at 11 47 30 am](https://user-images.githubusercontent.com/505788/46703156-72e19000-cc82-11e8-9441-7794babcd5be.png)

Versioned table looks like so:
![screen shot 2018-10-10 at 11 47 09 am](https://user-images.githubusercontent.com/505788/46703165-7d038e80-cc82-11e8-9322-60b6a3b761fa.png)

I've added a quick log to the `updateCMSFields()` method:
![screen shot 2018-10-10 at 11 49 14 am](https://user-images.githubusercontent.com/505788/46703194-93a9e580-cc82-11e8-8907-1ad412b9ff18.png)

If you then browse the History Tab and find and click on any version before I added all of the Blocks:
```
[2018-10-10 11:50:16] error-log.DEBUG: /var/www/mysite/www/vendor/dnadesign/silverstripe-elemental/src/Extensions/ElementalAreasExtension.php 170: writting a new area 
 [] []
```

I go back to the "Content" tab (Blocks are now missing):
![screen shot 2018-10-10 at 11 51 22 am](https://user-images.githubusercontent.com/505788/46703257-dbc90800-cc82-11e8-8ee7-42cbe101b244.png)

Versioned table now looks like so (the Page was written with a new `ElementalArea`:
![screen shot 2018-10-10 at 11 51 59 am](https://user-images.githubusercontent.com/505788/46703288-f3a08c00-cc82-11e8-9e18-b7671129b019.png)

The old ElementalArea is still there. If I go through my DB records and change everything back to the old ID, I get all the Blocks back.

**Comment by ScopeyNZ** [comment]
Slightly related #347.

**Comment by robbieaverill** [comment]
Beat me to it

**Comment by chrispenny** [comment]
Hi team (@robbieaverill, @ScopeyNZ),

Could this one please be upgraded to `impact/high`? We've noticed that the History view is triggering this write as well.

## Example

I create a Page with a bunch of Blocks:
![screen shot 2018-10-10 at 11 47 30 am](https://user-images.githubusercontent.com/505788/46703156-72e19000-cc82-11e8-9441-7794babcd5be.png)

Versioned table looks like so:
![screen shot 2018-10-10 at 11 47 09 am](https://user-images.githubusercontent.com/505788/46703165-7d038e80-cc82-11e8-9322-60b6a3b761fa.png)

I've added a quick log to the `updateCMSFields()` method:
![screen shot 2018-10-10 at 11 49 14 am](https://user-images.githubusercontent.com/505788/46703194-93a9e580-cc82-11e8-8907-1ad412b9ff18.png)

If you then browse the History Tab and find and click on any version before I added all of the Blocks:
```
[2018-10-10 11:50:16] error-log.DEBUG: /var/www/mysite/www/vendor/dnadesign/silverstripe-elemental/src/Extensions/ElementalAreasExtension.php 170: writting a new area 
 [] []
```

I go back to the "Content" tab (Blocks are now missing):
![screen shot 2018-10-10 at 11 51 22 am](https://user-images.githubusercontent.com/505788/46703257-dbc90800-cc82-11e8-8ee7-42cbe101b244.png)

Versioned table now looks like so (the Page was written with a new `ElementalArea`:
![screen shot 2018-10-10 at 11 51 59 am](https://user-images.githubusercontent.com/505788/46703288-f3a08c00-cc82-11e8-9e18-b7671129b019.png)

The old ElementalArea is still there. If I go through my DB records and change everything back to the old ID, I get all the Blocks back.

**Comment by chrispenny** [comment]
My current understand of versioning of Blocks on a Page (right or wrong), is that the history is tied to the publishing of that Page.

This means that if you start a new Page, add a bunch of Blocks, and then click the History tab (before publishing the Page), you will immediately lose all of your Blocks - because the only version in the History tab will be the one prior to the ElementalArea having been added to the Page.

There is maybe a separate discussion needed for this, but perhaps a new version of the Page should be created when Blocks are added?

**Comment by robbieaverill** [comment]
I'll whack together a unit test to reproduce this original problem, which I understand is when a page is archived and you view it (triggering getCMSFields on the page) it writes a new ElementalArea to it

**Comment by robbieaverill** [comment]
So far unable to reproduce this with elemental 3.1.x-dev (which your project is currently running): https://gist.github.com/robbieaverill/8a14d886bdd865fb6d243b214d61400c

**Comment by robbieaverill** [comment]
Bug reproduced in a vanilla SS 4.3 environment with elemental 3.x

**Comment by robbieaverill** [comment]
I think you're totally right @chrispenny - switching to an old version of a Page in history view, perhaps one that didn't have an elemental area, then calling getCMSFields to render the history view for it causes elemental to create a new area and attach it to the page, meaning the latest version has no blocks. I'm going to write some tests then patch it and make a PR.
