### ISSUE TITLE
Have obvious visual feed back for inline actions such as save.

### ISSUE THREAD

**Issue by NightJar** [dnadesign/silverstripe-elemental#398]
Currently (4.x-dev, unreleased) when saving the little icon for the block type updates with a little red circle (draft), a red dot (unpublished changes), or has no 'sub-icon' (published).

However it is not a very intuitive indication of state alteration, and it would also be good to have some kind of more visual response to clicking the save/publish button for a single block.

E.g. Pages have toast notifications pop up when they're saved.

**Comment by ScopeyNZ** [comment]
The designs have a little thing for this:

![image](https://user-images.githubusercontent.com/3260989/45733009-06e7ab00-bc33-11e8-97a9-7929c34f0316.png)

I was playing around with something for this:

https://codesandbox.io/s/528l23pwn4

Was hoping to finalise this a little and add it to admin.

**Comment by NightJar** [comment]
I'm still unsure if something so subtle should be the _only_ indication - however it really is more of a decision for @newleeland and @clarkepaul

**Comment by clarkepaul** [comment]
I think the pattern should be fine, we can re-assess when its developed and see in action.

**Comment by brynwhyman** [comment]
Noting that we already have the following issues raised to be reviewed:
Toast message after versioning a block: #364 
Animated icon for versioning: #292 

Closing this and will ensure to include test scripts/user testing covering this with upcoming UAT.
