### ISSUE TITLE
Publish and Close, Next and Previous buttons

### ISSUE THREAD

**Issue by hpeide** [dnadesign/silverstripe-elemental#399]
It would have been a real treat to have a "Publish and Close" button. And Previous and Next element button would also enhance content productivty. As now it is alot of clicking forth and back to achive this.
It's not bad as now, but better navigation would be a great enhancement I think.

Great work with the module! :-)

**Comment by robbieaverill** [comment]
Thanks for the feedback @hpeide! Have you looked into the inline editing work that's going on in the elemental master branch at the moment? This would probably remove the need for these extra actions. You could also track https://github.com/silverstripe/silverstripe-admin/issues/436 which is a core change for the same kind of thing.
