### ISSUE TITLE
BUG v3: Archived view traverses all DataObject levels resulting in time out

### ISSUE THREAD

**Issue by chrispenny** [dnadesign/silverstripe-elemental#409]
## The issue

When viewing an Elemental Area in a "read only"/"archived" view, it (appears to) attempt to traverse the entire data structure of each Element. When you have deep structures, this processes ends up taking a very long time, and quite often results in a time out.

## Possible solutions(?)

There could be a global traversal level limit (controllable via config)?

Or, each Element could have it's own config to allow/disallow traversal of it's `has..` relationships?

Or, each Element could have a white/black list of fields to (or not to) display?

Or, other?

## Guidance for project specific solution(?)

Maybe something already exists that would allow me to make changes specifically for this project?

EG: If we're able to easily control the template used for the read-only view, then potentially we could customise this? You'll have to forgive my ignorance in this area - if we go down this path, I'd definitely appreciate some guidance on where I should be looking and what I should be doing.

# Many thanks, team :)

**Comment by robbieaverill** [comment]
I think we can have a configurable depth. We only need one level deep for OOB elemental, probably two if you're using some sort of layout blocks

**Comment by robbieaverill** [comment]
The existing code is only really looking one level deep (Root.Main fields). It's a necessity to call getCMSFields for each element though, which is a performance hit regardless of how many levels you go. We had a similar issue in elemental v4 when getting the primary tab names for a "more actions" dropdown, and solved it by pre-caching the field list's primary tabs. That sort of approach could be backported but having it still generate a FieldList might be tricky.

I have a feeling that the performance hit is coming from ElementList (which is rendered inside an ElementalArea) rendering another ElementalArea, which then runs this code again to get the first level of fields to display. I'm going to park this for a bit and have a think about it.

**Comment by robbieaverill** [comment]
I don't think there's anything more we can fix with this. In the project I was testing it on, most of the performance hit was coming from the site tree loading and dependent pages, both of which have been optimised in core. Feel free to reopen if you don't think this has been addressed correctly.
