### ISSUE TITLE
FIX Glue search bar to top of AddElementPopover when scrolling

### ISSUE THREAD

**Issue by raissanorth** [dnadesign/silverstripe-elemental#414]
Currently the search bar does not stay fixed when one scrolls to browse through more content. As discussed with @newleeland, this behaviour is desired though to make it easier on the CMS users.

See current implementation below:

![image](https://user-images.githubusercontent.com/14869519/46115648-03b07880-c24c-11e8-9dd5-278c5b06bca0.png)

![image](https://user-images.githubusercontent.com/14869519/46115672-1a56cf80-c24c-11e8-9068-2fdd29afa188.png)

**Comment by raissanorth** [comment]
Closing this since @newleeland thinks 
> dont worry about it, as fixing it would take up valuable space for viewing the different blocks

**Comment by ScopeyNZ** [comment]
> dont worry about it, as fixing it would take up valuable space for viewing the different blocks

This seems so strange. I'd expect people to scroll, get frustrated then realise they can just use the search bar. I don't think the extra real-estate when scrolling would be that much benefit? This is tagged as `effort/easy`...

cc @newleeland @clarkepaul

**Comment by robbieaverill** [comment]
Yeah +1, we should glue it to the top (in my opinion)

**Comment by clarkepaul** [comment]
It was me who really said don't worry about fixing it to the top, I was just trying to minimise effort in as many areas so it gets done, but I'm all good with fixing it too. 
Reasons why I wasn't too fused about doing it: 
- We don't offer many blocks OR people typically don't have 100s of blocks so people likely don't need a search.
- It takes space away from seeing blocks you have

Main reason for fixing:
- Looks way better, better UX specially when scrolling
- Accommodates larger sites 
- Small effort for greater return

Happy to go ahead :)

**Comment by ScopeyNZ** [comment]
This was fixed as part of the addition of this pattern into silverstripe-admin shown in [the pattern library](https://silverstripe.github.io/silverstripe-admin/?knob-Search=true&selectedKind=Admin%2FPopoverOptionSet&selectedStory=Simple%20Example&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).
