### ISSUE TITLE
ElementalEditor needs a way to respond to unauthorised CMS users

### ISSUE THREAD

**Issue by raissanorth** [dnadesign/silverstripe-elemental#415]
At the moment users that only have access to the CMS, but no privileges to view or edit content will be able to open up a page that has the Elemental extension applied. 
They are, however, _not able_ to see the list of blocks at all. Instead only the loading indicator is shown, which is unsatisfactory feedback for users.

The unauthorised CMS user sees:

![image](https://user-images.githubusercontent.com/14869519/46116350-c6e68080-c24f-11e8-957f-f2fbf687c327.png)

These are the permissions I set when encountering this:

![image](https://user-images.githubusercontent.com/14869519/46116347-c0580900-c24f-11e8-884d-b36d956e7883.png)

I am using dev-master at 06eba2e2bb9

**Comment by robbieaverill** [comment]
In the default CMS we render a readonly view. We probably need to do that as well, assuming the user can view this page in the first place (your permissions indicate that they shouldn't be allowed to get to this point at all). The "access to all CMS sections" is probably taking precedence.

**Comment by raissanorth** [comment]
@sachajudd FYI

**Comment by raissanorth** [comment]
This issue closely related to https://github.com/dnadesign/silverstripe-elemental/issues/426.

**Comment by raissanorth** [comment]
Should be resolved by dnadesign/silverstripe-elemental#449

**Comment by raissanorth** [comment]
Closed via #446 and #449
