### ISSUE TITLE
BUG Caret button to open inline-editable view of elements is not keyboard accessible.

### ISSUE THREAD

**Issue by raissanorth** [dnadesign/silverstripe-elemental#420]
Tested on IE, Edge, Chrom, Firefox and Safari. Not key board accessible on any of these browsers yet. This relates to the ElementEditor feature work on `dev-master`.

**Comment by robbieaverill** [comment]
It's not a button any more is it? I think we need to tell screen readers that they can interact with the Element itself, not the caret

**Comment by ScopeyNZ** [comment]
Yes, and I think we do indicate the element is clickable? We don't want the caret itself to be tabbable any more.

**Comment by raissanorth** [comment]
That is correct, it is not a button anymore. I missed that refactor somehow. 🤦‍♀️ 
Since the element itself is not keyboard accessible, I assumed one would be able to use the ~button~ not-button-but-looks-like-a-button-caret to expand the element.

The issue persists however that the element is not expandable via keyboard input. Whilst the element is clickable when in focus, in IE and Edge - via BrowserStack at least - this triggers a save action of the entire page instead of the expanding the block. 

I will close this issue an open up a new one for the issue described above.
