### ISSUE TITLE
Safari browser compatibility issues with inline adding of blocks

### ISSUE THREAD

**Issue by raissanorth** [dnadesign/silverstripe-elemental#422]
https://github.com/dnadesign/silverstripe-elemental/pull/421 introduces inline adding of blocks. There are a few cross-browser compatibility issues that still need to be ironed out, however:

**IE**

- [x] The transformation for the hover bar does not apply, which causes the hover bar to be rendered too high. It needs to be just within two elements.

**Edge**
- [x] The items in the popover are not aligned properly - related PR https://github.com/silverstripe/silverstripe-admin/pull/717
- [x] The plus icon, as part of the hover bar, is rendered too low. It needs to sit horizontally centered on the hover bar.

**Safari**
- [x] In some occasion's half of the hover bar's plus icon is still visible when hovering away:

![image](https://user-images.githubusercontent.com/14869519/47883201-13495f80-de91-11e8-9222-3a6c82d5c49a.png)

![image](https://user-images.githubusercontent.com/14869519/47883206-17757d00-de91-11e8-868e-7cb387fc611c.png)

Note that the above issues relate to the ongoing feature development of the ElementalEditor on `dev-master`. This issue is raised mainly to log outstanding work.

**Comment by NightJar** [comment]
I addressed half of this in #433

**Comment by ScopeyNZ** [comment]
Whoops! Still a couple of changes to make here.

**Comment by robbieaverill** [comment]
Still going on this @ScopeyNZ?

**Comment by ScopeyNZ** [comment]
I wasn't actively working on this I was just noting that an issue was still remaining. It's incredibly low impact though

**Comment by brynwhyman** [comment]
I cannot recreate the Safari issue on the last version of Safari `12.0.3` and `silverstripe/recipe-content-blocks: ^2.1` which includes `dnadesign/silverstripe-elemental: 4.0.0@stable`

**Comment by Cheddam** [comment]
I _was_ able to reproduce this (by moving my cursor to the preview pane instead of another block), but it seems to be a bug in the rendering engine, and doesn't seem worthwhile attempting to hack around.
