### ISSUE TITLE
Remove block history option from in-line edit view

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#424]
Due to the complexities of building a React history viewer within the block (#59) we should, for now:

- [x] remove the history option form the block's options dropdown; and
- [x] hide the history form from being visible as an in-line tab.

The user will still be able to view the history of the block via the page history form but we intend to also action #425  which will re-add the history dropdown option to link the user to the block history in the GridFieldDetailForm

**Comment by raissanorth** [comment]
Closed via dnadesign/silverstripe-elemental#436
