### ISSUE TITLE
User permissions to edit content blocks

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#426]
Running `dnadesign/silverstripe-elemental dev-master 674a160a79`

#415 has been raised to handle graphql errors such as where the user is not permitted to view or edit a page, but while testing it seems there is a bug with edit permissions.

When a user has full 'Content permissions', and they are viewing a blocks page with existing blocks within the CMS, they are only presented with a loading indicator when the **should** be presented with the list of blocks for editing:
![image](https://user-images.githubusercontent.com/15868440/46323840-b158c880-c64c-11e8-8278-495b7f430be1.png)

Permissions:
![image](https://user-images.githubusercontent.com/15868440/46323793-8c645580-c64c-11e8-9d90-57df43574269.png)

**Comment by raissanorth** [comment]
@sachajudd This might be of interest to you.
