### ISSUE TITLE
Update to node 8

### ISSUE THREAD

**Issue by torleif** [dnadesign/silverstripe-elemental#430]
node 6 maintenance ends in April 2019. 

From what I can tell this might be a bit of a challenge, as silverstripe/webpack-config seems to have issues with the eslint module and proptypes in the latest version of react.

**Comment by ScopeyNZ** [comment]
Yeah this will be a challenge. Also we rely heavily on external dependencies provided by `silverstripe/admin` so we'd probably wait for that to be updated first.

**Comment by robbieaverill** [comment]
Yeah this needs to be raised on the silverstripe admin module first. Would you mind reopening an issue there @torleif?
