### ISSUE TITLE
Write tests for ElementTabProvider

### ISSUE THREAD

**Issue by NightJar** [dnadesign/silverstripe-elemental#431]
There are currently no tests for [`DNADesign\Elemental\Services\ElementTabProvider`](https://github.com/dnadesign/silverstripe-elemental/blob/469a7e154172a43f8dfc533d097a2d3c4badc358/src/Services/ElementTabProvider.php). Although #429 will add some incomplete tests, these should be fleshed out in order to avoid future regressions as work progresses.

**Comment by robbieaverill** [comment]
If anyone wants to do this, feel free - we don't need to track it though
