### ISSUE TITLE
Options menu doesn't expand block in correct tab

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#453]
When inline editing is enabled for a block on `master` and the block is collapsed, when selecting a tab option in the options menu, the block will always expand on the content tab regardless of the selection. It should expand on the tab that was selected.

Reproduce:
- Select 'Settings' from the options menu on a collapsed block
- Notice that the block expands to the content tab, not the settings tab

**Comment by brynwhyman** [comment]
Maybe related: https://github.com/silverstripe/silverstripe-admin/pull/641

**Comment by robbieaverill** [comment]
I merged a bunch of PRs from @raissanorth today, then re-tested and this is working now. Please feel free to reopen again @brynwhyman if you experience it again with the latest master branch of elemental. You'll need to update your other dependencies as well (`composer update`).
