### ISSUE TITLE
Add placeholder text to empty preview components

### ISSUE THREAD

**Issue by NightJar** [dnadesign/silverstripe-elemental#460]
When neither content nor a file is supplied to be used in the inline view of an Element currently nothing renders (in this space). It would be nicer to have a preview placeholder of "No preview available" - as per designs:

@clarkepaul @ https://github.com/dnadesign/silverstripe-elemental/issues/451#issuecomment-431213120
>Added placeholder title to designs https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5b90499d4d45900010a7be60

![image](https://user-images.githubusercontent.com/778003/47193639-842c4a00-d3b0-11e8-950f-1a204679ac89.png)

**Comment by robbieaverill** [comment]
Done with #462
