### ISSUE TITLE
New repo tag?

### ISSUE THREAD

**Issue by dizzystuff** [dnadesign/silverstripe-elemental#476]
Hey team, is there any chance of a new `3.0.1` or `3.1.0` tag any time soon? Dropped by to submit a PR and realised my issue was already resolved, three months ago (!), but it hasn't made it beyond the `3` branch.

Could you please provide an indication on when this might happen?

Thanks! Love the module.

**Comment by NightJar** [comment]
Hi @dizzystuff - should be coming in the next few weeks. We've been hammering away on v4, which is nearing release, v3 will slip in with it I should imagine.

**Comment by NightJar** [comment]
It's a bit more work, but also since there aren't any expected changes or open PRs for v3: https://github.com/dnadesign/silverstripe-elemental/releases/tag/3.1.0 :)

**Comment by dizzystuff** [comment]
This is terrific, and much appreciated. Thanks @NightJar !
