### ISSUE TITLE
Add more space to ElementalArea for DnD

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#484]
There is a good amount of space to drag and drop a block to the top of the list because the 'Add block' button is included in the ElementalArea. 
See:
![image](https://user-images.githubusercontent.com/15868440/47758368-a22e6e80-dd0f-11e8-90e2-f1474d99783e.png)

We could add some padding to the bottom of the ElementalArea so that there's more dropping space for a block at the bottom of the list. Currently you can't drop if the curser is beyond the bottom of the last block
Can't drop (no blue line) looks like this:
![image](https://user-images.githubusercontent.com/15868440/47758472-ffc2bb00-dd0f-11e8-87f1-8f85e7377684.png)

_Excuse the screenshots, it's hard to capture._

**Comment by clarkepaul** [comment]
Closing this issue as the details are captured in adesign/silverstripe-elemental/issues/544#issuecomment-445646003
