### ISSUE TITLE
File changes do not persist when collapsing/expanding the in-line form

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#490]
### Version

4.x

### Steps to reproduce

- Expand a form for a banner or file block (silverstripe/elemental-bannerblock)
- Add a file (or remove an existing one)
- Collapse the form without saving
- Reopen the form
- Note that your changes have disappeared

**Comment by ScopeyNZ** [comment]
I'll close pending the fix in silverstripe/silverstripe-asset-admin#862

**Comment by am071092** [comment]
@ScopeyNZ  I think PR: https://github.com/silverstripe/silverstripe-asset-admin/pull/922
will cause this issue to reappear again.

**Comment by ScopeyNZ** [comment]
Ok I have raised a new fix for the asset-admin issue:

https://github.com/silverstripe/silverstripe-asset-admin/pull/927

Hopefully that'll be acceptable and then I can encourage the maintainers to do a patch release of asset-admin.

**Comment by robbieaverill** [comment]
Fixed again with https://github.com/silverstripe/silverstripe-asset-admin/pull/927
