### ISSUE TITLE
URLSegment 

### ISSUE THREAD

**Issue by matthewntt** [dnadesign/silverstripe-elemental#491]
Access the page's URLSegment from within an elemental block. What do you think? It's a trivial change to BaseElement.php as outlined below. I can make a PR if you think it 's worth adding. 

``` php
public function GetURLSegment() {
    return $this::getPage()->URLSegment;
}
```

**Comment by robbieaverill** [comment]
We offer `getPage()` as an API to access the owner page already, you should be able to use `$Page.URLSegment` in a template to access this already. If that doesn't work then an extension in user code would be able to add it. Thanks for raising the issue 😄
