### ISSUE TITLE
Since 3.0.1 the area of a ElementalList gets the wrong OwnerClassName

### ISSUE THREAD

**Issue by brasileric** [dnadesign/silverstripe-elemental#492]
Since Elemental version 3.0.1 the ElementalArea of ElementalLists get the OwnerClassName "Page" instead of "DNADesign\ElementalList\Model\ElementList". This results in some strange behaviours of the list elements.

**Comment by robbieaverill** [comment]
Hi @brasileric, would you mind please logging this on https://github.com/dnadesign/silverstripe-elemental-list/issues? Thank you =)
