### ISSUE TITLE
Elemental in-line editor never loads when extension is added to existing pages

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#496]
### Affected Versions

4.x

### Description

When adding the `ElementalPageExtension` to a page type after some pages have already been added the element editor on the CMS for the page will never load. This is because there is no `ElementalArea` in the database for that page.

### Steps to reproduce

- Have a site with a page type that doesn't use the `ElementalPageExtension`.
- Create some pages using that page type
- Add the `ElementalPageExtension` to that page type and flush
- Browse to one of the pages your created
- Observe that the editor never finishes loading

### Notes

In this case GraphQL is kicking up a fuss because a null/zero ElementalAreaId is not considered valid.

I've listed this as medium impact because it's usually recommended that a page type is created specifically for elemental and then this issue would not occur - it's hard to create a page type for elemental and have a period where it's not using the elemental extension.

**Comment by robbieaverill** [comment]
You should probably run a dev/build as well as a flush in order to scaffold the elemental relationships for the page, but we can also probably build in some edge case handling for this as well

**Comment by NightJar** [comment]
PR https://github.com/dnadesign/silverstripe-elemental/pull/537
Needs tests. Maybe. Unsure.

**Comment by ScopeyNZ** [comment]
I was considering how to test this and I couldn't think of a good way. You'd need a behat test or something because you have to run a dev/build as a step within the test.

**Comment by NightJar** [comment]
I have been considering it for some time now, and am not sure it's worth testing. I updated the comment on the PR itself with my thoughts.

**Comment by ScopeyNZ** [comment]
Closed in #537
