### ISSUE TITLE
Remove BaseElement::getType and replace calls to it with DataObject::i18n_singular_name

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#503]
Currently we have `getType` as an overloadable type name for blocks that's translated. This is the same as what every DataObject has with `DataObject::i18n_singular_name` except the default is also configurable via config.

Before `4.0` is tagged stable we should remove this method and deprecate it in a `3.x` branch.

We're already (considering) switching to using `i18n_singular_name` within `getType` anyway: #502 .

**Comment by robbieaverill** [comment]
This method exists because you refer to “content blocks” outside of elemental context (i18n name) but “content” when inside elemental editor context. It’s by design.
