### ISSUE TITLE
History styling is off: Caret on the history "View Block" link is incorrect & font sizing issues

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#509]
### Affected Versions:

3.x, 4.x

#### Firstly the "View Block" link:

The font-icon is too small.

![image](https://user-images.githubusercontent.com/3260989/48682607-e1185b80-ec0d-11e8-84e3-98ab657369e0.png)

The underline on hover shouldn't go under the icon: 

![image](https://user-images.githubusercontent.com/24258161/48682794-fa6dd780-ec0e-11e8-9794-8eaa9e4b5186.png)

Designs:

![image](https://user-images.githubusercontent.com/3260989/48683026-04440a80-ec10-11e8-9380-f194a960d42b.png)

_(Note that this was originally intended to link to history of the individual block. Currently this only goes to edit the draft version of the block. The new wording is correct)_

#### The font size issue:

The titles of the various fields seem to have a non-standard smaller font-size:

![image](https://user-images.githubusercontent.com/3260989/48683039-19209e00-ec10-11e8-8096-fe950a6c30d9.png)

### Steps to reproduce

- Open a blocks page
- Have at least one block
- View the history for the page and select a version that has your block
- Observe the weird icon on the "View block" link & the small font size.

cc @sachajudd 
Reference: https://github.com/dnadesign/silverstripe-elemental/issues/223

**Comment by ScopeyNZ** [comment]
PR at #618

**Comment by ScopeyNZ** [comment]
> #### The font size issue:
> The titles of the various fields seem to have a non-standard smaller font-size:

I missed this. While this could be a problem with Elemental - it could also be a problem in admin.

I've put all my thoughts in a new issue: #620.

**Comment by robbieaverill** [comment]
Fixed in #618
