### ISSUE TITLE
Hide "new record" if multiple Types are available

### ISSUE THREAD

**Issue by JorisDebonnet** [dnadesign/silverstripe-elemental#51]
I've decided to use this module for my new web project, quite handy! There's one thing I don't find very user friendly though, and that's the "New record" button at the top right when you're editing an Element. The 'previous' and 'next' buttons are very handy, but the "New record" apparently creates a ElementContent object, even if the parent says that only ElementBox elements should be in the list. 

I realize that this functionality actually comes from BetterButtons, but I have no experience with that module, so I don't know whether I'm asking something impossible here :)

Ideally, the button should either be removed or provide a dropdown if multiple Elements can be created in this list; or if only one Element is supported here, one of those should be created, rather than an ElementContent.

**Comment by wilr** [comment]
+1 for removing the new record option.

**Comment by JorisDebonnet** [comment]
For now, I 'solved' it by hiding them with css. Perhaps that would suffice as a simple solution for this module as well - although of course being able to add a "correct" item with it (if there is only one type) would be very useful. 

`#Form_ItemEditForm_action_doNew {display: none}`

**Comment by pitchandtone** [comment]
SS4 branch will no longer rely on better buttons.

**Comment by wilr** [comment]
SS4 branch has been merged into v2 and new record functionality removed.
