### ISSUE TITLE
Elemental 4: Saving a Page triggers error

### ISSUE THREAD

**Issue by bummzack** [dnadesign/silverstripe-elemental#518]
When saving a Page that has elemental blocks in the CMS, an error will trigger: 

> E_WARNING: Invalid argument supplied for foreach()

And in the CMS:

![error message in cms](https://user-images.githubusercontent.com/1006185/48892904-65055a00-ee3f-11e8-983c-c0c61b59ccbd.png)

This happens, when `$this->Value()` in [`ElementalAreaField L:229`](https://github.com/dnadesign/silverstripe-elemental/blob/master/src/Forms/ElementalAreaField.php#L229) returns `null`.

Using `silverstripe/recipe-cms 4.3.x-dev` and `dnadesign/silverstripe-elemental 4.x-dev`. Same behavior can be observed with `ss 4.3.0-rc1` and `elemental 4.0.0-beta1`.

I guess the easiest fix would be to check for `null` or non-array values before running it through a `foreach`?

Steps to reproduce:

- Create a page that has the `ElementalPageExtension`
- Save the page. Most of the time, the error will trigger

**Comment by robbieaverill** [comment]
Yeah sounds good. We could also cast the value as an array before looping it. Would you like to make a PR?

**Comment by bummzack** [comment]
Hm, what is the result when I cast `null` to an array? `[ 0 => null ]`?
I guess it won't error when looping over that, but would add unnecessary overhead. 
I'd suggest checking for `is_array` before looping… and yes, I can create a PR

**Comment by robbieaverill** [comment]
It comes out as an empty array, but whatever you think is best =)

**Comment by bummzack** [comment]
Oh TIL, yeah in that case the cast is much cleaner :)

**Comment by ScopeyNZ** [comment]
Thanks @bummzack . This is fixed in the 4.0 branch: https://github.com/dnadesign/silverstripe-elemental/blob/b8698c6f6db42321f0d33ad1a0ed04e11197ab50/src/Forms/ElementalAreaField.php#L232 . It's just pending a merge up 🙂 

I'll do that in the morning and close this issue.

**Comment by robbieaverill** [comment]
Oh nice, I'll do that now to save you the trouble
