### ISSUE TITLE
Hide "ID" column

### ISSUE THREAD

**Issue by JorisDebonnet** [dnadesign/silverstripe-elemental#52]
Just a suggestion. I feel like the ID is meaningless to a content editor. And the web developer can easily find the ID by hovering over the Edit-button. 

If there is a reason to keep them, perhaps there could be some config setting to hide them?

**Comment by wilr** [comment]
The reason for keeping them was to help with 'linking' when you have 300 blocks and 'title' becomes meaningless ID is a foolproof way, also we show the CMS authors to use the ID for anchors.
