### ISSUE TITLE
Indicator for block is modified is blue, it should be orange

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#524]
**Version: elemental 4.0.x-dev with SS 4.3.x**

![image](https://user-images.githubusercontent.com/5170590/49082792-f5320d80-f24a-11e8-9a32-30e651ab4a27.png)

This icon should be orange, not blue. Looks like this changed in b91056b8

### PR

#538

**Comment by ScopeyNZ** [comment]
It should be blue for _unsaved_ changes: https://invis.io/N5MVKR392DS#/307488190_Unsaved_Changes

Is it showing blue when it shouldn't?

**Comment by robbieaverill** [comment]
Oh ok, the designs must have changed. All good!

**Comment by robbieaverill** [comment]
Ok I think there are still some inconsistencies.

Published block state:


When it has unsaved changes:
![image](https://user-images.githubusercontent.com/5170590/49140192-eeaba080-f2f3-11e8-8746-39d65ecb0bfc.png)

When you save it (inline):
![image](https://user-images.githubusercontent.com/5170590/49140212-fa976280-f2f3-11e8-8d7c-fabe29796698.png)

Block is modified now, refresh the page:
![image](https://user-images.githubusercontent.com/5170590/49140276-2b779780-f2f4-11e8-8979-af6d40bf3f23.png)

The last screenshot is what we originally had in the designs for a "modified" state. If the designs have changed so that this should now be blue, we should update it here as well so it's consistent.

I also noticed that when you save a block inline then refresh the page it triggers the change tracker warning - at this point you've saved the changes, so it probably shouldn't. This is a different issue though.

**Comment by robbieaverill** [comment]
cc @clarkepaul

**Comment by ScopeyNZ** [comment]
When you save it in-line and it doesn't change from blue that's a bug. Everything else is okay I think. Once it's saved it should go orange to indicate a draft version? I can't remember the difference between orange filled and orange outline now 😖

**Comment by robbieaverill** [comment]
Originally the orange circle without fill was "draft" which indicates it hasn't been published yet, and "modified" is the filled circle, meaning published and subsequently modified

**Comment by clarkepaul** [comment]
The blue indicator shouldn't show if the block is saved. We needed a way to indicate which block(s) have unsaved changes so they can be reviewed and saved before navigating away. The draft and modified indicators should stay as they are and hopefully aren't affected. This blue indicator is only for blocks at this stage, most other things don't require multi-item editing so it usually clearer what is being saved. Looks like a bug with "When you save it (inline)" unfortunately.

**Comment by ScopeyNZ** [comment]
Fix at #538
