### ISSUE TITLE
Publishing a block inline doesn't update its status indicator

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#525]
**Version: elemental 4.0.x-dev, SilverStripe 4.3.x-dev**

* Add a content block
* Set some content 
* Save it via more actions menu
* Close the inline editing for it
* Select Publish from the dropdown menu

Expected: It should publish, and the state indicator should change to remove the solid circle, indicating draft/modified state.

Actual: it doesn't update the state indicator

It used to do this when we told it to refetch the data for that block - perhaps something with optimistic cache updating has changed this recently.

### PR
#597

**Comment by ScopeyNZ** [comment]
I've noticed this with the new-ish unsaved changes indicator. Saving dismisses the unsaved changes but publishing doesn't. Slightly frustrating.

**Comment by NightJar** [comment]
>I remember @NightJar mentioning this a while ago

May provide context:
https://github.com/dnadesign/silverstripe-elemental/issues/470
https://github.com/dnadesign/silverstripe-elemental/issues/312#issuecomment-433227789

**Comment by ScopeyNZ** [comment]
I _think_ that publishing now does perform a save action first now. That was one of the things @NightJar fixed while we were working on this.

**Comment by clarkepaul** [comment]
^ just mentioned a couple issues which might be duplicates?

**Comment by robbieaverill** [comment]
I can't reproduce this on 4.0@d89d5f721d3fd9ce145628b52406821a1824e26f
