### ISSUE TITLE
Adding new blocks to a page doesn't change its modified status

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#527]
**Versions: SS 4.3.x-dev with elemental 3.2.x-dev OR elemental 4.0.x-dev**

* Create a new page
* Publish the page with no blocks
* Add three content blocks, all with "Version 1a" as the content
* Save each block and return to the page

Expected: the page should indicate somehow that it is in a draft state, since the content for the page has changed and is not yet published

Actual: the page remains in an unmodified (no draft changes) and published state

![image](https://user-images.githubusercontent.com/5170590/49245636-3bd26400-f413-11e8-9794-aa39fc920edc.png)

**Comment by robbieaverill** [comment]
## Debugging info

Page ID: 13
Creation: create page in root of site tree, change name to "Elemental test page", save

### Step one, add a block and save it

* `Page.ElementalAreaID` remains as 15
* `ElementalArea.Version` remains as 1

### Step two, publish the page

* `Page.ElementalAreaID` remains as 15
* `ElementalArea.Version` is changed to 2

### Step three, edit the block's content and save it

* `Page.ElementalAreaID` remains as 15
* `ElementalArea.Version` remains as 2 

---

So it looks like the problem is that the ElementalArea's version is not increased when an element it owns is modified. If it were, we probably wouldn't have an issue.

**Comment by ScopeyNZ** [comment]
I've raised an issue over on versioned that is related to this: https://github.com/silverstripe/silverstripe-versioned/issues/195

**Comment by robbieaverill** [comment]
I'm going to close this as a duplicate now
