### ISSUE TITLE
The history viewer doesn't show a draft version of the page to compare against after making unpublished changes

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#528]
**Versions: SS 4.3.x-dev with elemental 3.2.x-dev OR 4.0.x-dev**

* Create a page
* Publish it
* Add a block to it with some content
* Save the block
* Go back to the page
* Publish the page
* Edit the block and update the content
* Save the block
* Notice that the page doesn't indicate that it's in a modified state yet (see #527)
* Go to the history tab

Expected: there is a draft version I can select which both shows the latest content block changes that aren't published, and allows me to compare it against the current published version

Actual: only the latest published version is at the top of the list

![image](https://user-images.githubusercontent.com/5170590/49245936-febaa180-f413-11e8-8130-2fe78852cdad.png)

**Comment by ScopeyNZ** [comment]
There has been __plenty__ of discussion in `silverstripe-versioned` about this issue: https://github.com/silverstripe/silverstripe-versioned/issues/195

I think we can close this in favour of that?

**Comment by robbieaverill** [comment]
Yeah it's mostly the same issue
