### ISSUE TITLE
Bug: element added to wrong ElementList

### ISSUE THREAD

**Issue by JorisDebonnet** [dnadesign/silverstripe-elemental#53]
1. Create an ElementList "A" with a few Items
2. Detach/unlink one of the Items
3. Attach it to another ElementList "B" ("Link existing")
4. Add a new Item to ElementList "B"

The new item will be added to ElementList "A" instead.

**Comment by wilr** [comment]
Virtual blocks and unlinking has now been spun off to its' own module (temp: https://github.com/silverstripe/silverstripe-elemental-virtual) soon to be migrated
