### ISSUE TITLE
Block collapses when it is new and is opened for the first time

### ISSUE THREAD

**Issue by clarkepaul** [dnadesign/silverstripe-elemental#540]
To reproduce:
- add a block 
- click to open the block
You will notice the block height reduces while it is loading, and you see a shadow inside the block.
Suggested fix would be to apply a min-height to blocks that are collapsed and have the preview area. 
Refer to designs for min-height https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5b8c6cbfc5ffe300176d8e23

**Comment by robbieaverill** [comment]
Not sure I'm 100% on the issue here. Are you able to provide a screen recording?

**Comment by ScopeyNZ** [comment]
Perhaps this is not even an issue any longer?

**Comment by robbieaverill** [comment]
Yeah we did do some adjustments to the element heights and padding - probably happened between now and when this issue was raised

**Comment by ScopeyNZ** [comment]
Ok I just tried to validate this issue again and I couldn't reproduce. I'm going to close this as "probably fixed by something since it was raised"

**Comment by brynwhyman** [comment]
@clarkepaul I can't recreate this with the latest stable branch installed. Please reopen this issue if you believe the problem still exists.

**Comment by brynwhyman** [comment]
> Ok I just tried to validate this issue again and I couldn't reproduce. I'm going to close this as "probably fixed by something since it was raised"

Ha, bet me to it! I must have had an old page open....
