### ISSUE TITLE
BUG can't add blocks to page

### ISSUE THREAD

**Issue by micmania1** [dnadesign/silverstripe-elemental#543]
When you install the elemental module and add the page extension to a page, you can't add any blocks until you save the page. This is because until you save the page, the ElementalArea doesn't exist.

In v3 you're able to add the block, but then its not attached back to the page even though its saved in the database.

In v4 the loading indicator displays in the block area and gets stuck, preventing you from adding any blocks.

cc @sachajudd

**Comment by ScopeyNZ** [comment]
Have you tried the latest `4.0.x` branch? We patched this yesterday: #496 . It hasn't been merged into the `4.x` branch yet. 

As long as you dev/build there should always be an area on your pages - and you have to dev/build after adding the extension.
