### ISSUE TITLE
A preview update is not triggered on reorder

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#547]
### Affected version:

4.x

### Description

Currently when performing actions on blocks the preview will update after the action so that you get live preview of the changes you're making. When dragging around blocks to re-order there is no change being triggered

### Steps to reproduce

- Create/edit a blocks page
- Make at least two blocks with content
- Observe the preview and note the order of blocks
- Re-order the blocks by dragging around blocks
- Note there's no update to the preview
- Trigger an update by publishing (or refreshing)
- Note that the preview updates in this case and shows the correct order of blocks.

**Comment by robbieaverill** [comment]
Is this another manifestation of "modifying blocks doesn't update the page status"?

**Comment by ScopeyNZ** [comment]
The page status not being updated is probably expected (because of the existence of silverstripe/silverstripe-versioned#195). This is talking about the preview side-panel explicitly though - which we still have to trigger a change on - something we've done for the existing save mechanisms.

**Comment by ScopeyNZ** [comment]
Closed in #553
