### ISSUE TITLE
History of blocks not compatible with Fluent locales

### ISSUE THREAD

**Issue by clarkepaul** [dnadesign/silverstripe-elemental#549]
We're still figuring the finer details, but from our entail play it seems that the history of pages/blocks do not work with the Fluent module. We are currently using 4.3 (pre-stable release) and populating a site with fresh content.

Maybe we have missed some important configuration that we might uncover still.

cc @brynwhyman, @sachajudd

**Comment by ScopeyNZ** [comment]
Can you give a little detail on what you're seeing/not seeing?

**Comment by sachajudd** [comment]
Looks like some code is missing to configure this. Closing this for now.

```php
   /**
     * Fluent specific configuration
     *
     * @var array
     */
    private static $field_include = [
        'ElementalAreaID',
    ];  
```
