### ISSUE TITLE
Elemental does not keep changes in the right local when used with Fluent

### ISSUE THREAD

**Issue by clarkepaul** [dnadesign/silverstripe-elemental#550]
Version: 4.3 pre-release of stable, with CWP recipe
Compatibility issues with Fluent.
When updating a secondary locale, the main locale receives the updates rather than the secondary locale. This means you cannot update the content in the secondary locale at all if using content blocks.

cc @brynwhyman @sachajudd

**Comment by ScopeyNZ** [comment]
Is this the same as #549 ? See the comment in that issue.
