### ISSUE TITLE
Tag 4.0

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#551]

**Comment by robbieaverill** [comment]
I think we need to make this a "release recipe-content-blocks 2.1.0 stable" which would include this as 4.0.0 but also silverstripe/elemental-fileblock and silverstripe/elemental-bannerblock as 2.0.0 stable

**Comment by ScopeyNZ** [comment]
Thanks @robbieaverill . I've released a new 2.2.0@stable with all the modules tagged.

Please let me know what I've forgotten this time 😂

**Comment by robbieaverill** [comment]
I've created the 2.2 branch for the content blocks recipe 😛

**Comment by ScopeyNZ** [comment]
Oh the branching 🤦‍♂️
