### ISSUE TITLE
Custom Editor Preview Templates not found

### ISSUE THREAD

**Issue by derralf** [dnadesign/silverstripe-elemental#555]
elemental version: 3.0.x-dev

Custom Editor Preview Templates not found until getEditorPreview() gets overwritten

I have a custom Element in `app/src/element/ElementProjectGallery`:

```
<?php
namespace App\Element;
class ElementProjectGallery extends BaseElement {
....
...
```
Now I want to overwrite the Preview Template for the Backend (show image thumbnails).
I tried with `BaseElement_EditorPreview.ss` and `ElementProjectGallery_EditorPreview.ss` and tried to place them i various folders in my own theme. They where not found.

when I overwrite getEditorPreview() in my element and comment the fallback template:

```
    public function getEditorPreview()
    {
        $templates = $this->getRenderTemplates('_EditorPreview');
        // $templates[] = BaseElement::class . '_EditorPreview'; // comment for testing only
        return $this->renderWith($templates);
    }
```

I can see that it only searches

```
[0] => silverstripe/admin:cms-forms
[1] => $default
```
Where I think `$default` is the original dnadesign/silverstripe-elemental folder in vendor-modules.

My own theme folder will not be searched until I add **SSViewer::set_themes(SSViewer::config()->get('themes'));**:

```
<?php
namespace App\Element;
class ElementProjectGallery extends BaseElement {
...
    public function getEditorPreview()
    {
        SSViewer::set_themes(SSViewer::config()->get('themes'));
        $templates = $this->getRenderTemplates('_EditorPreview');
        // $templates[] = BaseElement::class . '_EditorPreview'; // comment for testing only
        return $this->renderWith($templates);
    }
```

template path/name:
```
themes
  <mytheme>
    App
      Element
        ElementProjectGallery_EditorPreview.ss
```

For my "own" elements, this is possible. But this way I can't use custom EditorPreviews for other/existing Elemental-Elements (to display e.g. style, images or other addidtional information)

**Comment by robbieaverill** [comment]
Yeah the problem is that the CMS generally doesn't take frontend themes into account. We've seen this problem a couple of times in elemental before - from memory an example is the Solr indexer we provide/document an example of.

Your fix is the correct way to achieve this I think, but make sure you unset the themes again before returning. Would you like to make a PR?

**Comment by derralf** [comment]
#558
