### ISSUE TITLE
[3.x] History viewer order is ascending rather than descending

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#561]
**Version: SS 4.3.0 with elemental 3.x-dev**

When viewing the history for an element, the order is ascending rather than descending:

![image](https://user-images.githubusercontent.com/5170590/50300601-d35c2d00-047c-11e9-8af9-a738cfd973f9.png)

**Comment by robbieaverill** [comment]
The underlying GraphQL query is not extensible or sortable in silverstripe/versioned 1.1: https://github.com/silverstripe/silverstripe-versioned/blob/1.1.0/src/GraphQL/Operations/ReadVersions.php#L51.

We've adjusted this so that you can both modify with extensions (https://github.com/silverstripe/silverstripe-versioned/commit/2a07f5f93e750c480437e16964219b09041b684f) and can sort by the version ID column in your GraphQL query (https://github.com/silverstripe/silverstripe-versioned/commit/c928e830825ec8ae5336d254835f754a11bac350#diff-eabd48e155178fb16e084912b8b00179R32) in silverstripe/versioned 1.3.

Since elemental v3.0 supports SilverStripe 4.2 I'll ignore that version, but we can fix this in elemental v3.1 and 3.x for SilverStripe 4.3.

**Comment by robbieaverill** [comment]
PR for elemental 3.1 at https://github.com/dnadesign/silverstripe-elemental/pull/644

**Comment by ScopeyNZ** [comment]
Closed in #644
