### ISSUE TITLE
Duplicate Blocks

### ISSUE THREAD

**Issue by newleeland** [dnadesign/silverstripe-elemental#562]
## Potential AC's
As a user I would like to create a copy of an existing block, so that I can reuse existing block and content inside.

## Designs
https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5c075839cfbaa5001082162f

**Comment by newleeland** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Copy/duplicate blocks](https://trello.com/c/A1cgmq2T/407-copy-duplicate-blocks)

**Comment by newleeland** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Copy/duplicate blocks](https://trello.com/c/A1cgmq2T/407-copy-duplicate-blocks)

**Comment by annabayliss** [comment]
Yes I think this feature would be extremely useful, especially when creating lots of blocks which have all the same styling (and am surprised it is not available already)

**Comment by brynwhyman** [comment]
@silverstripeux, it looks like the referenced design link is private, can you please make it public?

**Comment by brynwhyman** [comment]
A pull request has just come in for this :)
https://github.com/dnadesign/silverstripe-elemental/pull/770

**Comment by sachajudd** [comment]
Will close this issue off and create some new ones regarding my comments here: https://github.com/dnadesign/silverstripe-elemental/pull/770#pullrequestreview-378143557
