### ISSUE TITLE
Behat builds are broken (FormBuilder init'd TinyMCE is broken in SS 4.4)

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#563]
See:

* ~https://travis-ci.org/dnadesign/silverstripe-elemental/jobs/464264110~ fixed https://github.com/silverstripe/silverstripe-admin/pull/860
* https://travis-ci.org/silverstripe/silverstripe-elemental-bannerblock/builds/469332505

**Comment by robbieaverill** [comment]
I've done a merge up from 4.0 to master and fixed the conflicts - that might help to fix behat, which is passing in the 4.0 branch: b91912a

**Comment by robbieaverill** [comment]
Nope, didn't fix it

**Comment by brynwhyman** [comment]
I'm happy to keep this as `impact/critical` but it's worth noting that the bug is only present in SS 4.4.x-dev due to the introduction of React 16, which is yet to be released.

**Comment by robbieaverill** [comment]
Downgraded impact rating since the main bug is fixed. The banner block builds are still broken but I think it's something else.

**Comment by robbieaverill** [comment]
Fixed with https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/25
