### ISSUE TITLE
Publishing the page causes the content in a block to disappear until refresh

### ISSUE THREAD

**Issue by lexakami** [dnadesign/silverstripe-elemental#565]
Version: `4.0.0` with SilverStripe 4.3.0

Steps to replicate: 

1. Create an inline editable block on a page
2. Expand the block and add text into the content field
3. Click "Publish" on the page
4. The updated content doesn't display inside the block

If you refresh or publish a second time, the content is displayed. So it is saving the value of the field, but rendering the previous version of the content (which in this case is none). If you add more content, and publish the page, it shows the previous version of content until you refresh or publish again. This only seems to happen when publishing the page, not publishing the block individually. 

I also get this error in the console: `Unhandled promise rejection Error: "Network error: Store reset while query was in flight(not completed in link chain)"`

**Comment by ScopeyNZ** [comment]
> Also publishing the page while the content block is open and showing the previous content seems to overwrite the current content.

Not too surprised by this. A publish page action will run through and save all the fields on the page before publishing

**Comment by Kethatril** [comment]
Makes sense, we have had to disable inline editing as this bug makes it too easy to overwrite data.

**Comment by ScopeyNZ** [comment]
Hmmn. Not good. I'll bump up the impact then.

**Comment by ScopeyNZ** [comment]
FYI for those monitoring this issue we're going to look at it very soon (this/next week).

**Comment by robbieaverill** [comment]
Fixed with #581
