### ISSUE TITLE
Unused variable. Remove redundant $tableName variable.

### ISSUE THREAD

**Issue by StephenMakrogianni** [dnadesign/silverstripe-elemental#572]
https://github.com/dnadesign/silverstripe-elemental/blob/b91912a9ad54a78c388878e055e8c28515d892a3/src/Extensions/ElementalAreasExtension.php#L269

**Comment by ScopeyNZ** [comment]
Thanks Stephen. Care for a PR?

**Comment by robbieaverill** [comment]
Bump @StephenMakrogianni

**Comment by StephenMakrogianni** [comment]
Closing because this appears to be done
