### ISSUE TITLE
Content authors cannot edit blocks

### ISSUE THREAD

**Issue by scott1702** [dnadesign/silverstripe-elemental#586]
Currently only users with full administrative rights can edit content blocks.

**Steps to reproduce**:
1. Login as a content author user with permission to edit any page
2. Navigate to a page with an ElementalArea

**Expected result:**
User can edit content blocks as per usual

**Actual result**
ElementalArea gets stuck in loading state, with a JavaScript error of `Cannot view ElementalArea`

**Comment by ScopeyNZ** [comment]
Both the GraphQL and the elemental PRs have been merged now 🙂
