### ISSUE TITLE
Unsaved changes status indicator doesn't update when publishing from the dropdown

### ISSUE THREAD

**Issue by sachajudd** [dnadesign/silverstripe-elemental#588]
The blue "Unsaved changes" status indicator doesn't update when Publishing first from the blocks more options dropdown.

**Steps to reproduce:**
* Add a new content block
* Add some content to TinyMCE noting the blue "Unsaved changes" status indicator on the block icon
* Click more options dropdown on the block and select "Publish"

Seems to work fine if you publish first from the CMS action toolbar.

### PR
#597

**Comment by robbieaverill** [comment]
@ScopeyNZ didn't we see this earlier where the publish GraphQL mutation was only publishing the latest draft version, but not saving any unsaved changes first? Seems related

**Comment by ScopeyNZ** [comment]
Hmmn. I can't recall to be honest. I was going to run over some elemental stuff tomorrow (my time) so I'll play around then.

**Comment by clarkepaul** [comment]
I think this issue and https://github.com/dnadesign/silverstripe-elemental/issues/591 might be a duplicate for https://github.com/dnadesign/silverstripe-elemental/issues/525 ?

**Comment by robbieaverill** [comment]
Fixed with #597. I'd note that the behaviour now goes from solid blue indicator to hollow orange indicator to disappearing completely which isn't ideal, but at least this is behaving the way it was before we merged #581
