### ISSUE TITLE
Element Image relationship not saved when editing inline

### ISSUE THREAD

**Issue by digitall-it** [dnadesign/silverstripe-elemental#590]
When using Silverstripe v4.3.0 and Elemental v4.0.1 with PHP 7, I cannot seem to save my Image relationship when editing inline. Attached you'll find my composer.json+lock

[composer.zip](https://github.com/dnadesign/silverstripe-elemental/files/2822562/composer.zip)

 and my custom Element block.

[ElementTextWithImage.php.zip](https://github.com/dnadesign/silverstripe-elemental/files/2822564/ElementTextWithImage.php.zip)

Thank you all for your wonderful work!

---

## Steps to reproduce

* Add a new File Block (from silverstripe/elemental-fileblock) or a custom block (like above) with an associated Image
* Upload an image into it
* Either save the page, or the block individually via its "more actions" menu
* Open the block again

## Expected

It should show the image that you just uploaded.

## Actual

It doesn't show any image at all, which makes you think your upload hasn't worked. Refresh the page and open the block again to see that it has in fact been saved.

**Comment by robbieaverill** [comment]
Thanks for providing the background files @digitall-it!

I've had a quick look at this. As far as I can tell, the image relationship _is_ being saved, but it doesn't reflect that in the elemental UI until you refresh the page. This could be an issue with the redux form state not being updated for the UploadField.

I've cross checked this against the silverstripe/elemental-fileblock module in a fresh installation, and it's the same result there. I'll move this issue to that module and track it from there.

**Comment by robbieaverill** [comment]
Yeah looks like this is a weird redux form state thing. Here's the order of events:

* You open an inline editable block, redux form initialises with initial values and current values for each field (e.g. Image: 1)
* You replace the image
* Image ID is removed from the redux form state
* UploadField processes the new image
* Image ID is set back into the redux form state
* React re-renders the appropriate form field for the Image
* Minimize the editable block and re-open it again
* The form is reloaded, redux-form populates again and React renders all form fields again
* Right at the end a `UPLOADFIELD_SET_FILES` dispatch is made with the stale data, which updates the Redux form state again

The last dispatch is what is causing this problem. You can jump back to the previous item and see the field renders correctly, then this one fires and redux-form subsequently updates the state to the stale ID, causing React to re-render again.

**Comment by robbieaverill** [comment]
Oh good news! @ScopeyNZ has already fixed this in asset-admin with https://github.com/silverstripe/silverstripe-asset-admin/pull/863. The original issue was https://github.com/silverstripe/silverstripe-asset-admin/issues/862 and it's available in SilverStripe 4.3.2. Upgrading to the latest version will fix your problem =)

**Comment by ScopeyNZ** [comment]
This issue is reoccuring again (and it's also raised in #560 and #490). There's an open PR right now addressing the issue in asset-admin: https://github.com/silverstripe/silverstripe-asset-admin/pull/927
