### ISSUE TITLE
Unsaved changes icon persists after saving

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#591]
This is a new issue that has popped up since #565 so only exists in __4.0.x-dev__. Although the content of the block is updating correctly now when re-expanded the unsaved changes icon is not being removed and you get a "you have unsaved changes" modal.

### Steps to reproduce:

- Create a block
- Update the content of that block
- Save the block using the page level save button
- Note that the unsaved changes icon persists.

### Investigation

I had a quick look at this based on the fact it was caused by the recent fix to #565:

https://github.com/dnadesign/silverstripe-elemental/blob/5d5552d7651c7777286ba5b5b461e8905bdff053/client/src/legacy/ElementEditor/entwine.js#L61-L63

Changing this to unpack both the form names and the form names prefixed with `elemental.` _almost_ fixes the issue. There's still an issue where TinyMCE doesn't work.

I guess this is a slightly _less_ impact issue than #565 but I still think we should resolve this before a new release.

### PR
#597

**Comment by clarkepaul** [comment]
I think this issue and https://github.com/dnadesign/silverstripe-elemental/issues/588 might be a duplicate for https://github.com/dnadesign/silverstripe-elemental/issues/525 ?

**Comment by ScopeyNZ** [comment]
> I think this issue and #588 might be a duplicate for #525 ?

#525 is (I think) that you don't get rid of the orange dot when publishing in-line
#588 is that the blue dot doesn't disappear when publishing in-line (slightly different)
This one is just talking about saving. It's new and more wide ranging 🙂 

Either way there's a PR open now that should fix it 👍🌲

**Comment by robbieaverill** [comment]
Fixed with #597
