### ISSUE TITLE
Remove Elemental areas from showing in campaigns

### ISSUE THREAD

**Issue by clarkepaul** [dnadesign/silverstripe-elemental#593]
Elemental areas are not relevant to a users campaign and therefor aren't required to be shown in the campaigns area as a category type. They should be hidden from the campaign.

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/136
- [x] #602

**Comment by robbieaverill** [comment]
The data object gets added as an "implicit" changeset item, which means that it's being referenced from the page that was "explicitly" added to a campaign. Unfortunately the campaign admin API doesn't provide any way to opt out of displaying implicitly added changes in the UI, so I'll need to add this as an enhancement before fixing it as a bug here.

**Comment by robbieaverill** [comment]
PRs posted to the description

**Comment by ScopeyNZ** [comment]
PR's merged
