### ISSUE TITLE
LiteralField and LabelField do not have padding when inline editing

### ISSUE THREAD

**Issue by DorsetDigital** [dnadesign/silverstripe-elemental#598]
If you have an element which uses a LiteralField or LabelField, that field is rendered without any padding during inline-editing, causing it to site hard against the left of the container.

![screenshot from 2019-02-08 17-12-26](https://user-images.githubusercontent.com/15108750/52494538-2a9d9480-2bc6-11e9-85f7-55c957df2f22.png)

Using `->addExtraClass('form__field-label')` on the field gives the container (or label) a class with the padding to match the rest of the form, but I'm not sure if this is an expected behaviour for these field types.

**Comment by robbieaverill** [comment]
Hmm, this could be a core issue. Let me investigate.

**Comment by ScopeyNZ** [comment]
Yeah I've had a look at this. Definitely an elemental issue. We apply the "row" class (that adds negative margins) too early from the looks of things. We apply it to the whole form where-as it is applied on the form group level in other parts of the CMS. Elemental then zero's out the margin on form groups.

Probably needs to rebalance where we apply margins.

**Comment by robbieaverill** [comment]
Partial revert of https://github.com/dnadesign/silverstripe-elemental/pull/489 fixes this, PR at https://github.com/dnadesign/silverstripe-elemental/pull/694

**Comment by ScopeyNZ** [comment]
Fixed in 4.1.x (#694)
