### ISSUE TITLE
SilverStripe TagField doesn't appear in Block Settings

### ISSUE THREAD

**Issue by nzstephenf** [dnadesign/silverstripe-elemental#599]
I have the latest stable version compatible with SilverStripe 4.3 (Elemental 4.0.2). If you have an elemental block that has SilverStripe\TagField with your available fields, they don't show up correctly and fall back to a standard dropdown field within a Page's edit screen.

Currently, the only way to use TagField's as intended within my elemental block settings for example is: 
> https://domain.name/admin/pages/edit/EditForm/1/field/ElementalArea/item/123/edit

This is what I see at the moment:
![image](https://user-images.githubusercontent.com/8021977/52515901-cabaf280-2c86-11e9-8940-cd37b1268232.png)

What I was expecting to see (this is hard-linking through to the old method of creating/editing elemental blocks):
![image](https://user-images.githubusercontent.com/8021977/52515926-1372ab80-2c87-11e9-807f-24ba18fda0a7.png)

**Comment by ScopeyNZ** [comment]
Ok I think this is a known issue with TagField unfortunately. There's an open PR with some outstanding issues: https://github.com/silverstripe/silverstripe-tagfield/pull/120

**Comment by robbieaverill** [comment]
Yep, this is not an elemental issue
