### ISSUE TITLE
Image Output

### ISSUE THREAD

**Issue by hadleelineham** [dnadesign/silverstripe-elemental#6]
i was trying to make it out put the image but id just seems to out put the $content so i tried doing $Content.RAW on my page.ss file but no luck. so maybe some documentation on this will help. i am still really keen on using this so once this is solved ill come back to it.

**Comment by yoyo23** [comment]
You have to put your $Image inside a <% with Widget %> to render correct.
Have a look at templates/elements/ElementImage.ss .
Took me also a while to find it out.
