### ISSUE TITLE
Saving a block inline with no changes reports as a failure

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#603]
**4.0.x-dev**

This happens because the API result says `updated: false`, so we detect that as a failure. In fact, nothing has changed, so nothing was updated.

Perhaps we need to pass an explicit `success` boolean as well to indicate whether the request was successful or not (false if there was an exception thrown for example).

**Comment by robbieaverill** [comment]
>This happens because the API result says `updated: false`

Incorrect assumption, the redux form data isn't available at the time so there's an undefined index error inside a try/catch. Fix as part of #601

**Comment by ScopeyNZ** [comment]
Fixed in #601
