### ISSUE TITLE
Changes persist between page browsing and breaks page level change tracking

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#605]
"Changes persist between page browsing" probably doesn't sound like a bug but here's the current process:

- Open a blocks page, choose to edit an in-line editable block, and make some changes
- Note that the page level change tracker (the save button) indicates changes have been made
- Without saving or publishing, browse to a different page
- Note that you get a "You have unsaved changes... They'll be discarded" message
- Accept the prompt and continue to the other page
- Browse back to your original page
- Note that the unsaved changes remain on the block you edited.
- Now the "Save" button implies there are no changes
- The page level change tracker never updates (and will actually have a flipped state where it will only show changes when you manually revert your changes 😅 )

Having the changes persist is pretty awesome. Redux stores the form state (and the page never actually changed because we use pjax for page navigation) 

This isn't very good UX though.

I think we should revert changes when they browse away from the page - this should fix the page level tracking problem too.

I considered the possibility of not showing the unsaved changes message, but considering the other edit forms in SS this would be unusual. Additionally fields outside of the elemental area would still have their state lost.

**Comment by robbieaverill** [comment]
PR at https://github.com/dnadesign/silverstripe-elemental/pull/693 with some notes
