### ISSUE TITLE
Subsites 

### ISSUE THREAD

**Issue by digitall-it** [dnadesign/silverstripe-elemental#61]
Has anyone tried Elemental with Translatable and Subsites? Are they compatible?

**Comment by pitchandtone** [comment]
Yes we run elemental on wellingtonnz which uses translatable, and on gel which has subsites.

**Comment by pitchandtone** [comment]
Sorry rgl, not gel.

**Comment by digitall-it** [comment]
yay!

**Comment by digitall-it** [comment]
Is it http://www.wellingtonnz.com/ ? Very nice work! Did you use an existing module for having http://www.wellingtonnz.com/es/home/ instead of http://www.wellingtonnz.com/home-es/  or is it the default behaviour?

**Comment by wilr** [comment]
See https://github.com/Martimiz/silverstripe-languageprefix
