### ISSUE TITLE
[META] Decide when to release the React 16 upgrade

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#614]
Currently the next minor branch (aka. 4.x-dev) is `master`. The upgrade to React 16 is in `master`. We are currently accepting (and potentially planning) some minor updates that should target `master`.

We need to decide whether it's reasonable (or even possible) to release `4.1.0` from `master` independently of the rest of the SilverStripe React modules/components. Currently the minor releases of this module are blocked by that.

Additionally we could consider whether we release a major version of this module with the React 16 upgrade which means we'll need to create a `4` branch from a commit that happened prior to the React 16 upgrade.

**Comment by robbieaverill** [comment]
It will _have_ to be with CWP 2.3, because the React 16 upgrade will break older versions of Elemental so we'll have to release Elemental 4.1 at the same time as SilverStripe 4.4 in CWP 2.3.

**Comment by ScopeyNZ** [comment]
Yep. I was catering for other minor additions before 4.4 but it looks like that's not going to happen anyway.

**Comment by ScopeyNZ** [comment]
I'll just close this issue. We'll be releasing it with CWP 2.3.0
