### ISSUE TITLE
MigrateContentToElement doesn't find any pages to migrate

### ISSUE THREAD

**Issue by quamsta** [dnadesign/silverstripe-elemental#617]
After adding ElementalPageExtension to Page's extensions and running a dev/build?flush, ElementalAreas are created and the MigrateContentToElement task doesn't seem to work because of this filter:

`$pages = $pageType::get()->filter('ElementalAreaID', 0);`

Since every page now has an ElementalArea, the ElementalAreaID will never be 0. Not even sure when this filter could ever be true. I removed the filter, and this task does seem to run, but creates multiple Elements per ElementalArea, and I'm not really sure where to go from there.

**Comment by ScopeyNZ** [comment]
Yeah that's an interesting problem. In the end it looks like it was easier to just to get the new editor handling missing areas rather than ensuring the pages always have an area. Not quite sure how to fix this one too be honest - hence the `effort/hard` label 😅

**Comment by altwohill** [comment]
What about adjusting the filter to be 
` $pages = $pageType::get()->filter('Content:not', '');`

**Comment by robbieaverill** [comment]
@ScopeyNZ does #652 resolve this?

**Comment by ScopeyNZ** [comment]
Yes.
