### ISSUE TITLE
Still seeing issue: #575 unable to highlight text areas / other fields in inline editing mode

### ISSUE THREAD

**Issue by tomstgeorge** [dnadesign/silverstripe-elemental#625]
Still seeing issue #575 

Just tried on clean silverstripe 4.3 install

**Comment by robbieaverill** [comment]
@tomstgeorge can you please share the specific versions of silverstripe/admin and dnadesign/silverstripe-elemental that you're using?

**Comment by robbieaverill** [comment]
Nevermind - #575 hasn't been included in a stable release yet, which is probably why it's still broken for you.

I've just tagged elemental 4.0.3 - could you please update your version to that? Please comment on #575 if this still is broken after updating elemental, and we'll reopen that issue instead.

**Comment by tomstgeorge** [comment]
Silverstripe 4.3.2

dnadesign/silverstripe-elemental (4.0.2)

**Comment by tomstgeorge** [comment]
Thanks @robbieaverill
