### ISSUE TITLE
Ensure inline adding of blocks can be tabbed to

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#627]
### Overview

It is currently not possible to tab to the function to add blocks inline. This is important as the current drag and drop library doesn't allow for reordering with keyboard actions.

Feature in discussion:
![image](https://user-images.githubusercontent.com/15868440/47121853-d5fda300-d2d0-11e8-979f-1fdeff6788bc.png)

Split from #455 so this gets more visibility. 

### Acceptance Criteria
- A user is able to add new blocks inline, with keyboard actions

### Note
- Design prototypes would be implemented in #704

### Pull requests
* [ ] https://github.com/dnadesign/silverstripe-elemental/pull/724

**Comment by clarkepaul** [comment]
My recommendation here is to show the add block action before and after each block if a block is hovered (maybe in the middle of the block rather than on the far right?). This means the user doesn't need to hover between the blocks to see the actions. We can also improve the look and feel of the transition (remove the light grey in-between faded look). A design will be required prior to this one being implemented.

**Comment by brynwhyman** [comment]
Before looking at this issue, we plan to investigate #455

**Comment by newleeland** [comment]
> My recommendation here is to show the add block action before and after each block if a block is hovered (maybe in the middle of the block rather than on the far right?). This means the user doesn't need to hover between the blocks to see the actions. We can also improve the look and feel of the transition (remove the light grey in-between faded look). A design will be required prior to this one being implemented.

**I've made two interactive prototypes to illustrate this**
https://codepen.io/newleeland/pen/ormVYx

**Prototype 1: Line design.** 
- Bigger cursor hitbox
- Smaller hover delay
- High contrast line

**Prototype 2:**
- Add block buttons always on
- However, can be less _obvious_ this is adding a block

**Comment by clarkepaul** [comment]
I think we should probably separate the design improvements to the tabbing issue. Opened a different issue to cover them here #704

**Comment by robbieaverill** [comment]
Nice @maxime-rainville
