### ISSUE TITLE
Title field causes fatal error on read only transformation

### ISSUE THREAD

**Issue by NightJar** [dnadesign/silverstripe-elemental#630]
Elemental `4.0.x-dev#1624abcfa413ceb1583fdf233cff280c61237a8f` has a non-recoverable fatal error when a user attempts to view a read only page with an `ElementalArea` on it.
By "non-recoverable" I mean that this error once seen persists even after enabling the user to edit that page again.

Reproduction steps:
- Create a user
- Create a group
- Give the group the ability to access the Pages section of the CMS (as the only permission) ![image](https://user-images.githubusercontent.com/778003/54096558-42f50f00-4411-11e9-941f-28a4cf05a4ba.png)
- Assign the new user to the new group
- Sign in as the new user and create a `BlocksPage` (in a browser/session)
- Edit that blocks page (add blocks, that have titles and have the displayed checked)
- Publish the blocks page
- Use the admin user on another browser/session to use "Site Settings: Access" tab and enable only Administrators to edit pages 
![image](https://user-images.githubusercontent.com/778003/54096590-6750eb80-4411-11e9-86d7-334486298892.png)
- On the browser/session with the new user logged in, refresh the page.
- Observe that the elemental edit view still loads
- Browse to the home page to ensure that it is read only (it should be).
- Browse back to the Blocks Page
- Observe an "Internal server error" toast message
- refresh the page (the URL should be correctly set to edit the Blocks Page)
- Observe a Alert level error `[Alert] Call to a member function Value() on null` 
![image](https://user-images.githubusercontent.com/778003/54096714-d0386380-4411-11e9-8c92-cdb0308dadc3.png)
- Interestingly also observe the lack of stack trace 
![image](https://user-images.githubusercontent.com/778003/54096728-e34b3380-4411-11e9-8dd5-3d3717ad9f82.png)

## Setup

- Error occurs on `vendor\dnadesign\silverstripe-elemental\src\Forms\TextCheckboxGroupField.php`
- using `cwp/cwp-recipe-kitchen-sink` as context for testing.
- Windows 10, PHP 7.1.10, Apache 2.4.23
- SilverStripe 4.3.x-dev, `framework#a8605b0`, `cms#543307a`, `admin#d1d0a73`, `versioned-admin#747c508`, `versioned#4ff6126` Elemental as per opening sentence.

**Comment by robbieaverill** [comment]
Fixing a null pointer exception should be pretty straight forward, wanna smash it out now?

**Comment by chillu** [comment]
This also breaks workflow on any blocks pages for authors who requested the approval, since they'll get a readonly view while the approval is pending. So effectively this stops the workflow+elemental combo. 

I also don't think it's as simple as a null value pointer guard here, looking at the stacktrace the readonly transformation seems to be called *twice* on the same instance. It works the first time, then craps out the second time.

**Comment by chillu** [comment]
And as usual, it's never that simple: https://github.com/silverstripe/silverstripe-framework/pull/8853 and https://github.com/symbiote/silverstripe-advancedworkflow/pull/388

**Comment by chillu** [comment]
Alright, I think this needs to be fixed on *both* a custom field implementation level, and on the form/cms/workflow level. Created a PR for the custom field implementation here: https://github.com/dnadesign/silverstripe-elemental/pull/635

**Comment by robbieaverill** [comment]
#635 merged
