### ISSUE TITLE
Very hard to disable 'Show title' option

### ISSUE THREAD

**Issue by jonom** [dnadesign/silverstripe-elemental#633]
`BaseElement` includes a `ShowTitle` boolean field which is added to the Title field on all blocks. This is overly opinionated IMO and I can think of lots of block types where you would never want to show a Title. I realise I don't have to respect this setting in templates, but showing the 'Display' checkbox on blocks that don't let you display the title is a bad UX. Users will think something is broken.

I eventually worked out how to hide this option but it's a hassle:

```php
public function getCMSFields()
{
    $fields = parent::getCMSFields();

    // Target the TextCheckboxGroupField combo field (it's name is Title but so is the text field within it)
    $wrapper = $fields->fieldByName('Title'); // No result - doesn't work
    $wrapper = $fields->dataFieldByName('Title'); // Wrong - returns the text field nested within the TextCheckboxGroupField
    $wrapper = $fields->findTab('Root.Main')->Fields()->first(); // This does the trick but it's fragile and could break very easily

    // Change the title to remove the '(displayed if checked)' part
    $wrapper->setTitle('Title');

    // Hide the checkbox field
    $fields->removeByName('ShowTitle');
    return $fields;
}
```

**Comment by robbieaverill** [comment]
You could probably replace the TextCheckboxGroupField (composite) with a simple TextField for Title as well

**Comment by ScopeyNZ** [comment]
This has been pointed out to me before. I think it's our use of a composite that has a weird name clash (or something - not currently diving into the code).

I'll put this as an `impact/low` bug because there are workarounds - you just have a play a bit to find them.

**Comment by ScopeyNZ** [comment]
I've been looking into this today. I think this could be a valid bug on `silverstripe/framework`. Currently you can't just "replace" a composite field:

https://github.com/silverstripe/silverstripe-framework/blob/5276b6cbb1ebd49d704734d940b0467c51b0d064/src/Forms/FieldList.php#L389

There's a call to `hasData` when replacing - I assume this is so the replaceField API can dive into composites.

It's a little better for `removeByName` because it assumes that you don't just mean datafields - but we do have some code that attempts to ensure "Title" is namespaced (for multiple element forms on one page). I think we can just remove that though.

**Comment by ScopeyNZ** [comment]
I've raised a PR that resolved #632 . Now you can also remove the composite `->removeByName('Title')` and then add back just a text field for title `->addFieldToTab('Root.Main', TextField::create('Title', 'Title'))`

**Comment by ScopeyNZ** [comment]
Okay I've raised an issue and PR on framework for fixing the issue with `replaceField`: https://github.com/silverstripe/silverstripe-framework/issues/8875 .

Referring to the example code:

```
$wrapper = $fields->fieldByName('Title');
```

This API needs the tab names. `$wrapper = $fields->fieldByName('Root.Main.Title');` works.

```
$wrapper = $fields->dataFieldByName('Title');
```

This "correctly" gets the title field from inside the composite. I guess the composite having the same name is confusing, but the composite isn't a "dataField" so it should return null if the inner title field was not named "Title".

```
$wrapper = $fields->findTab('Root.Main')->Fields()->first();
```

`$wrapper = $fields->findTab('Root.Main')->Fields()->fieldByName('Title')` also works but it's in the same vein as `$wrapper = $fields->fieldByName('Root.Main.Title');`.

**Comment by jonom** [comment]
Thanks @ScopeyNZ for the quick work! Sorry for the radio silence, had the week off

**Comment by thats4shaw** [comment]
I found that using `$fields->fieldByName('Root.Main.Title')` in the context of `getCMSFields()` returns the text field nested within the TextCheckboxGroupField which @jonom mentioned initially. 

It does works nicely in the context `updateCMSFields()`.

**Comment by thats4shaw** [comment]
Actually scratch that, I'm actually finding that `$fields->fieldByName('Root.Main.Title')` doesn't work when you aren't using inline editing 🤷‍♂️.

**Comment by thats4shaw** [comment]
Bringing this back from the dead but removing and replacing `ShowTitle` actually causes problems in regards to viewing archives.

I've settled on this approach:
```
$showTitle = $fields->fieldByName('Root.Main.Title.ShowTitle');
$showTitle->setDisabled(true);
```

And just setting `$defaults` for the elements as needed.
