### ISSUE TITLE
'Add block' dialogue - columns overlap with long block names

### ISSUE THREAD

**Issue by DorsetDigital** [dnadesign/silverstripe-elemental#639]
Elemental 4.0.3
silverstripe/admin 1.3.3
silverstripe/cms 4.3.3
silverstripe/framework 4.3.3   

When I add a block to a page, where the block names are long, the columns overlap in the popover:

![Screenshot from 2019-03-19 15-46-33](https://user-images.githubusercontent.com/15108750/54621697-1324b780-4a60-11e9-9660-aa2ebcbb7f0c.png)

I noticed that the popover seems to end up with some contradictory CSS from its classes (in bundle.css):

```
.popover-option-set {
  min-width: 320px;
}

.popover {
  max-width: 276px;
}
```

A quick workaround is:

```
.popover-option-set__button {
    width: 100%;
}
```

But this makes the list a single column rather than the multi-column layout.

**Comment by ScopeyNZ** [comment]
Thanks @DorsetDigital for the report! This component actually lives in the `silverstripe/admin` module so I'll transfer your issue there.

Hopefully our use of BEM CSS naming makes this fairly trivial to work around in client code.

I'll talk with @silverstripeux and see what the suggestion is for this.

**Comment by ScopeyNZ** [comment]
Oh upon further investigation there's already an issue open:

https://github.com/silverstripe/silverstripe-admin/issues/823

I'll link to this issue and close this in favour of that.
