### ISSUE TITLE
SilverStripe 4.x compatibility

### ISSUE THREAD

**Issue by JorisDebonnet** [dnadesign/silverstripe-elemental#64]
Are there any plans yet for SS4 compatibility? Haven't tested it yet, just curious whether anyone is already working on it. Should become relevant in a few months when the betas start coming out, and half a year later, 3.x will start being phased out.

**Comment by pitchandtone** [comment]
In progress on the SS4 branch.

**Comment by pitchandtone** [comment]
Relatively stable on the SS4 branch, but have yet to try on real project.

**Comment by JorisDebonnet** [comment]
Unfortunately I am (currently) no longer using this module as I was steered away from it. So feel free to close this issue or use it as a placeholder or anything.

**Comment by pitchandtone** [comment]
Can you give some more info on why you were steered away?

**Comment by JorisDebonnet** [comment]
Oh, not because there was something wrong with this module, but because my client wanted to revert to an older version of the CMS that they were used to...  (they wanted an 'exact copy' of a previous website CMS I'd made) I'll certainly consider this again when I work on a new website with a more flexible-minded client :)

**Comment by wilr** [comment]
4.0 support in ss4 branch.
