### ISSUE TITLE
Split any DataObject extending ElementContent to a new module

### ISSUE THREAD

**Issue by SilbinaryWolf** [dnadesign/silverstripe-elemental#65]
I really like the Elemental module, but it adds a fair few DataObjects that I don't need or particularly want. It'd be nice if this was split into "silverstripe-elemental-core" and "silverstripe-elemental".

I imagine repo-wise, all core functionality would be moved out to elemental-core, and then this module would be updated to require elemental-core in it's composer.json.

Unless I'm forgetting something, this would ensure painless backwards compat.

**Comment by wilr** [comment]
👍  We talked about this last year with @pitchandtone and he's keen for this. Let me know if you want to tackle the project. I was going to remove all components out completely apart from the 'base' objects

**Comment by SilbinaryWolf** [comment]
I'm not keen to tackle this. I still have to make time for this PR at some point:
https://github.com/dnadesign/silverstripe-elemental/pull/60

**Comment by wilr** [comment]
@pitchandtone Thoughts? Anyone got time to tackle? I'm happy to undertake it just don't want to duplicate any effort

**Comment by pitchandtone** [comment]
In progress on the SS4 branch.
