### ISSUE TITLE
feature request: Content blocks should have option to be decoupled from normal page publish functions

### ISSUE THREAD

**Issue by albanyacademy** [dnadesign/silverstripe-elemental#654]
Current workflow ignores states where content blocks can be in draft states while changes need to be made to the page itself - currently you would have to change values on the page class, publish, then quickly unpublish whatever content blocks might not be ready for publishing yet. Would also impact any potential versioning/history viewing with unnecessary publish/unpublish states being logged.

Not having this behaviour dictated by ownership would be beneficial to help content authors have draft block changes exist outside of page changes - obviously having a "publish everything" function is nice, but there should be accommodation for both. It would also help make elemental blocks more easily extensible for Campaign admin, I would think.

At the very least there needs to be some distinction between 

- publishing page changes vs 
- publishing content blocks vs
- publishing page changes AND content blocks

In an ideal world, I'd want each option displayed when clicking the Publish button on an elemental page, prompting the user to pick what they want published. I don't think having 3 different publish buttons would be good, probably a bit confusing, but that additional bit of dialogue would be beneficial.

**Comment by ScopeyNZ** [comment]
Hi @albanyacademy. Currently in 4.0.0 of elemental it is possible to publish blocks individually. Additionally you should be able to avoid publishing blocks when publishing a page by adjusting the `$owns` configuration on the page.

Currently you could make your own page type that has an `ElementalArea` but no `$owns` configuration for it. This would be "not having this behaviour dictated by ownership". You could then extend the button toolbar at the bottom of a page to have a "publish all blocks" if you wish. It's unlikely we'll support this within this module - we have enough trouble supporting the existing versioned relationship 😅. This would be a great addition for a little satellite module though.

I'll ping our UX team for any insights: @silverstripeux .

**Comment by clarkepaul** [comment]
Thanks for the insight. I think its a good idea but agree this is possibly module functionality. Ultimately you are saving the page name, URL, page settings, page move in site tree etc without affecting the blocks, this is something we have considered and might eventuate but not anytime soon.
