### ISSUE TITLE
updateAvailableTypesForClass hook $class is undefined

### ISSUE THREAD

**Issue by christopherdarling** [dnadesign/silverstripe-elemental#658]
see https://github.com/dnadesign/silverstripe-elemental/blob/master/src/Extensions/ElementalAreasExtension.php#L120

When using the updateAvailableTypesForClass($class, $list) hook, $class is always null.

**Comment by kinglozzer** [comment]
Heh, oops! Removing it will break things for anyone using the hook, so I’d suggest instead giving the variable a value like `$class = get_class($this->owner);`

**Comment by kinglozzer** [comment]
Closed by https://github.com/dnadesign/silverstripe-elemental/commit/ae3ca5cddd4400cdfe06583a50035f474bbfba28, thanks @christopherdarling!
