### ISSUE TITLE
Delete stale branches

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#662]
There's a few branches on this repo that are probably no longer required.

- `pulls/*` - I think both those branches are dead now?
- `1` - SS3 is security/critical bugfix only mode now - surely there are no minor releases of elemental 1 planned?
- `2` and `3` - The team at SS doesn't really anticipate any minor releases for these major versions either
- Older `1.x` branches - Do we still want to support all the minor release lines?

Any thoughts @robbieaverill @wilr ?

**Comment by wilr** [comment]
Go for it :)

**Comment by ScopeyNZ** [comment]
Done 😄
