### ISSUE TITLE
After installing elemental on existing pages they're all moved to draft

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#668]
Affected versions: __^4__

Steps to reproduce:

- Have a bunch of published pages of a certain page type
- Install elemental ^4
- Apply the elemental extension to your page type (where you have existing pages)
- `dev/build`
- Note that the site tree is showing your pages as modified now.

**Comment by ScopeyNZ** [comment]
Closed by #669

**Comment by brynwhyman** [comment]
@ScopeyNZ can you please confirm that this issue can be closed?

**Comment by ScopeyNZ** [comment]
Yes

**Comment by michalkleiner** [comment]
@brynwhyman I think this issue was fixed in a way that introduced a different problem — #687
