### ISSUE TITLE
Migrating UserDefinedForms from 3.x to 4.x with ElementalContentBlocks

### ISSUE THREAD

**Issue by pjayme** [dnadesign/silverstripe-elemental#672]
On version `4.1.0` of `dnadesign/silverstripe-elemental`, the `MigrateContentToElement` task fails to migrate `$UserDefinedForms` that lived in non-content block `HTMLFields` into its respective `Form` content blocks. The task extracts the `$UserDefinedForm` string from an existing `Content/HTMLField` then injects it into a `Content` elemental block and renders it as a `string` instead of the actual form.

We have written a script where we:
- First assume the `MigrateContentToElement` task has been run
- Checks all the Content elemental blocks and looks for the `$UserDefinedForm` string
- Creates a new `Form` content block on the same page as the existing `$UserDefinedForm`
- Removes the existing `$UserDefinedForm` string from the Content elemental block

Would be nice to have this integrated into the `MigrateContentToElement` task :)

**Comment by michalkleiner** [comment]
Submit a PR then?

**Comment by michalkleiner** [comment]
Although not always is the $UserDefinedForm the only thing in the content field, so the logic might be that you split the content block into two (pre/post the variable) and insert the form block in between.

**Comment by pjayme** [comment]
@michalkleiner shoot, thought I raised it as one 😅 

Yup, we've taken that into consideration

**Comment by brynwhyman** [comment]
@pjayme did your PR for this ever come through? I can't see it 😕

**Comment by pjayme** [comment]
Hiya @brynwhyman we've decided to run a few more tests on it and take it to production before we raise this PR. Ishan (@ishannz) was actually the one that built this, just raising on behalf of him :)
