### ISSUE TITLE
the method 'isinvalidpublishstate' does not exist on 'ElementVirtualLinked'

### ISSUE THREAD

**Issue by normann** [dnadesign/silverstripe-elemental#68]
Jesus, the latest code in master branch breaks in a very bad way, in ElementVirtualLinked.php, the caller of function isInvalidPublishState is ElementVirtualLinked object, but the function exists only in ElementVirtualLinked _Controller object.

I thought it is all due to the merge commit 7a2a086651d6eae15f0530e085f1c9ca880181ec
where the class ElementVirtualLinked_Controller added in a way that moves two functions, that originally belong to ElementVirtualLinked, to ElementVirtualLinked_Controller.

**Comment by rotassator** [comment]
Just submitted a PR to fix this error. https://github.com/dnadesign/silverstripe-elemental/pull/70

**Comment by wilr** [comment]
Fixed with #70
