### ISSUE TITLE
Content block H2 styling should match other block types

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#686]
### Overview
When you have the `silverstripe/recipe-content-blocks` installed, it's quickly obvious that the default CSS style for the block title is different between this block and others. 

I have heard from clients that due to the lack of consistency, they've been forced to omit the block title field and use the WYSIWYG to create H2s, etc.

### Examples
The below screenshot shows the issue. `<h2 class="content-block__title">Content block title</h2>` needs to look more like the other H2s
![image](https://user-images.githubusercontent.com/15868440/60317519-99d42380-99c3-11e9-8de6-b3164e333af7.png)

**Comment by robbieaverill** [comment]
I think this is a Wātea theme issue, right?

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/cwp-watea-theme/pull/81

**Comment by brynwhyman** [comment]
Ah, yeah good point. Thanks!

**Comment by robbieaverill** [comment]
Fixed in the theme, PR above
