### ISSUE TITLE
IE11 - editing ElementContent causes whole Elemental section to be removed from DOM

### ISSUE THREAD

**Issue by HJGreen** [dnadesign/silverstripe-elemental#700]
This is an extension of an issue raised here: silverstripe/silverstripe-cms#2459

Only applies to Internet Explorer 11 (and below)

## Affected versions:
`silverstripe-elemental` **4.1**
`silverstripe/admin` 1.4.1
`silverstripe/framework` 4.4.1

## Steps to reproduce

- Open a page which supports the ElementContent block in the CMS
- Add a new ElementContent block, or edit an existing one
- Begin typing in the TinyMCE editor
- IE will throw a JavaScript error as described in silverstripe/silverstripe-cms#2459

As a result of this the entire Elemental section will disappear from the DOM, leaving only the containing `<div>`. The only way to get the section to reappear is to reload the page.

![elemental-screen](https://user-images.githubusercontent.com/2873649/61699274-ba0ebc80-ad8e-11e9-9b37-4e6f20c07345.gif)

# Pull Requests
- [ ] ~https://github.com/silverstripe/silverstripe-admin/pull/945~
- [x] https://github.com/silverstripe/silverstripe-admin/pull/951

**Comment by robbieaverill** [comment]
Thanks for the bug report. Hopefully fixing the core issue would also fix this issue, but we should also try and build in some fault tolerance for elemental if we can, so that it doesn't break as spectacularly as this.

**Comment by robbieaverill** [comment]
@NightJar fancy reviewing this since you have IE11 native?

**Comment by robbieaverill** [comment]
I also found that in IE11 you can't press enter on an element to open its inline edit form - it opens the "add new block" bar instead. I haven't tested it again with the patch in this PR though, but something to keep in mind when we're doing IE11 fixes here.
