### ISSUE TITLE
Adjust order of actions in the options dropdown 

### ISSUE THREAD

**Issue by clarkepaul** [dnadesign/silverstripe-elemental#707]
The order of the actions in the dropdown has changed recently? 
It should be:
- Save
- Publish
- Unpublish
- Unpublish and archive

![image](https://user-images.githubusercontent.com/555033/62103258-fe9ada80-b2ef-11e9-8e6d-f927e18b6073.png)

# Pull request
* [ ] https://github.com/dnadesign/silverstripe-elemental/pull/717

**Comment by brynwhyman** [comment]
'Unpublish and archive" is expected to be implemented in #678

**Comment by maxime-rainville** [comment]
@clarkepaul FYI To rename "Archive" to "Unpublish and archive", I'll have to bump up the width of the action menu. Let me know if this is problematic for you

# Current width
![image.png](https://images.zenhubusercontent.com/5ac42fb74b5806bc2bcd8e13/b8d35087-5756-486c-8e06-fa0be69923ad)

# Suggested new width
![image.png](https://images.zenhubusercontent.com/5ac42fb74b5806bc2bcd8e13/f4771a99-b1c9-47cd-a97c-8e773a2fd544)

**Comment by clarkepaul** [comment]
Seeing as the label is quite long I'd actually prefer if we kept the label as "Archive" and the success message changes to say something like "Successfully unpublished and archived".

I think users would be expecting it to be removed from the site anyway.

FYI We have this message for pages...
<img width="245" alt="Pasted_Image_14_08_19__3_57_PM" src="https://user-images.githubusercontent.com/555033/62993614-3e46f200-beac-11e9-9c2c-199463a68848.png">

**Comment by robbieaverill** [comment]
Can that be covered in #678? I've merged the PR for this issue
