### ISSUE TITLE
ElementalSolrIndex leads to double indexing

### ISSUE THREAD

**Issue by chillu** [dnadesign/silverstripe-elemental#709]
https://github.com/dnadesign/silverstripe-elemental/commit/3a9b68e1272ba3d3fe70216aaa9c4bf209047271#diff-f4f232f03fb2b2386febaa611c6caef9

I'd say in 99% of the cases, this index won't cut it, and devs will create their own one anyway. Or extending the [CWPSearchIndex](https://github.com/silverstripe/cwp-search/blob/master/src/CwpSearchIndex.php).

The elemental index should be a how-to, not something you're force fed by default. From what I can tell, this has lead to double indexing of content since we introduced this back in 2017. So double the indexing time, double the index size. This has a significant impact on the usefulness of our overall search solution.

Given this is now part of our semver commitment, we can't really remove it without a major release (which won't benefit most of the target audience, namely CWP).

The [cwp docs](https://github.com/silverstripe/cwp/blob/master/docs/en/02_Features/01_Solr_search/03_Basic_usage.md) actually mention how you can create a filter whitelist. In lieu of actually fixing the underlying issue, I think the best we can do is to remind people upgrading that they should create such a whitelist.

**Comment by robbieaverill** [comment]
Yeah, we can deprecate it and write another one though

**Comment by chillu** [comment]
But what would that new index to replace the deprecated one do? Some people will have started relying on it, assuming it'll actually index pages and blocks.

**Comment by chillu** [comment]
https://github.com/dnadesign/silverstripe-elemental/pull/710
https://github.com/dnadesign/silverstripe-elemental/pull/711
https://github.com/dnadesign/silverstripe-elemental/pull/712
