### ISSUE TITLE
TinyMCE html editor not resizeable in block editor

### ISSUE THREAD

**Issue by chillu** [dnadesign/silverstripe-elemental#714]
It's way too tiny for even showing one large paragraph, and can be a blocker for content authors who want to embed and resize images.

Ideally the editor resizes automatically if you add more content, but at the very least it should have the drag handle that's built into TinyMCE already - and works in page editing context already.

Block editor

![image](https://user-images.githubusercontent.com/111025/62684384-ae6cf800-ba14-11e9-92e1-4c1acfdb1327.png)

Standard page editor

![image](https://user-images.githubusercontent.com/111025/62684482-dfe5c380-ba14-11e9-90ab-c52d0a643d52.png)

### PR:

#719

**Comment by robbieaverill** [comment]
I guess we lost the drag handle when we took the bottom toolbar out - it used to be there

**Comment by brynwhyman** [comment]
Yeah, this is definitely a regression.
