### ISSUE TITLE
Save/Publish button presentation different to save/publish presentation for Pages

### ISSUE THREAD

**Issue by jules0x** [dnadesign/silverstripe-elemental#726]
Standard SilverStripe pages have a visual distinction between draft and published pages, however in an element, it's not as clear. 

![image](https://user-images.githubusercontent.com/8979741/63814773-1f555f00-c986-11e9-8f03-1dada62ab9a0.png)
vs
![image](https://user-images.githubusercontent.com/8979741/63814746-03ea5400-c986-11e9-8339-570b28a636f0.png)

Is it possible/beneficial to follow the same styling/layout as at sitetree publish buttons?

**Comment by robbieaverill** [comment]
This should be resolved by https://github.com/silverstripe/silverstripe-admin/issues/904

**Comment by Cheddam** [comment]
Confirmed to be resolved by [silverstripe/silverstripe-admin#904](https://github.com/silverstripe/silverstripe-admin/issues/904).
