### ISSUE TITLE
Using uploadfield makes the CMS elemental area disappear

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#736]
## Overview
If you attempt to create a folder through the uploadfield, after creating the folder, the modal closes and the CMS elemental area disappears.

## Version affected
dnadesign/silverstripe-elemental  4.2.0     
silverstripe/asset-admin  1.4.2
silverstripe/framework 4.4.3 

## To reproduce
1. Select 'Add from files' in an uploadfield (I used the one available in a File block)
2. Select 'Add folder', and a folder name, and click 'Create' (with the intention of then uploading a new file)

**Expected result**
1. The new folder is created
2. You add a new file to the folder, select the file, and click 'Insert'
3. You see the file has been added to the uploadfield in the File block

**Actual result** 
1. The modal closes
2. You are presented with a blocks page without an elemental area
3. A page refresh is required

## PRs
 - [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/130
 - [x] https://github.com/dnadesign/silverstripe-elemental/pull/739
 - [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/132

**Comment by smokeycam** [comment]
Not sure if I should put this into its own 'issue' or not, or if this belongs in this repo? But I have the exact same issue/outcome in regards to using the 'Call To Action Link' (from the silverstripe/silverstripe-elemental-bannerblock)

**Comment by maxime-rainville** [comment]
Looks like this only affects UploadField in Elemental. UploadField in a regular context seem to work fine.

https://youtu.be/MKeNNDV8hek

@smokeycam Elemental is not tightly couple to any specific framework version. Could you let us know what version of Elemental and silverstripe/elemental-bannerblock you're using. We did some work on that field last month https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/29 that sound a little bit like what you're describing. It got merged in the 2.0 branch of `silverstripe/elemental-bannerblock`. Can you double check if you've got these fixes running on your install?

**Comment by smokeycam** [comment]
Sure thing, so here is a screen recording (attached) using a vanilla SS4 install with only the following (composer file): 

"silverstripe/recipe-plugin": "^1.2",
"silverstripe/recipe-cms": "4.4.2@stable",
"silverstripe-themes/simple": "~3.2.0",
"silverstripe/elemental-bannerblock": "^2.0"

Same issue regardless if the element is in published or modified state.
![elemental-cta-issue](https://user-images.githubusercontent.com/1677761/65640854-698e3680-e03f-11e9-9909-df2ff02ec31c.gif)

**Comment by maxime-rainville** [comment]
@smokeycam Could be related, but it might not be. I'd say open a separate issue on `silverstripe/elemental-bannerblock`. Maybe add whatever errors are thrown in the JS console.

**Comment by dnsl48** [comment]
This issue has been worked on as part of a larger initiative focused on reducing the experience debt of the SilverStripe CMS.

Thank you for taking the time to raise this issue and/ or provide feedback supporting the implementation.

This is an initiative from the teams maintaining the commercially supported module list. If you're interested to read more about this initiative and keep up with our progress have a look at our [blog post on experience debt](https://www.silverstripe.org/blog/weve-got-experience-debt-in-our-sights).

**Comment by brynwhyman** [comment]
I'm reopening this issue. Even with the inclusion of the related PRs, the expected result can't recreated.

The page fails a lot more gracefully, but we shouldn't close this issue until we can stop the failure in the first place.

**Comment by brynwhyman** [comment]
Here's what I see now: 
![image](https://user-images.githubusercontent.com/15868440/68638329-08c2ab00-0566-11ea-8bbc-efdc7068969e.png)
