### ISSUE TITLE
Drag 'n drop drop indicator looks broken

### ISSUE THREAD

**Issue by newleeland** [dnadesign/silverstripe-elemental#737]
### Overview

When dragging a block the line indicating where the block is no longer accurate (regression).

![Screen Shot 2019-09-30 at 5.00.21 PM.png](https://images.zenhubusercontent.com/596d365561b4ca3b0a74bd86/385ba0be-c89e-485e-a7de-e490bddd3058)

### Versions affected
- `dnadesign/silverstripe-elemental 4.x-dev`
- NOTE: I can't recreate in `dnadesign/silverstripe-elemental 4.2.1`

### Steps to recreate
1. Attempt to drag a block to reorder it
2. Identify that the block will be re-positioned correctly based on the position of the cursor; but the indicator is in the wrong place. +

This makes it really unclear to know where the block will end up.

### Expected result

The blue line should appear above or below the block the cursor (thats dragging a block) is currently over. If the cursor is in the top half of a block, it goes above; if the cursor is in the bottom half of a block, it goes below.

**Comment by brynwhyman** [comment]
I've just recreated this. It's a regression from the current stable release of 4.2.1.

Bumping the impact to critical as there's effectively no workaround here. While you may still be able to reorder blocks, the indicator severely confuses things, especially when you have a large amount of blocks.

The below GIF shows me attempting to put Block 3 in the middle. See how the indicator is above Block 1.
![block-reorder](https://user-images.githubusercontent.com/15868440/66356594-0483fa80-e9c8-11e9-9501-64281619c95d.gif)
