### ISSUE TITLE
modeladmin for Elemental

### ISSUE THREAD

**Issue by sunnysideup** [dnadesign/silverstripe-elemental#748]
I am wondering if it may be an idea to include a ModelAdmin for Elemental blocks. Most notably, this would allow you to search for all  Elements for one type and do something with them.  In my experience, this is a common requirement (e.g. add a second title, check that the image alignment is set correctly, etc.. etc...). 

Of course people can add their own ModelAdmin, but there are a couple of things that should be fixed in the core module at least. Most notably, the searchable fields should include a type (classname) fiel so that you actually select all the ones of one type. 

The modeladmin could also be used to:

a. find any draft elements
b. find any elements without an ElementalArea (e.g. summary_fields = [ElementalArea.Count => 'Use Count')
c. review any other detail for all elements

**Comment by ScopeyNZ** [comment]
This was actually specifically removed a few major version ago: https://github.com/dnadesign/silverstripe-elemental/issues/106

Some of these goals can be solved with improved reports, which are pretty trivially implemented in user code. At this point I'll close this issue assuming that past decisions were made for a reason, but feel free to continue the discussion if you feel strongly.

**Comment by sunnysideup** [comment]
Thank you for your quick and detailed reply. Much appreciated. I agree that this can be done other ways.
