### ISSUE TITLE
Add a preview link (draft and published) to each block

### ISSUE THREAD

**Issue by sunnysideup** [dnadesign/silverstripe-elemental#749]
I have found this code to be pretty useful (added to `BaseElement` via `DataExtension.updateCMSFields`

```php

        $liveLink =  $this->owner->PreviewLink();
        $draftLink = str_replace(
            '?',
            '?stage='.Versioned::DRAFT.'&',
            $liveLink
        );
        $fields->addFieldsToTab(
            'Root.Preview',
            [
                LiteralField::create(
                    'FrontEndLinkLive',
                    '<p><a href="'.$draftLink.'" target="_preview">preview draft version</a></p>'
                ),
                LiteralField::create(
                    'FrontEndLinkDraft',
                    '<p><a href="'.$liveLink.'" target="_preview">view published version</a></p>'
                ),
            ]
        );
```
Is this an idea?

**Comment by ScopeyNZ** [comment]
I think this would be more appropriate as an action, but possibly better left to user code. The preview should be enough (despite the fact it has "never worked" for you) for draft, and there is usually a link to the live version of the page on the UI already. Additionally, the code should probably at least include a `#anchor` so you're scrolled there.

**Comment by sunnysideup** [comment]
I think the reason the preview has never worked could be because we always end up with form fields that are "not react ready".  Is there a screenshot of what a preview even looks like?

I will make a module for preview.

**Comment by sunnysideup** [comment]
I had a look for a preview in a Silverstripe Demo site:

![image](https://user-images.githubusercontent.com/167154/68344208-577dd880-0153-11ea-977a-0a0c97ebe4d7.png)

I could not find any preview anywhere, am I missing anything?

I am expecting either:

a. 
![image](https://user-images.githubusercontent.com/167154/68344411-d410b700-0153-11ea-804a-cb899d7d72d1.png)

or b. preview pane in CMS split mode scrolls through to point on page where currently edited element is being viewed.

**Comment by sunnysideup** [comment]
I have implemented this here:

https://github.com/sunnysideup/silverstripe-elemental-edit-me-button
