### ISSUE TITLE
UserForms

### ISSUE THREAD

**Issue by digitall-it** [dnadesign/silverstripe-elemental#76]
Is this addon compatible with Elemental? How to use those together?

**Comment by colinburns** [comment]
Yes it is compatible... You can create a UserForm somewhere on your site and then you can choose the 'Form Element' element type and you'll see a drop down list of all your User Forms that you can choose to include in the Element.

**Comment by digitall-it** [comment]
I see, but as I nested elements together, I found out that $UserForm gets added twice to the page. So for time costraints had to not use it. I'll try to create a minimum use case for the presumed bug.
