### ISSUE TITLE
elemental not working upon fresh vanilla install?

### ISSUE THREAD

**Issue by globalvisionmedia** [dnadesign/silverstripe-elemental#766]
I believe I followed the instructions to create just the default site and added elemental but it seems to fail at the moment.

env:
WAMP
Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.5 mysqlnd 5.0.12-dev 

$composer create-project silverstripe/installer silverstripe-vanilla
create .env
$vendor/bin/sake dev/build
confirm site runs and CMS works
$composer require dnadesign/silverstripe-elemental ^4
edit themes/simple/templates/Layout/Page.ss to add $ElementalArea
call /dev/build and ?flush
CMS still shows original interface. no block editor.

no error in apache or php logs, no javascript errors
source shows it is loading en.js and bundle.js from DNAdesign/

You can see my entire site here: http://petertest.globalvision.com.au/ss.tgz  (8 megs) and http://petertest.globalvision.com.au/ss_vanilla.sql is the database.

Second issue:
if you then use composer to remove elemental it completely breaks the site for a few hours. changing to another browser, incognito or removing cookies or /tmp/* does not help so it must be caching something server side? Error says it's still looking for the DNAdesign classes.

**Comment by globalvisionmedia** [comment]
I believe I have fixed this. I had installed it using cygwin to run the command line parts. it seems that xampp's apache does not like the links that were created during the install process when elemental was installed.

The solution is to go into public\_resources\vendor\dnadesign\silverstripe-elemental\client and dereference the two links - I literally copied the two folders there. yuck, I know but it worked.

**Comment by ScopeyNZ** [comment]
This is a common SilverStripe qualm. You'll have to ensure that the SilverStripe composer vendor plugin (https://github.com/silverstripe/vendor-plugin) is set to "copy" mode when using Windows as symlink support is patchy.

**Comment by globalvisionmedia** [comment]
Should this be noted on the install page? Might save a few headaches?

Peter Hawkins
Managing Director
Global Vision
Suite 303, 517 Flinders Lane Melbourne 3000


(p) 1300 201 866 (m) 0414 674 666
http://www.gvmedia.com.au
________________________________

**Comment by ScopeyNZ** [comment]
I don't have time to introduce any docs changes right now, but the docs themselves are open source and you're welcome to contribute a patch if you think it will help someone? This might be the source you are looking for:

https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/00_Getting_Started/02_Composer.md

**Comment by ScopeyNZ** [comment]
Alternatively, please feel free to raise an issue on the framework repo with your suggestion (and maybe some example wording).
