### ISSUE TITLE
Locale switch issue when using indirect localisation for ElementalArea

### ISSUE THREAD

**Issue by conny-nyman** [dnadesign/silverstripe-elemental#771]
When using **indirect localisation** between Fluent and ElementalArea, how should one deal with changing locale while editing a block which is not inline editable? 

What I mean is that when you're inside the edit view for a custom block (which requires its own grid field) and then switch locale in the left sidebar, SilverStripe will return **404 Page not found** because the block is not translated.

![image](https://user-images.githubusercontent.com/25151529/72986909-eebd0880-3df1-11ea-9077-9f00506bb89a.png)

Are there any workarounds for this? Such as redirecting the user back out the page view with the new locale selected, instead of returning 404.

Steps to reproduce:
- Setup two Fluent locales
- Create a custom BaseElement with `$inline_editable` set to `false`
- Create a page with an elemental area (with indirect localisation)
- Add the new custom base element to the elemental area
- While editing the custom base element change the locale in the Fluent locale menu

Actual result:
- 404 Page not found

Expected result:
- Not sure what to expect here, but a 404 does not seem okay even though it makes sense from a developer perspective. Redirect the user back to the page view with the new locale?

**Comment by Cheddam** [comment]
Hey @conny-nyman, thanks for raising this issue! This problem doesn't seem unique to Elemental - switching locale while viewing any nested relationship will likely result in the same failure. I think it might make more sense to raise this in the [Fluent module](https://github.com/tractorcow-farm/silverstripe-fluent), as a solution would need to be applied directly to that module.

**Comment by conny-nyman** [comment]
Hey @Cheddam, good point :+1:  I create an issue for it in the Fluent repository now (https://github.com/tractorcow-farm/silverstripe-fluent/issues/589).
