### ISSUE TITLE
Access Page Function (like a form) from element

### ISSUE THREAD

**Issue by digitall-it** [dnadesign/silverstripe-elemental#78]
I cannot seem to be able to access a page function (like a form generator) from within an Element.

For example,

```
<% $BookingForm %>
<% $Up.BookingForm %>
<% $Top.BookingForm %>
```

None of these accesses BookingPage's function BookingForm()

**Comment by digitall-it** [comment]
Found out the function ControllerTop(). It should be documented more. May I help?

**Comment by pitchandtone** [comment]
@digitall-it submit a pr, keen to know where you think would be helpful.

**Comment by digitall-it** [comment]
I had to access a form from an element, and couldn't find a page handler. So I searched the documentation and couldn't find ControllerTop() mentioned anywhere. I found out by asking the community, so I thought other may need to know that piece of information, it's helpful. I'll submit a pr to the docs mentioning it.

**Comment by pitchandtone** [comment]
@wilr do you think it'd be appropriate to rename the function Top? So the API is common?

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
