### ISSUE TITLE
Document how to render individual elements

### ISSUE THREAD

**Issue by mestaritonttu** [dnadesign/silverstripe-elemental#788]
In the readme it is said
> In your page type layout template use $ElementalArea to render the elements to the page (in place of $Content).

I was unable to find any information on how to render individual elements, for example by referring to their title.

Today I've spent hours reading through the code and testing stuff out, but it is not clear to me how this could be achieved.

**Comment by Cheddam** [comment]
@mestaritonttu I think the intended approach would be to instead have separate ElementAreas for each "section" of the page you wanted to have element(s) in, rather than trying to fish a specific Element out of the default ElementArea. Could you describe your use-case?

**Comment by mestaritonttu** [comment]
> @mestaritonttu I think the intended approach would be to instead have separate ElementAreas for each "section" of the page you wanted to have element(s) in, rather than trying to fish a specific Element out of the default ElementArea. 

How is this possible? By the procedure described in "Defining your own elements"? This doesn't seem very different from the Silverstripe lesson for [adding custom fields to a page](https://www.silverstripe.org/learn/lessons/v4/adding-custom-fields-to-a-page-1), so it kind of feels like defeating the purpose of having a simpler workflow.

> Could you describe your use-case?

Use case is simply having multiple text fields for a page and being able to render them anywhere I want in my template. Ideally, I shouldn't have to touch any of the templates that ship with Elemental as I consider that "hacking the core files" and assume I would always have to restore the edits after updates.

**Comment by wget** [comment]
> that ship with Elemental as I consider that "hacking the core files"

Or maybe extends from these core classes in an inheritance dependency? That way, they won't get overwritten on updates.

**Comment by mestaritonttu** [comment]
I got some help from Silverstripe forums and created this ugly workaround:


**app/src/Page.php:**
```
namespace {

    use SilverStripe\CMS\Model\SiteTree;

    $elementalArray = [];
    class Page extends SiteTree
    {
        private static $db = [];

        private static $has_one = [];
        public static function blockToArray($key, $value) {
            global $elementalArray;
            $elementalArray[$key] = $value;
        }
        public static function renderBlock($key) {
            global $elementalArray;
            return $elementalArray[$key];
        }
    }
}
```

**vendor/dnadesign/silverstripe-elemental/templates/DNADesign/Elemental/Models/ElementalArea.ss:**
```
<% if $ElementControllers %>
    <% loop $ElementControllers %>
        $Top.OwnerPage.blockToArray($Title, $HTML)
    <% end_loop %>
<% end_if %>
```

**themes/simple/templates/Layout/Page.ss:**
```
<% include SideBar %>
<div class="content-container unit size3of4 lastUnit">
	<article>
		<h1>$Title</h1>
		<div class="content">$Content</div>
		<div>$ElementalArea</div>
		$renderBlock(firstblock)
		$renderBlock(secondblock)
	</article>
		$Form
		$CommentsForm
</div>
```

However, I don't understand why the HTML is rendered in escaped form. I tried using $HTML.raw in ElementalArea.ss, but that just leads to double the escaping (so the browser displays even the html entities themselves). I tried html_entity_decode in renderBlock, but it didn't help.

Anyway, would appreciate a solution that does not travel all around the place like this.

**Comment by kinglozzer** [comment]
@mestaritonttu I’m still confused about your use-case - elemental is designed so that you can create and re-order blocks, then render every block from that area together. If you need a second set of blocks (e.g. in a sidebar), you can add another elemental area and add a separate list of blocks for that.

In your example, if someone changes the title of a block in the CMS then that block will no longer render.

If you just want a few different HTML areas dotted around the template, you don’t need elemental to achieve that - if anything it will make it harder - just use `private static $db` etc on your page type.

**Comment by mestaritonttu** [comment]
Fair enough. I was just looking for a way **to avoid** this tedious field creation step. I am used to a different CMS/CMF where customisation of content is built into the fundamental architecture, so there is no need to go adding fields, rebuilding the database and creating functions for displaying the fields in the admin. Elemental appeared to me to be a promising way to achieve the same experience, but I was mistaken.
