### ISSUE TITLE
Standardise language around recipe / module versions

### ISSUE THREAD

**Issue by Cheddam** [dnadesign/silverstripe-elemental#791]
Last year we [passed an RFC]() to decouple patch-level releases in the core modules. This allowed, for example, `silverstripe/framework` to receive a patch version outside of the standard release cycle, and allowed modules like `silverstripe/cms` to _not_ receive a patch version during a hotfix (which would have had identical contents to the version before).

This is a win in many regards, but it also provides massive opportunity for confusion when it comes to describing a release. For example, the '4.5.2' hotfix release includes silverstripe/framework 4.5.3 and silverstripe/cms 4.5.1. Some tooling looks at one of these modules to determine the version of 'Silverstripe' in use, and there are other places that use the term 'CMS & Framework', which is even more confusing. What we want to refer to in all of these cases is the version of the **Silverstripe CMS Recipe** (tbc).

This issue attempts to compile a full list of places where we are using incorrect terminology and/or referring to the version information on the wrong package, so that we can adjust them all.

- [ ] The UI in the CMS references the cms module version version rather than the CMS Recipe version – [GitHub issue](https://github.com/silverstripe/silverstripe-installer/issues/276)
- [ ] The UI in Silverstripe Cloud references the framework version rather than the CMS Recipe version - [Jira issue](https://silverstripe.atlassian.net/browse/SC-1842)
- [ ] The [older changelogs in CWP (2)]() need to be tweaked retroactively to reference CMS Recipe
- [ ] The [changelogs in the main documentation](https://docs.silverstripe.org/en/4/changelogs/4.5.2/) don't reference CMS Recipes
  - It may be best to provide a breakdown of the module versions included in each release?
  - We should add a note to the changelog index page explaining that they track CMS Recipe versions
- [ ] [silverstripe.org/download references "CMS & Framework version"](https://www.silverstripe.org/download/) rather than CMS Recipe version
- [ ] Internal documentation on how to reference CMS Recipe versions going forward
- [ ] Topics in community Slack should reference CMS Recipe (currently 'Release')

**Comment by brynwhyman** [comment]
Added an existing issue in the description for:
> The UI in Silverstripe Cloud references the framework version rather than the CMS Recipe version (https://silverstripe.atlassian.net/browse/SC-1842)

**Comment by michalkleiner** [comment]
Is elemental the right place to do this?

**Comment by Cheddam** [comment]
@michalkleiner Nope, this definitely landed in the wrong bucket 😅
