### ISSUE TITLE
provideBlockSchema breaks the whole elemental-area if a file is missing

### ISSUE THREAD

**Issue by lerni** [dnadesign/silverstripe-elemental#802]
If an image is used as thumbnail per `provideBlockSchema()` and than deleted in assets-admin, the whole elemental-area in CMS fails to load (timeout). With this, the user is able to break the CMS :(
```php
protected function provideBlockSchema()
{
    $blockSchema = parent::provideBlockSchema();
    if ($this->Slides()->Count()) {
        if ($this->Slides()->Sort("SortOrder")->First()->SlideImageID) {
            $blockSchema['fileURL'] = $this->Slides()->Sort("SortOrder")->First()->SlideImage()->CMSThumbnail()->getURL();
        }
    }
    return $blockSchema;
}
```
This happens with `4.3.2` - most probable all versions with support for `provideBlockSchema()`.

**Comment by maxime-rainville** [comment]
Can you provide some replication steps? I tried replicating the issue in Silverstripe CMS 4.6.0-beta1 and didn't managed to.

**Comment by lerni** [comment]
thank you for taking the time looking into it and try to reproduce! I've broken down a project with a minimal setup to replicate it:
https://bitbucket.org/kraftausdruck/elemental-schema/src/master/

Steps to reproduce (PHP 7.3 used):
- clone above, composer install & setup env-file
- login to CMS
- create an ElementPage
- add an text-image element
- add an image & save element, may also page
- go into asset-admin
- delete image associated before
- try loading the element-page in CMS again - boom

**Comment by lerni** [comment]
just FYI - still same with elemental "4.4.0-rc1" - see repo above

**Comment by lerni** [comment]
@gheggie pointed out I should use `>SlideImage()->exists()` instead of just `->SlideImageID`
