### ISSUE TITLE
Regression 4.6.0 / Postgres index relation already exists

### ISSUE THREAD

**Issue by emteknetnz** [dnadesign/silverstripe-elemental#808]
First happened on this PR, which bumped the recipe version that PQSQL is tested against from 4.5.x-dev to 4.6.x-dev, so possibly it's related to that

Otherwise, may be something in https://github.com/dnadesign/silverstripe-elemental/compare/4.3..4.4

The postgres failure:

https://travis-ci.org/github/dnadesign/silverstripe-elemental/jobs/698651852

```
PHP Fatal error:  Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query:

create index "ix_a32d98fbe585c49c2c18e1e14f7cdbe4" ON "Page" ("ElementalAreaID");

ERROR:  relation "ix_a32d98fbe585c49c2c18e1e14f7cdbe4" already exists in /home/travis/build/dnadesign/silverstripe-elemental/vendor/silverstripe/framework/src/ORM/Connect/DBConnector.php:64

Stack trace:

#0 /home/travis/build/dnadesign/silverstripe-elemental/vendor/silverstripe/postgresql/code/PostgreSQLConnector.php(234): SilverStripe\ORM\Connect\DBConnector->databaseError('Couldn't run qu...', 256, 'create index "i...', Array)

#1 /home/travis/build/dnadesign/silverstripe-elemental/vendor/silverstripe/postgresql/code/PostgreSQLConnector.php(246): SilverStripe\PostgreSQL\PostgreSQLConnector->preparedQuery('create index "i...', Array, 256)

#2 /home/travis/build/dnadesign/silverstripe-elemental/vendor/silverstripe/framework/src/ORM/Connect/Database.php(159): SilverStripe\PostgreSQL\PostgreSQLConnector->query('create index "i...', 256)

#3 /home/travis/build/d in /home/travis/build/dnadesign/silverstripe-elemental/vendor/silverstripe/framework/src/ORM/Connect/DBConnector.php on line 64
```

## PRs
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/9555

**Comment by dnsl48** [comment]
That appears to be a regression caused by https://github.com/silverstripe/silverstripe-framework/commit/052c5cbc38210476ffce7d98dc052fa09b4e5e5f (part of [4.6.0-rc1](https://docs.silverstripe.org/en/4/changelogs/beta/4.6.0-beta1/)).
I'm investigating what exactly is going on there.

**Comment by dnsl48** [comment]
A patch with a fix is here - https://github.com/silverstripe/silverstripe-framework/pull/9555
Should be in `4.6.1` release.
