### ISSUE TITLE
Add GraphQL endpoints

### ISSUE THREAD

**Issue by adrexia** [dnadesign/silverstripe-elemental#83]
As discussed with John, it would be very useful for elemental to have some GraphQL endpoints in the ss4 upgrade. Having these in place would make it easier to adapt the CMS interface, and give us more flexibility on how the frontend is rendered.

**Comment by nicolewilliams16** [comment]
I don't think this will make the MVP for 2.0.0 but should be factored into our next phase of work

**Comment by robbieaverill** [comment]
This might become a requirement for upcoming work on a page level history viewer component

**Comment by robbieaverill** [comment]
There's going to be some amount of GraphQL scaffolding added as part of the history viewer work - see #202 for this module, and wider discussion at https://github.com/silverstripe/silverstripe-versioned/issues/37

**Comment by robbieaverill** [comment]
@adrexia we've been adding some basic GraphQL operations as part of the elemental React implementation in the master branch lately, this will include things like read, write, publish, unpublish, archive, reorder, etc. If there's more that you'd like, feel free to reopen this issue =)

**Comment by robbieaverill** [comment]
It's worth mentioning that these operations will exist in the admin GraphQL schema, not the frontend. With the option to have multiple GraphQL schemas I think we'll expect that any frontend schemas would be defined by user code rather than default (for now at least).
