### ISSUE TITLE
LIVE content lost when saving DRAFT copy of page (with decoupled OwnerClassName)

### ISSUE THREAD

**Issue by jakxnz** [dnadesign/silverstripe-elemental#836]
# Versions

```
silverstripe/framework        4.5.2
dnadesign/silverstripe-elemental    4.4.0
```

## Description

I saved (not published) a page (type: HomePage), and notice that the `LIVE` view of the page suddenly lost all of its content blocks

## Steps to reproduce

1. From the CMS create a page with type `Page`
2. Add blocks to the page's elemental area. For testing, you'll also need to Publish the page.
3. Confirm that the `LIVE` view of the page has the blocks you created (preferably test in a browser with no session, i.e Incognito)
4. Change the page type to anything else e.g `HomePage`
5. Publish the page
6. Modify the page Title, and Save the page (do not publish)
7. Visit the `LIVE` view of the page (preferably test in a browser with no session, i.e Incognito)

## Expected result

- All blocks are visible

## Actual result

- No blocks are visible

## Analysis

I notice that the code in `ElementalArea::getOwnerPage()` makes the assumption that the ElementalArea's `OwnerClassName` still matches the `Page`'s `ClassName`

https://github.com/dnadesign/silverstripe-elemental/blob/4/src/Models/ElementalArea.php#L207
```
$page = DataObject::get_one($class, [
    "\"{$table}\".\"{$areaID}\" = ?" => $this->ID,
    "\"{$baseTable}\".\"ClassName\" = ?" => $class
]);

if ($page) {
    $this->setOwnerPageCached($page);
    return $page;
}
```

When no record is matched, it fails over to the `DRAFT` record, which can't be viewed from the LIVE view.

**Comment by jakxnz** [comment]
I can see this was fixed in 4.4.1 https://github.com/dnadesign/silverstripe-elemental/releases/tag/4.4.1

Solution: Upgrade to 4.4.1

**Comment by michalkleiner** [comment]
It's always good to try the latest version first before spending time on raising an issue.

**Comment by kinglozzer** [comment]
Thanks for confirming it’s fixed @jakxnz!

**Comment by jakxnz** [comment]
@michalkleiner, agreed. Though it took me a good while to isolate the issue to this module. So I raised it to try and help others searching for the issue.
