### ISSUE TITLE
Add ability to have multiple element areas

### ISSUE THREAD

**Issue by pitchandtone** [dnadesign/silverstripe-elemental#84]
Similar to Content Blocks module, although I'd prefer to have two has_ones rather than defining it in YML.

$has_one = array(
 "ContentArea" => "ElementArea"
 "SideBarArea" => "ElementArea"
);

**Comment by pitchandtone** [comment]
In progress on the SS4 branch, needs more testing.

**Comment by wilr** [comment]
This has now been implemented and tested.

**Comment by sparkcom** [comment]
Does this mean we can now have more than 1 ElementArea as show by codes from @pitchandtone ? 

If so, it would be great to see some information in the Readme.md file 

Regards,

**Comment by brynwhyman** [comment]
Hey @sparkcom, I've raised the following issue to help you (and others) out https://github.com/dnadesign/silverstripe-elemental/issues/759
