### ISSUE TITLE
The Block picker confuses the preview

### ISSUE THREAD

**Issue by maxime-rainville** [dnadesign/silverstripe-elemental#848]
When I click the "add block" button the preview area shrinks for some reason. When I dismiss the Block picker, it goes back to normal.

Tested in Firefox and Chrome.

![image](https://user-images.githubusercontent.com/1168676/98194452-52c94b80-1f84-11eb-9161-3a32b8fd1994.png)

https://youtu.be/tmUT6beJQac

### Notes
- It's not just the preview that is affected, any viewport on the right is 'shifted'
- Could this be related to the Reactstrap 8 upgrade?
- This has been confirmed on multiple browsers

**Comment by emteknetnz** [comment]
Issue looks to be reactstrap / popper upgrade related:

There's an extra `<div>` in there for 1.7 which was the `position: absolute` and `transform3d` happens

On 1.6 this overrode the `min-width: 280px` on `.popover-option-set` defined in `admin/client/src/components/PopoverOptionSet.scss`.  Now in 1.7 that's not being overridden.

1.6:
![image](https://user-images.githubusercontent.com/4809037/98744414-8ab61000-2416-11eb-8401-0037138fe2f3.png)

1.7:
![image](https://user-images.githubusercontent.com/4809037/98744448-97d2ff00-2416-11eb-9b67-196fd696179f.png)

**Comment by emteknetnz** [comment]
Fixed in https://github.com/silverstripe/silverstripe-admin/pull/1154
