### ISSUE TITLE
Include content blocks in CMS search

### ISSUE THREAD

**Issue by pitchandtone** [dnadesign/silverstripe-elemental#87]
The CMS search should be expanded to return a variety of items
This is important if content blocks are treated as “first class” content holders. If your website mainly uses content blocks for display, CMS search is effectively broken at the moment.
In order to do this efficiently, we need to either denormalise searchable content into the “owner” record (e.g. copying MyContentBlock.Summary into SiteTree._SearchContent). 
Or we optionally hook up fulltextsearch to the CMS

**Comment by jules0x** [comment]
https://github.com/dnadesign/silverstripe-elemental/tree/ss4-searchable
✌️

**Comment by jules0x** [comment]
https://github.com/dnadesign/silverstripe-elemental/pull/98

The aggregate SearchContent field on ElementalArea.php stores the rendered and tag-stripped content of it's children. This field is suitable for searching against for returning a page result. The search only works with the search term field.

**Comment by pitchandtone** [comment]
Fixed by https://github.com/dnadesign/silverstripe-elemental/pull/98
