### ISSUE TITLE
History viewer

### ISSUE THREAD

**Issue by pitchandtone** [dnadesign/silverstripe-elemental#89]
Allow history comparison for nested objects (e.g. blocks) from a page context
Shareable comparison links which can be used for workflow emails and general author collaboration
Discussion on UX

**Comment by pitchandtone** [comment]
We have had this working on the SS3 version of Elemental using bluehousegroup/silverstripe-data-object-version-viewer but I have yet to try it on SS4.

Plus the latest version of the module seems to have some rewrites that I haven't got my head around yet.

**Comment by pitchandtone** [comment]
I have asked about SS4 compatibility here: https://github.com/bluehousegroup/silverstripe-data-object-version-viewer/issues/16

**Comment by robbieaverill** [comment]
This is going to be done in core in the near future. I suggest we close this issue for now.

Reference: https://github.com/silverstripe/silverstripe-versioned/issues/37

**Comment by robbieaverill** [comment]
Closing in favour of core functionality being introduced soon =) https://github.com/silverstripe/silverstripe-versioned/issues/37
