### ISSUE TITLE
Better visual GridField selector for “add block” UI

### ISSUE THREAD

**Issue by pitchandtone** [dnadesign/silverstripe-elemental#90]
Allow for more UX control than in the default dropdown
Allow thumbnails (e.g. “three squares” icon for a three-image gallery tile)
Categories for available blocks
Description on what a block does
Should be a generic GridField component

**Comment by chillu** [comment]
Designs: https://projects.invisionapp.com/share/VMDZ9YAGX#/screens/261615433

![image](https://user-images.githubusercontent.com/111025/36646823-a080648a-1ae1-11e8-8d86-d132f6771ff4.png)

![image](https://user-images.githubusercontent.com/111025/36646826-ac2ca30c-1ae1-11e8-837f-0b87a5765dbe.png)

**Comment by clarkepaul** [comment]
@newleeland will create some mockups for this.

**Comment by robbieaverill** [comment]
We're doing this at the moment and tracking progress in issues like https://github.com/dnadesign/silverstripe-elemental/issues/338 https://github.com/dnadesign/silverstripe-elemental/issues/339 https://github.com/dnadesign/silverstripe-elemental/issues/340 https://github.com/dnadesign/silverstripe-elemental/issues/341, let's track progress there to reduce duplication =)
