### ISSUE TITLE
CWP: UserForms Block

### ISSUE THREAD

**Issue by pitchandtone** [dnadesign/silverstripe-elemental#91]
Already exists in elemental
Currently, requires a page creation which will confuse authors
Allow removal of “user form” page type option, create userform “pages” in separate section and encourage their use through a block on a generic page

I would love Userforms to be an extension that is applied to a page, so that we could apply it to a block just as easily.

**Comment by asecondwill** [comment]
This would be great.  This is the only ref i could find on how to include userforms by adding a page,  ill give it a go.

Have you tried forms in elements using Flexi Forms?  that uses extensions so might work like you say.

**Comment by asecondwill** [comment]
I tried it out,  ok to add in the cms,  just a note in the UI to say create the page first would help

But the UX for the site user is odd.  it takes you off to a different page on submit.

**Comment by wilr** [comment]
Done, see https://github.com/dnadesign/silverstripe-elemental-userforms. PR for making this happen https://github.com/dnadesign/silverstripe-elemental-userforms/pull/1
