### ISSUE TITLE
CWP: Contentreview integration

### ISSUE THREAD

**Issue by pitchandtone** [dnadesign/silverstripe-elemental#93]
Make extension independent of model (also allow reviewing individual content blocks)
Ensure reports show all reviewable types
Ensure reminder email links work with all reviewable types

**Comment by jules0x** [comment]
Contentreview hasn't yet started migrating to SS4.

**Comment by robbieaverill** [comment]
Content review should be ready for integration testing on SS4 now, I'm going to triage as an enhancement

**Comment by raissanorth** [comment]
I have tested this at the page level and content review appears to be integrated. Reviewing Elemental Pages works as expected. 

I suggest that this is raised as a separate feature request on the Content Review module itself. If we enable the review of individual content blocks, we will have to discuss how to approach nested content blocks and general data objects for instance.
