### ISSUE TITLE
Better visual GridField selector for “link existing” UI

### ISSUE THREAD

**Issue by pitchandtone** [dnadesign/silverstripe-elemental#95]
Refer to content blocks module for modal UI which I believe is better

**Comment by pitchandtone** [comment]
Need to use GridFieldAddExistingSearchHandler and extend to do add() like ElementalGridFieldAddExistingAutocompleter handles this currently.

**Comment by robbieaverill** [comment]
I think we could probably move this issue to github.com/dnadesign/silverstripe-elemental-virtual now

**Comment by robbieaverill** [comment]
Issue moved to [dnadesign/silverstripe-elemental-virtual #5](https://github.com/dnadesign/silverstripe-elemental-virtual/issues/5) via [**ZenHub**](https://www.zenhub.com/)
