### ISSUE TITLE
New generic inline editor FormField (similar to WidgetAreaEditor)

### ISSUE THREAD

**Issue by pitchandtone** [dnadesign/silverstripe-elemental#96]
Shows the edit forms in collapsible panels
Should be GridField based (useful in other contexts as well, e.g. quick edit in ModelAdmin)
Has enough extension hooks to allow stuff like flagging a row as “changed”, or indicate workflow states
Example implementation: https://github.com/smindel/silverstripe-GridFieldAddOns/blob/master/docs/en/GridFieldExpandableForm.md

**Comment by pitchandtone** [comment]
And Richer overview on GridField rows

**Comment by be2n** [comment]
Invision files for inline editing designs: https://invis.io/EQGL9JRJFYV

**Comment by clarkepaul** [comment]
cc @newleeland

**Comment by clarkepaul** [comment]
Relies on React Gridfield work possibly. Related https://github.com/silverstripe/silverstripe-admin/issues/463

**Comment by robbieaverill** [comment]
We're working on this at the moment with the React elemental editor rewrite, progress can be tracked on the numerous issues floating around at the moment
